# copybara:uncomment package(default_applicable_licenses = ["@org_tensorflow//tensorflow:license"])

licenses(["notice"])

filegroup(
    name = "hexagon_delegate",
    srcs = ["HexagonDelegate.java"],
    visibility = ["//visibility:public"],
)
