package(
    # copybara:uncomment default_applicable_licenses = ["@org_tensorflow//tensorflow:license"],
    default_visibility = ["@org_tensorflow//tensorflow:internal"],
    licenses = ["notice"],
)

exports_files(glob(["*.html"]) + glob(["*.pb"]) + glob(["*.dot"]))
