version: 2
updates:
  # Keep GitHub Actions up to date
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "ci"
    groups:
      # Group all github actions updates together to reduce PR noise
      actions-dependencies:
        patterns:
          - "*"
