"""Repository rules and macros for Android NDK environment checks.

This is a workaround for accessing environment variables in .bzl files.
Bazel doesn't allow accessing environment variables during loading phase, except
through repository rules. This rule checks if ANDROID_NDK_HOME is set and
writes the result to current_android_ndk_env.bzl, which can be loaded by
other .bzl files.
"""

def _check_android_ndk_env_impl(ctx):
    ndk_home = ctx.getenv("ANDROID_NDK_HOME")
    if not ndk_home:
        # Try to find NDK in standard GitHub Actions location
        result = ctx.execute(["bash", "-c", "ls -d /usr/local/lib/android/sdk/ndk/* | sort -V | tail -n 1"])
        if result.return_code == 0:
            ndk_home = result.stdout.strip()

    ndk_home_is_set = bool(ndk_home) and len(ndk_home.strip()) > 0

    # .bzl file contains ANDROID_NDK_HOME_IS_SET = True if ANDROID_NDK_HOME is set.
    content = "# Generated by check_android_ndk_env.bzl\n"
    content += "ANDROID_NDK_HOME_IS_SET = "
    content += "True" if ndk_home_is_set else "False"
    content += "\n"
    content += "ANDROID_NDK_HOME = \"" + (ndk_home if ndk_home_is_set else "") + "\"\n"
    ctx.file("current_android_ndk_env.bzl", content = content)

    # Dummy BUILD file to make the repository is valid.
    ctx.file("BUILD", content = "")

check_android_ndk_env = repository_rule(
    implementation = _check_android_ndk_env_impl,
    local = True,
    environ = ["ANDROID_NDK_HOME"],
)
