// Copyright 2025 Google LLC.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#include <any>
#include <cstdint>
#include <cstdlib>
#include <memory>
#include <string>
#include <tuple>
#include <vector>

#include "testing/base/public/gunit.h"
#include "ml_drift/common/data_type.h"  // from @ml_drift
#include "ml_drift/common/ir_model.h"  // from @ml_drift
#include "ml_drift/common/operations.h"  // from @ml_drift
#include "ml_drift/common/shape.h"  // from @ml_drift
#include "ml_drift/common/tensor.h"  // from @ml_drift
#include "ml_drift_delegate/tflite/convert/convert_testing_utils.h"
#include "ml_drift_delegate/tflite/convert/stub_delegate.h"
#include "ml_drift_delegate/tflite/ir_model_builder_helper.h"
#include "tflite/builtin_ops.h"
#include "tflite/c/builtin_op_data.h"
#include "tflite/c/c_api.h"
#include "tflite/c/common.h"
#include "tflite/interpreter.h"

namespace litert::ml_drift::ir {
namespace {

class ConvertDepthwiseConvTest
    : public ::testing::TestWithParam<std::tuple<
          TfLiteType, bool, bool, TfLitePadding, TfLiteFusedActivation, int>> {
 protected:
  void SetUp() override {
    delegate_ = CreateStubDelegate();
    ASSERT_TRUE(delegate_);
    std::tie(dtype_, const_weights_, use_bias_, padding_, activation_,
             depth_multiplier_) = GetParam();
  }

  void TearDown() override { DeleteStubDelegate(delegate_); }

  TfLiteDelegate* delegate_;
  TfLiteType dtype_;
  bool const_weights_;
  bool use_bias_;
  TfLitePadding padding_;
  TfLiteFusedActivation activation_;
  int depth_multiplier_;
};

TEST_P(ConvertDepthwiseConvTest, Parameterized) {
  // Generate a model with a depthwise conv op.
  SingleOpInterpreterBuilder model(kTfLiteBuiltinDepthwiseConv2d,
                                   /*version=*/1);
  const size_t element_size = (dtype_ == kTfLiteFloat32) ? 4 : 2;
  model.AddInput(dtype_, {1, 2, 3, 1});  // input data
  std::vector<uint8_t> weights_data(depth_multiplier_ * element_size, 0);
  if (const_weights_) {
    model.AddConstInput(dtype_, {1, 1, 1, depth_multiplier_}, weights_data);
  } else {
    model.AddInput(dtype_, {1, 1, 1, depth_multiplier_});
  }
  std::vector<uint8_t> bias_data;
  if (use_bias_) {
    bias_data.assign(depth_multiplier_ * element_size, 0);
    model.AddConstInput(dtype_, {depth_multiplier_}, bias_data);
  }
  model.AddOutput(dtype_, {1, 2, 3, depth_multiplier_});  // output
  TfLiteDepthwiseConvParams* params =
      reinterpret_cast<TfLiteDepthwiseConvParams*>(
          calloc(1, sizeof(TfLiteDepthwiseConvParams)));
  params->depth_multiplier = depth_multiplier_;
  params->padding = padding_;
  params->stride_height = 1;
  params->stride_width = 1;
  params->activation = activation_;
  model.SetParameters(params);

  // Build the interpreter.
  std::unique_ptr<::tflite::Interpreter> interpreter = model.Build();
  ASSERT_TRUE(interpreter);

  // Delegate the graph.
  ASSERT_EQ(interpreter->ModifyGraphWithDelegate(delegate_), kTfLiteOk);

  // Inspect the IrModel generated by the delegate.
  const ::ml_drift::ir::IrModel* ir_model = GetIrModel(delegate_);
  ASSERT_TRUE(ir_model);
  const int expected_model_inputs = const_weights_ ? 1 : 2;
  EXPECT_EQ(ir_model->inputs().size(), expected_model_inputs);
  EXPECT_EQ(ir_model->outputs().size(), 1);
  ASSERT_EQ(ir_model->ops().size(), activation_ == kTfLiteActNone ? 1 : 2);
  const ::ml_drift::ir::IrOp* dw_conv_op = ir_model->op(0);
  const int expected_dw_conv_inputs = const_weights_ ? 1 : 2;
  EXPECT_EQ(dw_conv_op->inputs.size(), expected_dw_conv_inputs);
  EXPECT_EQ(dw_conv_op->outputs.size(), 1);
  EXPECT_EQ(dw_conv_op->name, "depthwise_convolution");
  const ::ml_drift::DepthwiseConvolution2DAttributes* attr =
      std::any_cast<::ml_drift::DepthwiseConvolution2DAttributes>(
          &dw_conv_op->attr);
  ASSERT_TRUE(attr);
  if (const_weights_) {
    EXPECT_FALSE((std::get<::ml_drift::Tensor<::ml_drift::OHWI,
                                              ::ml_drift::DataType::FLOAT32>>(
                      attr->weights)
                      .data.empty()));
  } else {
    EXPECT_TRUE((std::get<::ml_drift::Tensor<::ml_drift::OHWI,
                                             ::ml_drift::DataType::FLOAT32>>(
                     attr->weights)
                     .data.empty()));
  }
  if (use_bias_) {
    EXPECT_FALSE(attr->bias.data.empty());
  } else {
    EXPECT_TRUE(attr->bias.data.empty());
  }

  // Sanity check inference.
  ASSERT_EQ(interpreter->AllocateTensors(), kTfLiteOk);
  ASSERT_EQ(interpreter->Invoke(), kTfLiteOk);
}

INSTANTIATE_TEST_SUITE_P(
    ConvertDepthwiseConvTest, ConvertDepthwiseConvTest,
    ::testing::Combine(
        ::testing::Values(kTfLiteFloat32, kTfLiteFloat16),  // dtype
        ::testing::Bool(),                                  // const_weights
        ::testing::Bool(),                                  // use_bias
        ::testing::Values(kTfLitePaddingSame,
                          kTfLitePaddingValid),             // padding
        ::testing::Values(kTfLiteActNone, kTfLiteActRelu),  // activation
        ::testing::Values(1, 2)                             // depth_multiplier
        ),
    [](const ::testing::TestParamInfo<ConvertDepthwiseConvTest::ParamType>&
           info) {
      std::string name =
          std::string(std::get<0>(info.param) == kTfLiteFloat32 ? "float32"
                                                                : "float16") +
          (std::get<1>(info.param) ? "_const" : "_runtime") +
          (std::get<2>(info.param) ? "_bias" : "_nobias") +
          (std::get<3>(info.param) == kTfLitePaddingSame ? "_same" : "_valid") +
          (std::get<4>(info.param) == kTfLiteActNone ? "_noactivation"
                                                     : "_relu") +
          "_dm" + std::to_string(std::get<5>(info.param));
      return name;
    });

TEST(ConvertDepthwiseConvTest, SpannedWeights) {
  IrModelBuilderOptions options;
  options.enable_spanned_weights = true;
  std::unique_ptr<TfLiteDelegate, void (*)(TfLiteDelegate*)> delegate(
      CreateStubDelegate(options), DeleteStubDelegate);

  SingleOpInterpreterBuilder model(kTfLiteBuiltinDepthwiseConv2d,
                                   /*version=*/1);
  model.AddInput(kTfLiteFloat32, {1, 2, 2, 2});  // input data
  std::vector<float> weights_data = {1.0f, 2.0f};
  const uint8_t* p = reinterpret_cast<const uint8_t*>(weights_data.data());
  std::vector<uint8_t> weights_bytes(p,
                                     p + weights_data.size() * sizeof(float));
  model.AddConstInput(kTfLiteFloat32, {1, 1, 1, 2}, weights_bytes);
  model.AddOutput(kTfLiteFloat32, {1, 2, 2, 2});  // output
  TfLiteDepthwiseConvParams* params =
      reinterpret_cast<TfLiteDepthwiseConvParams*>(
          calloc(1, sizeof(TfLiteDepthwiseConvParams)));
  params->depth_multiplier = 1;
  params->padding = kTfLitePaddingValid;
  params->stride_height = 1;
  params->stride_width = 1;
  params->activation = kTfLiteActNone;
  model.SetParameters(params);

  std::unique_ptr<::tflite::Interpreter> interpreter = model.Build();
  ASSERT_TRUE(interpreter);
  ASSERT_EQ(interpreter->ModifyGraphWithDelegate(delegate.get()), kTfLiteOk);

  const ::ml_drift::ir::IrModel* ir_model = GetIrModel(delegate.get());
  ASSERT_TRUE(ir_model);
  ASSERT_EQ(ir_model->ops().size(), 1);

  const ::ml_drift::ir::IrOp* dw_conv_op = ir_model->op(0);
  const auto* attr =
      std::any_cast<::ml_drift::DepthwiseConvolution2DAttributes>(
          &dw_conv_op->attr);
  ASSERT_TRUE(attr);

  const auto& weights = std::get<
      ::ml_drift::Tensor<::ml_drift::OHWI, ::ml_drift::DataType::FLOAT32>>(
      attr->weights);
  EXPECT_TRUE(weights.data.empty());
  EXPECT_FALSE(weights.spanned_data.empty());
  EXPECT_EQ(weights.spanned_data.data(),
            reinterpret_cast<const float*>(weights_bytes.data()));
}

TEST(ConvertDepthwiseConvTest, TransposeWeights1x1DepthMultiplier) {
  std::unique_ptr<TfLiteDelegate, void (*)(TfLiteDelegate*)> delegate(
      CreateStubDelegate(), DeleteStubDelegate);

  SingleOpInterpreterBuilder model(kTfLiteBuiltinDepthwiseConv2d,
                                   /*version=*/1);
  model.AddInput(kTfLiteFloat32, {1, 1, 1, 2});  // input data
  std::vector<float> weights_data = {1.0f, 2.0f, 3.0f, 4.0f};
  const uint8_t* p = reinterpret_cast<const uint8_t*>(weights_data.data());
  std::vector<uint8_t> weights_bytes(p,
                                     p + weights_data.size() * sizeof(float));
  model.AddConstInput(kTfLiteFloat32, {1, 1, 1, 4}, weights_bytes);
  model.AddOutput(kTfLiteFloat32, {1, 1, 1, 4});  // output

  TfLiteDepthwiseConvParams* params =
      reinterpret_cast<TfLiteDepthwiseConvParams*>(
          calloc(1, sizeof(TfLiteDepthwiseConvParams)));
  params->depth_multiplier = 2;
  params->padding = kTfLitePaddingValid;
  params->stride_height = 1;
  params->stride_width = 1;
  params->activation = kTfLiteActNone;
  model.SetParameters(params);

  std::unique_ptr<::tflite::Interpreter> interpreter = model.Build();
  ASSERT_TRUE(interpreter);
  ASSERT_EQ(interpreter->ModifyGraphWithDelegate(delegate.get()), kTfLiteOk);

  const ::ml_drift::ir::IrModel* ir_model = GetIrModel(delegate.get());
  ASSERT_TRUE(ir_model);
  ASSERT_EQ(ir_model->ops().size(), 1);

  const ::ml_drift::ir::IrOp* dw_conv_op = ir_model->op(0);
  const auto* attr =
      std::any_cast<::ml_drift::DepthwiseConvolution2DAttributes>(
          &dw_conv_op->attr);
  ASSERT_TRUE(attr);

  const auto& weights = std::get<
      ::ml_drift::Tensor<::ml_drift::OHWI, ::ml_drift::DataType::FLOAT32>>(
      attr->weights);
  EXPECT_FALSE(weights.data.empty());

  std::vector<float> expected_weights = {1.0f, 3.0f, 2.0f, 4.0f};
  for (int i = 0; i < 4; ++i) {
    EXPECT_EQ(weights.data[i], expected_weights[i]);
  }
}

}  // namespace
}  // namespace litert::ml_drift::ir
