// Copyright 2025 Google LLC.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#include <any>
#include <cstdint>
#include <cstdlib>
#include <cstring>
#include <memory>
#include <variant>
#include <vector>

#include "testing/base/public/gunit.h"
#include "ml_drift/common/ir_model.h"  // from @ml_drift
#include "ml_drift/common/operations.h"  // from @ml_drift
#include "ml_drift/common/shape.h"  // from @ml_drift
#include "ml_drift/common/tensor.h"  // from @ml_drift
#include "ml_drift_delegate/tflite/convert/convert_testing_utils.h"
#include "ml_drift_delegate/tflite/convert/stub_delegate.h"
#include "tflite/builtin_ops.h"
#include "tflite/c/builtin_op_data.h"
#include "tflite/c/c_api.h"
#include "tflite/c/common.h"
#include "tflite/interpreter.h"

namespace litert::ml_drift::ir {
namespace {

class ConvertConcatTest : public ::testing::TestWithParam<TfLiteType> {
 protected:
  void SetUp() override {
    delegate_ = CreateStubDelegate();
    ASSERT_TRUE(delegate_);
  }

  void TearDown() override { DeleteStubDelegate(delegate_); }

  TfLiteDelegate* delegate_;
};

TEST_P(ConvertConcatTest, ConcatAlongBatch) {
  // Generate a model with a concat op.
  SingleOpInterpreterBuilder model(kTfLiteBuiltinConcatenation,
                                   /*version=*/1);
  model.AddInput(GetParam(), {1, 2, 3, 4});  // input data
  model.AddInput(GetParam(), {1, 2, 3, 4});  // input data
  model.AddOutput(GetParam(), {2, 2, 3, 4});
  TfLiteConcatenationParams* params =
      reinterpret_cast<TfLiteConcatenationParams*>(
          calloc(1, sizeof(TfLiteConcatenationParams)));
  model.SetParameters(params);

  // Build the interpreter and delegate it.
  std::unique_ptr<::tflite::Interpreter> interpreter = model.Build();
  ASSERT_TRUE(interpreter);
  ASSERT_EQ(interpreter->ModifyGraphWithDelegate(delegate_), kTfLiteOk);

  // Inspect the IrModel generated by the delegate.
  const ::ml_drift::ir::IrModel* ir_model = GetIrModel(delegate_);
  ASSERT_TRUE(ir_model);
  EXPECT_EQ(ir_model->inputs().size(), 2);
  EXPECT_EQ(ir_model->outputs().size(), 1);
  ASSERT_EQ(ir_model->ops().size(), 1);
  const ::ml_drift::ir::IrOp* concat_op = ir_model->op(0);
  EXPECT_EQ(concat_op->inputs.size(), 2);
  EXPECT_EQ(concat_op->outputs.size(), 1);
  EXPECT_EQ(concat_op->name, "concat");
  const ::ml_drift::ConcatAttributes* attr =
      std::any_cast<::ml_drift::ConcatAttributes>(&concat_op->attr);
  ASSERT_TRUE(attr);
  EXPECT_EQ(attr->axis, ::ml_drift::Axis::BATCH);

  // Sanity check inference.
  ASSERT_EQ(interpreter->AllocateTensors(), kTfLiteOk);
  ASSERT_EQ(interpreter->Invoke(), kTfLiteOk);
}

TEST_P(ConvertConcatTest, ConcatAlongHeight) {
  // Generate a model with a concat op.
  SingleOpInterpreterBuilder model(kTfLiteBuiltinConcatenation,
                                   /*version=*/1);
  model.AddInput(GetParam(), {1, 2, 3, 4});  // input data
  model.AddInput(GetParam(), {1, 2, 3, 4});  // input data
  model.AddOutput(GetParam(), {1, 4, 3, 4});
  TfLiteConcatenationParams* params =
      reinterpret_cast<TfLiteConcatenationParams*>(
          calloc(1, sizeof(TfLiteConcatenationParams)));
  model.SetParameters(params);

  // Build the interpreter and delegate it.
  std::unique_ptr<::tflite::Interpreter> interpreter = model.Build();
  ASSERT_TRUE(interpreter);
  ASSERT_EQ(interpreter->ModifyGraphWithDelegate(delegate_), kTfLiteOk);

  // Inspect the IrModel generated by the delegate.
  const ::ml_drift::ir::IrModel* ir_model = GetIrModel(delegate_);
  ASSERT_TRUE(ir_model);
  EXPECT_EQ(ir_model->inputs().size(), 2);
  EXPECT_EQ(ir_model->outputs().size(), 1);
  ASSERT_EQ(ir_model->ops().size(), 1);
  const ::ml_drift::ir::IrOp* concat_op = ir_model->op(0);
  EXPECT_EQ(concat_op->inputs.size(), 2);
  EXPECT_EQ(concat_op->outputs.size(), 1);
  EXPECT_EQ(concat_op->name, "concat");
  const ::ml_drift::ConcatAttributes* attr =
      std::any_cast<::ml_drift::ConcatAttributes>(&concat_op->attr);
  ASSERT_TRUE(attr);
  EXPECT_EQ(attr->axis, ::ml_drift::Axis::HEIGHT);

  // Sanity check inference.
  ASSERT_EQ(interpreter->AllocateTensors(), kTfLiteOk);
  ASSERT_EQ(interpreter->Invoke(), kTfLiteOk);
}

TEST_P(ConvertConcatTest, ConcatAlongWidth) {
  // Generate a model with a concat op.
  SingleOpInterpreterBuilder model(kTfLiteBuiltinConcatenation,
                                   /*version=*/1);
  model.AddInput(GetParam(), {1, 2, 3, 4});  // input data
  model.AddInput(GetParam(), {1, 2, 3, 4});  // input data
  model.AddOutput(GetParam(), {1, 2, 6, 4});
  TfLiteConcatenationParams* params =
      reinterpret_cast<TfLiteConcatenationParams*>(
          calloc(1, sizeof(TfLiteConcatenationParams)));
  model.SetParameters(params);

  // Build the interpreter and delegate it.
  std::unique_ptr<::tflite::Interpreter> interpreter = model.Build();
  ASSERT_TRUE(interpreter);
  ASSERT_EQ(interpreter->ModifyGraphWithDelegate(delegate_), kTfLiteOk);

  // Inspect the IrModel generated by the delegate.
  const ::ml_drift::ir::IrModel* ir_model = GetIrModel(delegate_);
  ASSERT_TRUE(ir_model);
  EXPECT_EQ(ir_model->inputs().size(), 2);
  EXPECT_EQ(ir_model->outputs().size(), 1);
  ASSERT_EQ(ir_model->ops().size(), 1);
  const ::ml_drift::ir::IrOp* concat_op = ir_model->op(0);
  EXPECT_EQ(concat_op->inputs.size(), 2);
  EXPECT_EQ(concat_op->outputs.size(), 1);
  EXPECT_EQ(concat_op->name, "concat");
  const ::ml_drift::ConcatAttributes* attr =
      std::any_cast<::ml_drift::ConcatAttributes>(&concat_op->attr);
  ASSERT_TRUE(attr);
  EXPECT_EQ(attr->axis, ::ml_drift::Axis::WIDTH);

  // Sanity check inference.
  ASSERT_EQ(interpreter->AllocateTensors(), kTfLiteOk);
  ASSERT_EQ(interpreter->Invoke(), kTfLiteOk);
}

TEST_P(ConvertConcatTest, ConcatAlongDepth) {
  // Generate a model with a concat op.
  SingleOpInterpreterBuilder model(kTfLiteBuiltinConcatenation,
                                   /*version=*/1);
  model.AddInput(GetParam(), {1, 2, 3, 4, 5});  // input data
  model.AddInput(GetParam(), {1, 2, 3, 4, 5});  // input data
  model.AddOutput(GetParam(), {1, 2, 3, 8, 5});
  TfLiteConcatenationParams* params =
      reinterpret_cast<TfLiteConcatenationParams*>(
          calloc(1, sizeof(TfLiteConcatenationParams)));
  model.SetParameters(params);

  // Build the interpreter and delegate it.
  std::unique_ptr<::tflite::Interpreter> interpreter = model.Build();
  ASSERT_TRUE(interpreter);
  ASSERT_EQ(interpreter->ModifyGraphWithDelegate(delegate_), kTfLiteOk);

  // Inspect the IrModel generated by the delegate.
  const ::ml_drift::ir::IrModel* ir_model = GetIrModel(delegate_);
  ASSERT_TRUE(ir_model);
  EXPECT_EQ(ir_model->inputs().size(), 2);
  EXPECT_EQ(ir_model->outputs().size(), 1);
  ASSERT_EQ(ir_model->ops().size(), 1);
  const ::ml_drift::ir::IrOp* concat_op = ir_model->op(0);
  EXPECT_EQ(concat_op->inputs.size(), 2);
  EXPECT_EQ(concat_op->outputs.size(), 1);
  EXPECT_EQ(concat_op->name, "concat");
  const ::ml_drift::ConcatAttributes* attr =
      std::any_cast<::ml_drift::ConcatAttributes>(&concat_op->attr);
  ASSERT_TRUE(attr);
  EXPECT_EQ(attr->axis, ::ml_drift::Axis::DEPTH);

  // Sanity check inference.
  ASSERT_EQ(interpreter->AllocateTensors(), kTfLiteOk);
  ASSERT_EQ(interpreter->Invoke(), kTfLiteOk);
}

TEST_P(ConvertConcatTest, ConcatAlongChannel) {
  // Generate a model with a concat op.
  SingleOpInterpreterBuilder model(kTfLiteBuiltinConcatenation,
                                   /*version=*/1);
  model.AddInput(GetParam(), {1, 2, 3, 4});  // input data
  model.AddInput(GetParam(), {1, 2, 3, 4});  // input data
  model.AddOutput(GetParam(), {1, 2, 3, 8});
  TfLiteConcatenationParams* params =
      reinterpret_cast<TfLiteConcatenationParams*>(
          calloc(1, sizeof(TfLiteConcatenationParams)));
  model.SetParameters(params);

  // Build the interpreter and delegate it.
  std::unique_ptr<::tflite::Interpreter> interpreter = model.Build();
  ASSERT_TRUE(interpreter);
  ASSERT_EQ(interpreter->ModifyGraphWithDelegate(delegate_), kTfLiteOk);

  // Inspect the IrModel generated by the delegate.
  const ::ml_drift::ir::IrModel* ir_model = GetIrModel(delegate_);
  ASSERT_TRUE(ir_model);
  EXPECT_EQ(ir_model->inputs().size(), 2);
  EXPECT_EQ(ir_model->outputs().size(), 1);
  ASSERT_EQ(ir_model->ops().size(), 1);
  const ::ml_drift::ir::IrOp* concat_op = ir_model->op(0);
  EXPECT_EQ(concat_op->inputs.size(), 2);
  EXPECT_EQ(concat_op->outputs.size(), 1);
  EXPECT_EQ(concat_op->name, "concat");
  const ::ml_drift::ConcatAttributes* attr =
      std::any_cast<::ml_drift::ConcatAttributes>(&concat_op->attr);
  ASSERT_TRUE(attr);
  EXPECT_EQ(attr->axis, ::ml_drift::Axis::CHANNELS);

  // Sanity check inference.
  ASSERT_EQ(interpreter->AllocateTensors(), kTfLiteOk);
  ASSERT_EQ(interpreter->Invoke(), kTfLiteOk);
}

TEST_P(ConvertConcatTest, ConcatThreeInputs) {
  // Generate a model with a concat op.
  SingleOpInterpreterBuilder model(kTfLiteBuiltinConcatenation,
                                   /*version=*/1);
  model.AddInput(GetParam(), {1, 2, 3, 4});  // input data
  model.AddInput(GetParam(), {1, 2, 3, 4});  // input data
  model.AddInput(GetParam(), {1, 2, 3, 4});  // input data
  model.AddOutput(GetParam(), {1, 2, 3, 12});
  TfLiteConcatenationParams* params =
      reinterpret_cast<TfLiteConcatenationParams*>(
          calloc(1, sizeof(TfLiteConcatenationParams)));
  model.SetParameters(params);

  // Build the interpreter and delegate it.
  std::unique_ptr<::tflite::Interpreter> interpreter = model.Build();
  ASSERT_TRUE(interpreter);
  ASSERT_EQ(interpreter->ModifyGraphWithDelegate(delegate_), kTfLiteOk);

  // Inspect the IrModel generated by the delegate.
  const ::ml_drift::ir::IrModel* ir_model = GetIrModel(delegate_);
  ASSERT_TRUE(ir_model);
  EXPECT_EQ(ir_model->inputs().size(), 3);
  EXPECT_EQ(ir_model->outputs().size(), 1);
  ASSERT_EQ(ir_model->ops().size(), 1);
  const ::ml_drift::ir::IrOp* concat_op = ir_model->op(0);
  EXPECT_EQ(concat_op->inputs.size(), 3);
  EXPECT_EQ(concat_op->outputs.size(), 1);
  EXPECT_EQ(concat_op->name, "concat");
  const ::ml_drift::ConcatAttributes* attr =
      std::any_cast<::ml_drift::ConcatAttributes>(&concat_op->attr);
  ASSERT_TRUE(attr);
  EXPECT_EQ(attr->axis, ::ml_drift::Axis::CHANNELS);

  // Sanity check inference.
  ASSERT_EQ(interpreter->AllocateTensors(), kTfLiteOk);
  ASSERT_EQ(interpreter->Invoke(), kTfLiteOk);
}

TEST_P(ConvertConcatTest, ConcatWithDuplicatedInput) {
  // Generate a model with a concat op.
  SingleOpInterpreterBuilder model(kTfLiteBuiltinConcatenation,
                                   /*version=*/1);
  model.AddInput(GetParam(), {1, 2, 3, 2});  // input 0
  model.AddInput(GetParam(), {1, 2, 3, 3});  // input 1
  // Input 0 is duplicated: 2 + 3 + 2 = 7
  model.AddOutput(GetParam(), {1, 2, 3, 7});
  TfLiteConcatenationParams* params =
      reinterpret_cast<TfLiteConcatenationParams*>(
          calloc(1, sizeof(TfLiteConcatenationParams)));
  model.SetParameters(params);

  // Build the interpreter and delegate it.
  // Note that we are passing input 0 twice, which will trigger the copy logic.
  std::unique_ptr<::tflite::Interpreter> interpreter = model.Build({0, 1, 0});
  ASSERT_TRUE(interpreter);
  ASSERT_EQ(interpreter->ModifyGraphWithDelegate(delegate_), kTfLiteOk);

  // Inspect the IrModel generated by the delegate.
  const ::ml_drift::ir::IrModel* ir_model = GetIrModel(delegate_);
  ASSERT_TRUE(ir_model);
  EXPECT_EQ(ir_model->inputs().size(), 2);
  EXPECT_EQ(ir_model->outputs().size(), 1);
  EXPECT_EQ(ir_model->ops().size(), 2);
  // concat op gets created first
  EXPECT_EQ(ir_model->op(0)->name, "concat");
  EXPECT_EQ(ir_model->op(1)->name, "copy");
  // Only two inputs to model, but we have three inputs to concat op
  EXPECT_EQ(ir_model->op(0)->inputs.size(), 3);
  // Also note that the 0 tensor will have two consumers
  EXPECT_EQ(ir_model->tensors().at(0)->consumers.size(), 2);

  // Sanity check inference.
  ASSERT_EQ(interpreter->AllocateTensors(), kTfLiteOk);
  ASSERT_EQ(interpreter->Invoke(), kTfLiteOk);
}

TEST_P(ConvertConcatTest, ConcatAlongChannelWithActivation) {
  // Generate a model with a concat op.
  SingleOpInterpreterBuilder model(kTfLiteBuiltinConcatenation,
                                   /*version=*/1);
  model.AddInput(GetParam(), {1, 2, 3, 4});  // input data
  model.AddInput(GetParam(), {1, 2, 3, 4});  // input data
  model.AddOutput(GetParam(), {1, 2, 3, 8});
  TfLiteConcatenationParams* params =
      reinterpret_cast<TfLiteConcatenationParams*>(
          calloc(1, sizeof(TfLiteConcatenationParams)));
  params->activation = kTfLiteActRelu;
  model.SetParameters(params);

  // Build the interpreter and delegate it.
  std::unique_ptr<::tflite::Interpreter> interpreter = model.Build();
  ASSERT_TRUE(interpreter);
  ASSERT_EQ(interpreter->ModifyGraphWithDelegate(delegate_), kTfLiteOk);

  // Inspect the IrModel generated by the delegate.
  const ::ml_drift::ir::IrModel* ir_model = GetIrModel(delegate_);
  ASSERT_TRUE(ir_model);
  EXPECT_EQ(ir_model->inputs().size(), 2);
  EXPECT_EQ(ir_model->outputs().size(), 1);
  ASSERT_EQ(ir_model->ops().size(), 2);
  const ::ml_drift::ir::IrOp* concat_op = ir_model->op(0);
  EXPECT_EQ(concat_op->inputs.size(), 2);
  EXPECT_EQ(concat_op->outputs.size(), 1);
  EXPECT_EQ(concat_op->name, "concat");
  const ::ml_drift::ConcatAttributes* attr =
      std::any_cast<::ml_drift::ConcatAttributes>(&concat_op->attr);
  ASSERT_TRUE(attr);
  EXPECT_EQ(attr->axis, ::ml_drift::Axis::CHANNELS);

  const ::ml_drift::ir::IrOp* relu_op = ir_model->op(1);
  EXPECT_EQ(relu_op->name, "relu");
  EXPECT_EQ(relu_op->inputs.size(), 1);
  EXPECT_EQ(relu_op->outputs.size(), 1);
  EXPECT_EQ(relu_op->inputs[0], concat_op->outputs[0]);

  // Sanity check inference.
  ASSERT_EQ(interpreter->AllocateTensors(), kTfLiteOk);
  ASSERT_EQ(interpreter->Invoke(), kTfLiteOk);
}

TEST_P(ConvertConcatTest, ConcatWithConstantInput) {
  if (GetParam() != kTfLiteFloat32) {
    GTEST_SKIP() << "Skipping constant input test for non-float32 types for "
                    "simplicity of data generation.";
  }
  // Generate a model with a concat op.
  SingleOpInterpreterBuilder model(kTfLiteBuiltinConcatenation,
                                   /*version=*/1);
  model.AddInput(GetParam(), {1, 2, 3, 4});  // input 0
  std::vector<float> const_data = {1.0f,  2.0f,  3.0f,  4.0f,  5.0f,  6.0f,
                                   7.0f,  8.0f,  9.0f,  10.0f, 11.0f, 12.0f,
                                   13.0f, 14.0f, 15.0f, 16.0f, 17.0f, 18.0f,
                                   19.0f, 20.0f, 21.0f, 22.0f, 23.0f, 24.0f};
  std::vector<uint8_t> const_data_bytes(const_data.size() * sizeof(float));
  std::memcpy(const_data_bytes.data(), const_data.data(),
              const_data_bytes.size());

  model.AddConstInput(GetParam(), {1, 2, 3, 4}, const_data_bytes);  // input 1
  model.AddOutput(GetParam(), {1, 2, 3, 8});
  TfLiteConcatenationParams* params =
      reinterpret_cast<TfLiteConcatenationParams*>(
          calloc(1, sizeof(TfLiteConcatenationParams)));
  model.SetParameters(params);

  // Build the interpreter and delegate it.
  std::unique_ptr<::tflite::Interpreter> interpreter = model.Build();
  ASSERT_TRUE(interpreter);
  ASSERT_EQ(interpreter->ModifyGraphWithDelegate(delegate_), kTfLiteOk);

  // Inspect the IrModel generated by the delegate.
  const ::ml_drift::ir::IrModel* ir_model = GetIrModel(delegate_);
  ASSERT_TRUE(ir_model);
  // Constant input shouldn't be in model inputs.
  EXPECT_EQ(ir_model->inputs().size(), 1);
  EXPECT_EQ(ir_model->outputs().size(), 1);
  // We expect 2 ops: 1 for CONSTANT and 1 for CONCAT.
  ASSERT_EQ(ir_model->ops().size(), 2);
  // Constant op is added first during input parsing, then concat op.
  EXPECT_EQ(ir_model->op(0)->name, "const");
  EXPECT_EQ(ir_model->op(1)->name, "concat");

  const ::ml_drift::ir::IrOp* concat_op = ir_model->op(1);
  EXPECT_EQ(concat_op->inputs.size(), 2);
  EXPECT_EQ(concat_op->outputs.size(), 1);

  // Verify constant data.
  const ::ml_drift::ir::IrOp* const_op = ir_model->op(0);
  const ::ml_drift::ConstTensorAttributes* attr =
      std::any_cast<::ml_drift::ConstTensorAttributes>(&const_op->attr);
  ASSERT_TRUE(attr);
  const auto* t = std::get_if<::ml_drift::TensorFloat32>(&attr->tensor);
  ASSERT_TRUE(t);
  for (int i = 0; i < const_data.size(); ++i) {
    EXPECT_EQ(t->data[i], const_data[i]);
  }

  // Sanity check inference.
  ASSERT_EQ(interpreter->AllocateTensors(), kTfLiteOk);
  ASSERT_EQ(interpreter->Invoke(), kTfLiteOk);
}

TEST_P(ConvertConcatTest, ConcatWithConstantZerosInputToPad) {
  if (GetParam() != kTfLiteFloat32) {
    GTEST_SKIP() << "Skipping constant input test for non-float32 types for "
                    "simplicity of data generation.";
  }
  // Generate a model with a concat op.
  SingleOpInterpreterBuilder model(kTfLiteBuiltinConcatenation,
                                   /*version=*/1);
  model.AddInput(GetParam(), {1, 2, 3, 4});  // input 0
  std::vector<float> const_data = {
      0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f,
      0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f, 0.0f};
  std::vector<uint8_t> const_data_bytes(const_data.size() * sizeof(float));
  std::memcpy(const_data_bytes.data(), const_data.data(),
              const_data_bytes.size());

  model.AddConstInput(GetParam(), {1, 2, 3, 4}, const_data_bytes);  // input 1
  model.AddOutput(GetParam(), {1, 2, 3, 8});
  TfLiteConcatenationParams* params =
      reinterpret_cast<TfLiteConcatenationParams*>(
          calloc(1, sizeof(TfLiteConcatenationParams)));
  model.SetParameters(params);

  // Build the interpreter and delegate it.
  std::unique_ptr<::tflite::Interpreter> interpreter = model.Build();
  ASSERT_TRUE(interpreter);
  ASSERT_EQ(interpreter->ModifyGraphWithDelegate(delegate_), kTfLiteOk);

  // Inspect the IrModel generated by the delegate.
  const ::ml_drift::ir::IrModel* ir_model = GetIrModel(delegate_);
  ASSERT_TRUE(ir_model);
  // Constant input shouldn't be in model inputs.
  EXPECT_EQ(ir_model->inputs().size(), 1);
  EXPECT_EQ(ir_model->outputs().size(), 1);
  // We expect 1 op: PAD.
  ASSERT_EQ(ir_model->ops().size(), 1);
  EXPECT_EQ(ir_model->op(0)->name, "pad");

  const ::ml_drift::ir::IrOp* pad_op = ir_model->op(0);
  EXPECT_EQ(pad_op->inputs.size(), 1);
  EXPECT_EQ(pad_op->outputs.size(), 1);

  const ::ml_drift::PadAttributes* attr =
      std::any_cast<::ml_drift::PadAttributes>(&pad_op->attr);
  ASSERT_TRUE(attr);
  EXPECT_EQ(attr->type, ::ml_drift::PaddingContentType::ZEROS);
  EXPECT_EQ(attr->appended.c, 4);

  // Sanity check inference.
  ASSERT_EQ(interpreter->AllocateTensors(), kTfLiteOk);
  ASSERT_EQ(interpreter->Invoke(), kTfLiteOk);
}

INSTANTIATE_TEST_SUITE_P(ConvertConcatTest, ConvertConcatTest,
                         ::testing::Values(  // clang-format off
      // go/keep-sorted start numeric=yes
      kTfLiteBool,
      kTfLiteFloat16,
      kTfLiteFloat32,
      kTfLiteInt8,
      kTfLiteInt16,
      kTfLiteInt32,
      kTfLiteUInt8,
      kTfLiteUInt16,
      kTfLiteUInt32
      // go/keep-sorted end
                                             // clang-format on
                             ));

}  // namespace
}  // namespace litert::ml_drift::ir
