// Copyright 2026 Google LLC.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#include <any>
#include <cstdint>
#include <cstdlib>
#include <cstring>
#include <memory>
#include <vector>

#include "testing/base/public/gunit.h"
#include "ml_drift/common/ir_model.h"  // from @ml_drift
#include "ml_drift/common/operations.h"  // from @ml_drift
#include "ml_drift/common/shape.h"  // from @ml_drift
#include "ml_drift_delegate/tflite/convert/convert_testing_utils.h"
#include "ml_drift_delegate/tflite/convert/stub_delegate.h"
#include "tflite/builtin_ops.h"
#include "tflite/c/builtin_op_data.h"
#include "tflite/c/c_api.h"
#include "tflite/c/common.h"
#include "tflite/interpreter.h"

namespace litert::ml_drift::ir {
namespace {

class ConvertStridedSliceTest : public ::testing::TestWithParam<TfLiteType> {
 protected:
  void SetUp() override {
    // Verify the raw per-op conversion; model-level transforms (which would
    // fold away this no-op full-tensor slice) have their own dedicated tests.
    delegate_ = std::unique_ptr<TfLiteDelegate, void (*)(TfLiteDelegate*)>(
        CreateStubDelegate({.apply_model_transformations = false}),
        DeleteStubDelegate);
    ASSERT_TRUE(delegate_);
  }

  std::unique_ptr<TfLiteDelegate, void (*)(TfLiteDelegate*)> delegate_ = {
      nullptr, [](TfLiteDelegate*) {}};
};

std::vector<uint8_t> ToBytes(const std::vector<int32_t>& data) {
  std::vector<uint8_t> bytes(data.size() * sizeof(int32_t));
  std::memcpy(bytes.data(), data.data(), bytes.size());
  return bytes;
}

TEST_P(ConvertStridedSliceTest, Slice4D) {
  std::vector<int32_t> begins_data = {0, 1, 1, 0};
  std::vector<int32_t> ends_data = {1, 3, 3, 3};
  std::vector<int32_t> strides_data = {1, 1, 1, 1};

  std::vector<uint8_t> begins_bytes = ToBytes(begins_data);
  std::vector<uint8_t> ends_bytes = ToBytes(ends_data);
  std::vector<uint8_t> strides_bytes = ToBytes(strides_data);

  // Generate a model with a strided slice op.
  SingleOpInterpreterBuilder model(kTfLiteBuiltinStridedSlice, /*version=*/1);
  model.AddInput(GetParam(), {1, 4, 4, 3});  // input data
  model.AddConstInput(kTfLiteInt32, {4}, begins_bytes);
  model.AddConstInput(kTfLiteInt32, {4}, ends_bytes);
  model.AddConstInput(kTfLiteInt32, {4}, strides_bytes);
  model.AddOutput(GetParam(), {1, 2, 2, 3});

  TfLiteStridedSliceParams* params =
      reinterpret_cast<TfLiteStridedSliceParams*>(
          calloc(1, sizeof(TfLiteStridedSliceParams)));
  params->begin_mask = 0;
  params->end_mask = 0;
  params->ellipsis_mask = 0;
  params->new_axis_mask = 0;
  params->shrink_axis_mask = 0;
  model.SetParameters(params);

  // Build the interpreter and delegate it.
  std::unique_ptr<::tflite::Interpreter> interpreter = model.Build();
  ASSERT_TRUE(interpreter);

  ASSERT_EQ(interpreter->ModifyGraphWithDelegate(delegate_.get()), kTfLiteOk);

  // Inspect the IrModel generated by the delegate.
  const ::ml_drift::ir::IrModel* ir_model = GetIrModel(delegate_.get());
  ASSERT_TRUE(ir_model);
  EXPECT_EQ(ir_model->inputs().size(), 1);
  EXPECT_EQ(ir_model->outputs().size(), 1);
  ASSERT_EQ(ir_model->ops().size(), 1);
  const ::ml_drift::ir::IrOp* slice_op = ir_model->op(ir_model->ops()[0]->id);
  EXPECT_EQ(slice_op->inputs.size(), 1);
  EXPECT_EQ(slice_op->outputs.size(), 1);
  EXPECT_EQ(slice_op->name, "slice");
  const ::ml_drift::SliceAttributes* attr =
      std::any_cast<::ml_drift::SliceAttributes>(&slice_op->attr);
  ASSERT_TRUE(attr);
  EXPECT_EQ(attr->starts, ::ml_drift::BHWC(0, 1, 1, 0));
  EXPECT_EQ(attr->ends, ::ml_drift::BHWC(1, 3, 3, 3));
  EXPECT_EQ(attr->strides, ::ml_drift::BHWC(1, 1, 1, 1));

  // Sanity check inference.
  ASSERT_EQ(interpreter->AllocateTensors(), kTfLiteOk);
  ASSERT_EQ(interpreter->Invoke(), kTfLiteOk);
}

TEST_P(ConvertStridedSliceTest, Slice3D) {
  std::vector<int32_t> begins_data = {1, 1, 0};
  std::vector<int32_t> ends_data = {3, 3, 3};
  std::vector<int32_t> strides_data = {1, 1, 1};

  std::vector<uint8_t> begins_bytes = ToBytes(begins_data);
  std::vector<uint8_t> ends_bytes = ToBytes(ends_data);
  std::vector<uint8_t> strides_bytes = ToBytes(strides_data);

  SingleOpInterpreterBuilder model(kTfLiteBuiltinStridedSlice, /*version=*/1);
  model.AddInput(GetParam(), {4, 4, 3});
  model.AddConstInput(kTfLiteInt32, {3}, begins_bytes);
  model.AddConstInput(kTfLiteInt32, {3}, ends_bytes);
  model.AddConstInput(kTfLiteInt32, {3}, strides_bytes);
  model.AddOutput(GetParam(), {2, 2, 3});

  TfLiteStridedSliceParams* params =
      reinterpret_cast<TfLiteStridedSliceParams*>(
          calloc(1, sizeof(TfLiteStridedSliceParams)));
  params->begin_mask = 0;
  params->end_mask = 0;
  params->ellipsis_mask = 0;
  params->new_axis_mask = 0;
  params->shrink_axis_mask = 0;
  model.SetParameters(params);

  std::unique_ptr<::tflite::Interpreter> interpreter = model.Build();
  ASSERT_TRUE(interpreter);

  ASSERT_EQ(interpreter->ModifyGraphWithDelegate(delegate_.get()), kTfLiteOk);

  const ::ml_drift::ir::IrModel* ir_model = GetIrModel(delegate_.get());
  ASSERT_TRUE(ir_model);
  EXPECT_EQ(ir_model->ops().size(), 1);
  const ::ml_drift::ir::IrOp* slice_op = ir_model->op(ir_model->ops()[0]->id);
  const ::ml_drift::SliceAttributes* attr =
      std::any_cast<::ml_drift::SliceAttributes>(&slice_op->attr);
  ASSERT_TRUE(attr);

  EXPECT_EQ(attr->starts, ::ml_drift::BHWC(1, 0, 1, 0));
  EXPECT_EQ(attr->ends, ::ml_drift::BHWC(3, 1, 3, 3));
  EXPECT_EQ(attr->strides, ::ml_drift::BHWC(1, 1, 1, 1));
}

TEST_P(ConvertStridedSliceTest, Slice2D) {
  std::vector<int32_t> begins_data = {1, 1};
  std::vector<int32_t> ends_data = {3, 3};
  std::vector<int32_t> strides_data = {1, 1};

  std::vector<uint8_t> begins_bytes = ToBytes(begins_data);
  std::vector<uint8_t> ends_bytes = ToBytes(ends_data);
  std::vector<uint8_t> strides_bytes = ToBytes(strides_data);

  SingleOpInterpreterBuilder model(kTfLiteBuiltinStridedSlice, /*version=*/1);
  model.AddInput(GetParam(), {4, 4});
  model.AddConstInput(kTfLiteInt32, {2}, begins_bytes);
  model.AddConstInput(kTfLiteInt32, {2}, ends_bytes);
  model.AddConstInput(kTfLiteInt32, {2}, strides_bytes);
  model.AddOutput(GetParam(), {2, 2});

  TfLiteStridedSliceParams* params =
      reinterpret_cast<TfLiteStridedSliceParams*>(
          calloc(1, sizeof(TfLiteStridedSliceParams)));
  params->begin_mask = 0;
  params->end_mask = 0;
  params->ellipsis_mask = 0;
  params->new_axis_mask = 0;
  params->shrink_axis_mask = 0;
  model.SetParameters(params);

  std::unique_ptr<::tflite::Interpreter> interpreter = model.Build();
  ASSERT_TRUE(interpreter);

  ASSERT_EQ(interpreter->ModifyGraphWithDelegate(delegate_.get()), kTfLiteOk);

  const ::ml_drift::ir::IrModel* ir_model = GetIrModel(delegate_.get());
  ASSERT_TRUE(ir_model);
  EXPECT_EQ(ir_model->ops().size(), 1);
  const ::ml_drift::ir::IrOp* slice_op = ir_model->op(ir_model->ops()[0]->id);
  const ::ml_drift::SliceAttributes* attr =
      std::any_cast<::ml_drift::SliceAttributes>(&slice_op->attr);
  ASSERT_TRUE(attr);

  EXPECT_EQ(attr->starts, ::ml_drift::BHWC(1, 0, 0, 1));
  EXPECT_EQ(attr->ends, ::ml_drift::BHWC(3, 1, 1, 3));
  EXPECT_EQ(attr->strides, ::ml_drift::BHWC(1, 1, 1, 1));
}

TEST_P(ConvertStridedSliceTest, Slice1D) {
  std::vector<int32_t> begins_data = {1};
  std::vector<int32_t> ends_data = {3};
  std::vector<int32_t> strides_data = {1};

  std::vector<uint8_t> begins_bytes = ToBytes(begins_data);
  std::vector<uint8_t> ends_bytes = ToBytes(ends_data);
  std::vector<uint8_t> strides_bytes = ToBytes(strides_data);

  SingleOpInterpreterBuilder model(kTfLiteBuiltinStridedSlice, /*version=*/1);
  model.AddInput(GetParam(), {4});
  model.AddConstInput(kTfLiteInt32, {1}, begins_bytes);
  model.AddConstInput(kTfLiteInt32, {1}, ends_bytes);
  model.AddConstInput(kTfLiteInt32, {1}, strides_bytes);
  model.AddOutput(GetParam(), {2});

  TfLiteStridedSliceParams* params =
      reinterpret_cast<TfLiteStridedSliceParams*>(
          calloc(1, sizeof(TfLiteStridedSliceParams)));
  params->begin_mask = 0;
  params->end_mask = 0;
  params->ellipsis_mask = 0;
  params->new_axis_mask = 0;
  params->shrink_axis_mask = 0;
  model.SetParameters(params);

  std::unique_ptr<::tflite::Interpreter> interpreter = model.Build();
  ASSERT_TRUE(interpreter);

  ASSERT_EQ(interpreter->ModifyGraphWithDelegate(delegate_.get()), kTfLiteOk);

  const ::ml_drift::ir::IrModel* ir_model = GetIrModel(delegate_.get());
  ASSERT_TRUE(ir_model);
  EXPECT_EQ(ir_model->ops().size(), 1);
  const ::ml_drift::ir::IrOp* slice_op = ir_model->op(ir_model->ops()[0]->id);
  const ::ml_drift::SliceAttributes* attr =
      std::any_cast<::ml_drift::SliceAttributes>(&slice_op->attr);
  ASSERT_TRUE(attr);

  EXPECT_EQ(attr->starts, ::ml_drift::BHWC(1, 0, 0, 0));
  EXPECT_EQ(attr->ends, ::ml_drift::BHWC(3, 1, 1, 1));
  EXPECT_EQ(attr->strides, ::ml_drift::BHWC(1, 1, 1, 1));
}

TEST_P(ConvertStridedSliceTest, SliceImplicitBatch) {
  std::vector<int32_t> begins_data = {1, 1, 0};
  std::vector<int32_t> ends_data = {3, 3, 3};
  std::vector<int32_t> strides_data = {1, 1, 1};

  std::vector<uint8_t> begins_bytes = ToBytes(begins_data);
  std::vector<uint8_t> ends_bytes = ToBytes(ends_data);
  std::vector<uint8_t> strides_bytes = ToBytes(strides_data);

  SingleOpInterpreterBuilder model(kTfLiteBuiltinStridedSlice, /*version=*/1);
  model.AddInput(GetParam(), {2, 4, 4, 3});
  model.AddConstInput(kTfLiteInt32, {3}, begins_bytes);
  model.AddConstInput(kTfLiteInt32, {3}, ends_bytes);
  model.AddConstInput(kTfLiteInt32, {3}, strides_bytes);
  model.AddOutput(GetParam(), {2, 2, 2, 3});

  TfLiteStridedSliceParams* params =
      reinterpret_cast<TfLiteStridedSliceParams*>(
          calloc(1, sizeof(TfLiteStridedSliceParams)));
  params->begin_mask = 0;
  params->end_mask = 0;
  params->ellipsis_mask = 0;
  params->new_axis_mask = 0;
  params->shrink_axis_mask = 0;
  model.SetParameters(params);

  std::unique_ptr<::tflite::Interpreter> interpreter = model.Build();
  ASSERT_TRUE(interpreter);

  ASSERT_EQ(interpreter->ModifyGraphWithDelegate(delegate_.get()), kTfLiteOk);

  const ::ml_drift::ir::IrModel* ir_model = GetIrModel(delegate_.get());
  ASSERT_TRUE(ir_model);
  EXPECT_EQ(ir_model->ops().size(), 1);
  const ::ml_drift::ir::IrOp* slice_op = ir_model->op(ir_model->ops()[0]->id);
  const ::ml_drift::SliceAttributes* attr =
      std::any_cast<::ml_drift::SliceAttributes>(&slice_op->attr);
  ASSERT_TRUE(attr);

  EXPECT_EQ(attr->starts, ::ml_drift::BHWC(0, 1, 1, 0));
  EXPECT_EQ(attr->ends, ::ml_drift::BHWC(2, 3, 3, 3));
  EXPECT_EQ(attr->strides, ::ml_drift::BHWC(1, 1, 1, 1));
}

TEST_P(ConvertStridedSliceTest, SliceWithNegativeIndices) {
  std::vector<int32_t> begins_data = {0, -3, -3, 0};
  std::vector<int32_t> ends_data = {1, -1, -1, 3};
  std::vector<int32_t> strides_data = {1, 1, 1, 1};

  std::vector<uint8_t> begins_bytes = ToBytes(begins_data);
  std::vector<uint8_t> ends_bytes = ToBytes(ends_data);
  std::vector<uint8_t> strides_bytes = ToBytes(strides_data);

  // Generate a model with a strided slice op.
  SingleOpInterpreterBuilder model(kTfLiteBuiltinStridedSlice, /*version=*/1);
  model.AddInput(GetParam(), {1, 4, 4, 3});  // input data
  model.AddConstInput(kTfLiteInt32, {4}, begins_bytes);
  model.AddConstInput(kTfLiteInt32, {4}, ends_bytes);
  model.AddConstInput(kTfLiteInt32, {4}, strides_bytes);
  model.AddOutput(GetParam(), {1, 2, 2, 3});

  TfLiteStridedSliceParams* params =
      reinterpret_cast<TfLiteStridedSliceParams*>(
          calloc(1, sizeof(TfLiteStridedSliceParams)));
  params->begin_mask = 0;
  params->end_mask = 0;
  params->ellipsis_mask = 0;
  params->new_axis_mask = 0;
  params->shrink_axis_mask = 0;
  model.SetParameters(params);

  // Build the interpreter and delegate it.
  std::unique_ptr<::tflite::Interpreter> interpreter = model.Build();
  ASSERT_TRUE(interpreter);

  ASSERT_EQ(interpreter->ModifyGraphWithDelegate(delegate_.get()), kTfLiteOk);

  // Inspect the IrModel generated by the delegate.
  const ::ml_drift::ir::IrModel* ir_model = GetIrModel(delegate_.get());
  ASSERT_TRUE(ir_model);
  EXPECT_EQ(ir_model->inputs().size(), 1);
  EXPECT_EQ(ir_model->outputs().size(), 1);
  ASSERT_EQ(ir_model->ops().size(), 1);
  const ::ml_drift::ir::IrOp* slice_op = ir_model->op(ir_model->ops()[0]->id);
  EXPECT_EQ(slice_op->inputs.size(), 1);
  EXPECT_EQ(slice_op->outputs.size(), 1);
  EXPECT_EQ(slice_op->name, "slice");
  const ::ml_drift::SliceAttributes* attr =
      std::any_cast<::ml_drift::SliceAttributes>(&slice_op->attr);
  ASSERT_TRUE(attr);
  EXPECT_EQ(attr->starts, ::ml_drift::BHWC(0, 1, 1, 0));
  EXPECT_EQ(attr->ends, ::ml_drift::BHWC(1, 3, 3, 3));
  EXPECT_EQ(attr->strides, ::ml_drift::BHWC(1, 1, 1, 1));

  // Sanity check inference.
  ASSERT_EQ(interpreter->AllocateTensors(), kTfLiteOk);
  ASSERT_EQ(interpreter->Invoke(), kTfLiteOk);
}

TEST_P(ConvertStridedSliceTest, SliceWithMasks) {
  std::vector<int32_t> begins_data = {0, 0, 0, 0};
  std::vector<int32_t> ends_data = {0, 0, 0, 0};
  std::vector<int32_t> strides_data = {1, 1, 1, 1};

  std::vector<uint8_t> begins_bytes = ToBytes(begins_data);
  std::vector<uint8_t> ends_bytes = ToBytes(ends_data);
  std::vector<uint8_t> strides_bytes = ToBytes(strides_data);

  SingleOpInterpreterBuilder model(kTfLiteBuiltinStridedSlice, /*version=*/1);
  model.AddInput(GetParam(), {1, 4, 4, 3});  // input data
  model.AddConstInput(kTfLiteInt32, {4}, begins_bytes);
  model.AddConstInput(kTfLiteInt32, {4}, ends_bytes);
  model.AddConstInput(kTfLiteInt32, {4}, strides_bytes);
  model.AddOutput(GetParam(), {1, 4, 4, 3});

  TfLiteStridedSliceParams* params =
      reinterpret_cast<TfLiteStridedSliceParams*>(
          calloc(1, sizeof(TfLiteStridedSliceParams)));
  params->begin_mask = 15;  // Set first 4 bits
  params->end_mask = 15;
  params->ellipsis_mask = 0;
  params->new_axis_mask = 0;
  params->shrink_axis_mask = 0;
  model.SetParameters(params);

  std::unique_ptr<::tflite::Interpreter> interpreter = model.Build();
  ASSERT_TRUE(interpreter);

  ASSERT_EQ(interpreter->ModifyGraphWithDelegate(delegate_.get()), kTfLiteOk);

  const ::ml_drift::ir::IrModel* ir_model = GetIrModel(delegate_.get());
  ASSERT_TRUE(ir_model);
  EXPECT_EQ(ir_model->ops().size(), 1);
  const ::ml_drift::ir::IrOp* slice_op = ir_model->op(ir_model->ops()[0]->id);
  const ::ml_drift::SliceAttributes* attr =
      std::any_cast<::ml_drift::SliceAttributes>(&slice_op->attr);
  ASSERT_TRUE(attr);

  EXPECT_EQ(attr->starts, ::ml_drift::BHWC(0, 0, 0, 0));
  EXPECT_EQ(attr->ends, ::ml_drift::BHWC(1, 4, 4, 3));
  EXPECT_EQ(attr->strides, ::ml_drift::BHWC(1, 1, 1, 1));
}

INSTANTIATE_TEST_SUITE_P(ConvertStridedSliceTest, ConvertStridedSliceTest,
                         ::testing::Values(  // clang-format off
                             // go/keep-sorted start numeric=yes
                             kTfLiteBool,
                             kTfLiteFloat16,
                             kTfLiteFloat32,
                             kTfLiteInt8,
                             kTfLiteInt16,
                             kTfLiteInt32,
                             kTfLiteUInt8,
                             kTfLiteUInt16,
                             kTfLiteUInt32
                             // go/keep-sorted end
                             // clang-format on
                             ));

}  // namespace
}  // namespace litert::ml_drift::ir
