package(
    # copybara:uncomment default_applicable_licenses = ["@org_tensorflow//tensorflow:license"],
    licenses = ["notice"],
)

filegroup(
    name = "nnapi_delegate_src",
    srcs = [
        "NnApiDelegate.java",
        "NnApiDelegateImpl.java",
    ],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "nnapi_delegate_api_src",
    srcs = ["NnApiDelegate.java"],
    visibility = ["//visibility:public"],
)

filegroup(
    name = "nnapi_delegate_impl_src",
    srcs = ["NnApiDelegateImpl.java"],
    visibility = ["//visibility:public"],
)
