#Copyright (C) 2025 Intel Corporation
#SPDX-License-Identifier: Apache-2.0

load("//litert/build_common:litert_build_defs.bzl", "litert_lib")

package(
    default_visibility = ["//litert:__subpackages__"],
)

cc_library(
    name = "common",
    deps = [
        "//litert/c:litert_common",
        "//litert/c:litert_model",
        "//litert/cc:litert_model",
    ],
)
