# Copyright 2025 Google LLC.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

package(
    # copybara:uncomment default_applicable_licenses = ["@org_tensorflow//tensorflow:license"],
)

LITERT_C_API_DEPS = [
    "//litert/c:litert_common",
    "//litert/c:litert_opaque_options",
    "//litert/c/options:litert_google_tensor_options",
    "//litert/c/options:litert_intel_openvino_options",
    "//litert/c/options:litert_mediatek_options",
    "//litert/c/options:litert_qualcomm_options",
    "//litert/c/options:litert_samsung_options",
    "//litert/c/options:litert_runtime_options",
]
