#!/usr/bin/env python3
# Copyright 2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""Regenerates third_party/intel_openvino/openvino_version.bzl.

third_party/intel_openvino/openvino_version.bzl is the single source of
truth for which OpenVINO package LiteRT builds against: both the Bazel
build (third_party/intel_openvino/openvino.bzl) and the pip SDK
(ci/tools/python/vendor_sdk/intel/setup.py, via sdist-build-time
substitution) read the literal URLs and version it contains. Nothing in
the build path stitches URLs together; this script is the only place that
does, and it is meant to be run by a developer, not by the build.

Usage:
  # Bump to a new build (release or nightly) and verify the derived URLs
  # are live before committing:
  python ci/tools/update_openvino_version.py \\
      --windows-url 'https://storage.openvinotoolkit.org/repositories/openvino/packages/2026.3.1/windows/openvino_toolkit_windows_2026.3.1.22476.56d9685302d_x86_64.zip' \\
      --validate

  # CI guardrail: assert the committed file matches what re-deriving from
  # its own windows URL would produce (i.e. it wasn't hand-edited or only
  # partially updated).
  python ci/tools/update_openvino_version.py --check
"""

import argparse
import pathlib
import re
import sys
import urllib.error
import urllib.request
from urllib.parse import urlparse

REPO_ROOT = pathlib.Path(__file__).resolve().parent.parent.parent
OUTPUT_BZL = REPO_ROOT / "third_party/intel_openvino/openvino_version.bzl"

_ALLOWED_SCHEME = "https"
_ALLOWED_HOST = "storage.openvinotoolkit.org"

# OS keys, in the order they should appear in the generated file.
_OS_KEYS = ("windows", "ubuntu24", "ubuntu22", "android")

_TEMPLATE = '''# Copyright 2026 Intel Corporation
# SPDX-License-Identifier: Apache-2.0
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
"""Single source of truth for the pinned OpenVINO package.

Generated by ci/tools/update_openvino_version.py from the Windows package
URL below — do not edit by hand. To bump the build or switch between the
release/nightly channel, re-run:

    python ci/tools/update_openvino_version.py \\\\
        --windows-url '<new windows archive url>' --validate

Both the Bazel build (third_party/intel_openvino/openvino.bzl) and the pip
SDK (ci/tools/python/vendor_sdk/intel/setup.py) read the literal values
below; neither stitches URLs together itself.
"""

# "release" | "nightly" — informational, derived from the URL shape.
OPENVINO_CHANNEL = "{channel}"

# PEP 440 version for `pip install openvino=={{version}}`.
OPENVINO_PEP440_VERSION = "{pep440_version}"

# One fully-formed archive URL per OS variant.
OPENVINO_URLS = {{
    "windows": "{windows_url}",
    "ubuntu24": "{ubuntu24_url}",
    "ubuntu22": "{ubuntu22_url}",
    "android": "{android_url}",
}}

# Extracted top-level directory name per archive (basename minus
# extension), i.e. the Bazel repo-rule symlink target.
OPENVINO_DIRS = {{
    "windows": "{windows_dir}",
    "ubuntu24": "{ubuntu24_dir}",
    "ubuntu22": "{ubuntu22_dir}",
    "android": "{android_dir}",
}}
'''


def _validate_windows_url(url: str) -> None:
  """Rejects URLs that aren't plausible OpenVINO Windows archive URLs."""
  parsed = urlparse(url)
  if parsed.scheme != _ALLOWED_SCHEME:
    raise ValueError(
        f"--windows-url must use {_ALLOWED_SCHEME!r}, got: {parsed.scheme!r}"
    )
  if parsed.netloc != _ALLOWED_HOST:
    raise ValueError(
        f"--windows-url host must be {_ALLOWED_HOST!r}, got:"
        f" {parsed.netloc!r}"
    )
  if "_windows_" not in url or not url.endswith(".zip"):
    raise ValueError(
        "--windows-url does not look like an OpenVINO Windows archive URL"
        f" (expected it to contain '_windows_' and end with '.zip'): {url}"
    )


def _derive_urls(windows_url: str) -> tuple[str, dict[str, str]]:
  """Derives the channel and all four archive URLs from the Windows URL."""
  channel = "nightly" if "/nightly/" in windows_url else "release"

  urls = {"windows": windows_url}
  for os_key in ("ubuntu24", "ubuntu22", "android"):
    url = windows_url.replace("_windows_", f"_{os_key}_")
    url = url.replace(".zip", ".tgz")
    # Release layout has an OS-subdir ("/windows/" vs "/linux/"); nightly
    # is a flat directory, so this replace is a no-op there.
    url = url.replace("/windows/", "/linux/")
    urls[os_key] = url
  return channel, urls


def _pep440_version(channel: str, urls: dict[str, str]) -> str:
  """Derives the PEP 440 version string from the Windows URL."""
  filename = urls["windows"].rsplit("/", 1)[-1]
  if channel == "nightly":
    match = re.search(r"_(\d+\.\d+\.\d+\.dev\d+)_", filename)
    if not match:
      raise ValueError(
          "Could not find a '<version>.dev<date>' token in nightly"
          f" filename: {filename}"
      )
    return match.group(1)

  # Release: the channel-dir path segment is the plain "{version}".
  match = re.search(r"/packages/(\d+\.\d+\.\d+)/", urls["windows"])
  if not match:
    raise ValueError(
        "Could not find a '/packages/<version>/' path segment in release"
        f" URL: {urls['windows']}"
    )
  return match.group(1)


def _dir_for(url: str) -> str:
  """Returns the archive's extracted top-level dir name (basename sans ext)."""
  basename = url.rsplit("/", 1)[-1]
  for ext in (".tar.gz", ".tgz", ".zip"):
    if basename.endswith(ext):
      return basename[: -len(ext)]
  raise ValueError(f"Unrecognized archive extension for: {basename}")


def _head_ok(url: str) -> bool:
  """Returns whether `url` resolves, trying HEAD then a ranged GET."""
  request = urllib.request.Request(url, method="HEAD")
  try:
    with urllib.request.urlopen(request, timeout=30) as resp:
      return 200 <= resp.status < 300
  except urllib.error.HTTPError as e:
    if e.code == 405:  # Method not allowed; some hosts reject HEAD.
      return _ranged_get_ok(url)
    return False
  except urllib.error.URLError:
    return False


def _ranged_get_ok(url: str) -> bool:
  request = urllib.request.Request(url, headers={"Range": "bytes=0-0"})
  try:
    with urllib.request.urlopen(request, timeout=30) as resp:
      return resp.status in (200, 206)
  except (urllib.error.HTTPError, urllib.error.URLError):
    return False


def _validate_urls(urls: dict[str, str]) -> None:
  failures = []
  for os_key in _OS_KEYS:
    url = urls[os_key]
    print(f"Checking {os_key}: {url}")
    if not _head_ok(url):
      failures.append((os_key, url))
  if failures:
    for os_key, url in failures:
      print(f"ERROR: {os_key} URL is not reachable: {url}", file=sys.stderr)
    raise SystemExit(1)
  print("All URLs validated OK.")


def _render(
    channel: str,
    urls: dict[str, str],
    dirs: dict[str, str],
    pep440_version: str,
) -> str:
  return _TEMPLATE.format(
      channel=channel,
      pep440_version=pep440_version,
      windows_url=urls["windows"],
      ubuntu24_url=urls["ubuntu24"],
      ubuntu22_url=urls["ubuntu22"],
      android_url=urls["android"],
      windows_dir=dirs["windows"],
      ubuntu24_dir=dirs["ubuntu24"],
      ubuntu22_dir=dirs["ubuntu22"],
      android_dir=dirs["android"],
  )


def _load_committed_windows_url() -> str:
  """Extracts OPENVINO_URLS['windows'] from the committed .bzl (regex, no exec())."""
  text = OUTPUT_BZL.read_text()
  match = re.search(r'"windows":\s*"([^"]+)"', text)
  if not match:
    raise ValueError(f"Could not find a windows URL in {OUTPUT_BZL}")
  return match.group(1)


def main() -> int:
  parser = argparse.ArgumentParser(
      description=__doc__,
      formatter_class=argparse.RawDescriptionHelpFormatter,
  )
  parser.add_argument(
      "--windows-url",
      help=(
          "The OpenVINO Windows package archive URL to derive the "
          "ubuntu24/ubuntu22/android URLs and PEP 440 version from. "
          "Required unless --check is given."
      ),
  )
  parser.add_argument(
      "--validate",
      action="store_true",
      help="HEAD-check all four derived URLs before writing.",
  )
  parser.add_argument(
      "--check",
      action="store_true",
      help=(
          "Do not write anything. Re-derive from the windows URL already "
          "committed in openvino_version.bzl and fail if the regenerated "
          "file would differ (CI drift guard)."
      ),
  )
  args = parser.parse_args()

  if args.check:
    if args.windows_url:
      parser.error("--check cannot be combined with --windows-url")
    windows_url = _load_committed_windows_url()
  else:
    if not args.windows_url:
      parser.error("--windows-url is required unless --check is given")
    windows_url = args.windows_url

  _validate_windows_url(windows_url)
  channel, urls = _derive_urls(windows_url)
  pep440_version = _pep440_version(channel, urls)
  dirs = {os_key: _dir_for(urls[os_key]) for os_key in _OS_KEYS}

  if args.validate:
    _validate_urls(urls)

  rendered = _render(channel, urls, dirs, pep440_version)

  if args.check:
    current = OUTPUT_BZL.read_text() if OUTPUT_BZL.exists() else ""
    if current != rendered:
      print(
          f"ERROR: {OUTPUT_BZL} is out of date or was hand-edited.\n"
          "Re-run: python ci/tools/update_openvino_version.py --windows-url"
          " '<url>' --validate",
          file=sys.stderr,
      )
      return 1
    print(f"OK: {OUTPUT_BZL} matches its derivation from the windows URL.")
    return 0

  OUTPUT_BZL.write_text(rendered)
  print(f"Wrote {OUTPUT_BZL}")
  return 0


if __name__ == "__main__":
  sys.exit(main())
