#
# SPDX-FileCopyrightText: Copyright 2026 Arm Limited and/or its affiliates <open-source-office@arm.com>
# SPDX-License-Identifier: Apache-2.0
#

load("@rules_cc//cc:cc_library.bzl", "cc_library")

package(
    default_visibility = ["//litert:__subpackages__"],
)

cc_library(
    name = "arm_jit_executable",
    hdrs = ["arm_jit_executable.h"],
)
