// Copyright 2026 Google LLC.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#include "litert/tflite_support/op_resolver/op_resolver.h"

#include <string>

#include <gmock/gmock.h>
#include <gtest/gtest.h>
#include "absl/types/span.h"  // from @com_google_absl
#include "litert/c/options/litert_cpu_options.h"
#include "litert/cc/litert_common.h"
#include "litert/cc/litert_compiled_model.h"
#include "litert/cc/litert_environment.h"
#include "litert/cc/litert_options.h"
#include "litert/cc/litert_tensor_buffer.h"
#include "litert/test/common.h"
#include "litert/test/matchers.h"
#include "litert/test/testdata/simple_model_test_vectors.h"
#include "tflite/mutable_op_resolver.h"

// Generated by `gen_selected_ops` on `simple_model.tflite`.
void RegisterSelectedOps(::tflite::MutableOpResolver* resolver);

namespace litert {
namespace {

TEST(OpResolverTest, SetOpResolverWithMutableOpResolver) {
  LITERT_ASSERT_OK_AND_ASSIGN(auto env, Environment::Create({}));
  LITERT_ASSERT_OK_AND_ASSIGN(auto options, Options::Create());
  LITERT_ASSERT_OK(options.SetHardwareAccelerators(HwAccelerators::kCpu));
  LITERT_ASSERT_OK_AND_ASSIGN(auto& cpu_options, options.GetCpuOptions());
  LITERT_ASSERT_OK(cpu_options.SetKernelMode(kLiteRtCpuKernelModeBuiltin));

  tflite::MutableOpResolver resolver;
  RegisterSelectedOps(&resolver);
  LITERT_ASSERT_OK(tflite_support::SetOpResolver(options, &resolver));

  std::string model_path = testing::GetTestFilePath(kModelFileName);
  LITERT_ASSERT_OK_AND_ASSIGN(auto compiled_model,
                              CompiledModel::Create(env, model_path, options));

  LITERT_ASSERT_OK_AND_ASSIGN(auto input_buffers,
                              compiled_model.CreateInputBuffers());
  LITERT_ASSERT_OK_AND_ASSIGN(auto output_buffers,
                              compiled_model.CreateOutputBuffers());

  LITERT_ASSERT_OK(
      input_buffers[0].Write<float>(absl::MakeConstSpan(kTestInput0Tensor)));
  LITERT_ASSERT_OK(
      input_buffers[1].Write<float>(absl::MakeConstSpan(kTestInput1Tensor)));

  LITERT_ASSERT_OK(compiled_model.Run(input_buffers, output_buffers));

  LITERT_ASSERT_OK_AND_ASSIGN(
      auto lock_and_addr,
      TensorBufferScopedLock::Create<const float>(
          output_buffers[0], TensorBuffer::LockMode::kRead));
  auto output = absl::MakeSpan(lock_and_addr.second, kTestOutputSize);
  EXPECT_THAT(output,
              ::testing::Pointwise(::testing::FloatNear(1e-5),
                                   absl::MakeConstSpan(kTestOutputTensor)));
}

TEST(OpResolverTest, UnregisteredOpFails) {
  LITERT_ASSERT_OK_AND_ASSIGN(auto env, Environment::Create({}));
  LITERT_ASSERT_OK_AND_ASSIGN(auto options, Options::Create());
  LITERT_ASSERT_OK(options.SetHardwareAccelerators(HwAccelerators::kCpu));
  LITERT_ASSERT_OK_AND_ASSIGN(auto& cpu_options, options.GetCpuOptions());
  LITERT_ASSERT_OK(cpu_options.SetKernelMode(kLiteRtCpuKernelModeBuiltin));

  // Empty resolver without Register_ADD: overrides the default builtin op
  // resolver and must fail to build the interpreter.
  tflite::MutableOpResolver empty_resolver;
  LITERT_ASSERT_OK(tflite_support::SetOpResolver(options, &empty_resolver));

  std::string model_path = testing::GetTestFilePath(kModelFileName);
  auto compiled_model = CompiledModel::Create(env, model_path, options);
  EXPECT_FALSE(compiled_model.HasValue());
}

TEST(OpResolverTest, NullArgumentReturnsError) {
  LITERT_ASSERT_OK_AND_ASSIGN(auto options, Options::Create());
  EXPECT_FALSE(tflite_support::SetOpResolver(options, nullptr).HasValue());
}

}  // namespace
}  // namespace litert
