/******************************************************************************
 * Copyright (C) 2025 Broadcom.
 * The term "Broadcom" refers to Broadcom Inc. and/or its subsidiaries.
 *
 * This program is the proprietary software of Broadcom and/or its licensors,
 * and may only be used, duplicated, modified or distributed pursuant to
 * the terms and conditions of a separate, written license agreement executed
 * between you and Broadcom (an "Authorized License").  Except as set forth in
 * an Authorized License, Broadcom grants no license (express or implied),
 * right to use, or waiver of any kind with respect to the Software, and
 * Broadcom expressly reserves all rights in and to the Software and all
 * intellectual property rights therein. IF YOU HAVE NO AUTHORIZED LICENSE,
 * THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 * IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.
 *
 * Except as expressly set forth in the Authorized License,
 *
 * 1.     This program, including its structure, sequence and organization,
 * constitutes the valuable trade secrets of Broadcom, and you shall use all
 * reasonable efforts to protect the confidentiality thereof, and to use this
 * information only in connection with your use of Broadcom integrated circuit
 * products.
 *
 * 2.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED
 * "AS IS" AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS
 * OR WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH
 * RESPECT TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL
 * IMPLIED WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR
 * A PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS, QUIET
 * ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION. YOU ASSUME
 * THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE SOFTWARE.
 *
 * 3.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM
 * OR ITS LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL,
 * INDIRECT, OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY
 * RELATING TO YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM
 * HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN
 * EXCESS OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1,
 * WHICHEVER IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY
 * FAILURE OF ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
 *
 * Portions generated by GenAI: Cursor 2.0, Claude Sonnet 4.5
 *
 ******************************************************************************/
/* #define BSTORM_DEBUG_LEVEL_VERBOSE 1 */
#include "bstorm_core_internal.h"
#include "bstorm_common.h"
#include "bstorm_init.h"
#include "bstorm_types.h"
#include "bstorm_operations.h"
#include "bstorm_graph_info.h"
#include "bstm/compiler/bstorm_compiler_bstm_offline.h"
#include "flatbuf/bstorm_flatbuf.h"
#include "common/bstorm_util_litert.h"

#include "litert/c/litert_common.h"
#include "litert/c/litert_tensor_buffer_requirements.h"
#include "litert/c/litert_tensor_buffer_types.h"
#include "litert/cc/litert_tensor_buffer.h"
#include "litert/cc/litert_tensor_buffer_requirements.h"
#include "litert/vendors/c/litert_dispatch.h"
#include "litert/vendors/c/litert_dispatch_api.h"

#include <map>
#include <memory>
#include <string>
#include <cstdlib>
#include <cstring>

//==============================================================================
// Device Context Class Implementation
//==============================================================================

struct bstorm_dispatch_config {
    enum bstorm_engine_control bstm;
    std::string graph_path;
    std::string hw_remote;
    bool direct_access = true;
};

class bstorm_device_context {
  public:
    bstorm_device_context()
    {
        config_.bstm = bstorm_engine_default;
    }

    ~bstorm_device_context()
    {
        if (bstorm_context_) {
            bstorm_context_destroy(bstorm_context_);
        }
    }

    bstorm_result init()
    {
        bstorm_result rc = BSTORM_RESULT_INITIALIZER();
        struct bstorm_context_config context_config;
        struct bstorm_context_status status;
        const char* options_env = std::getenv("BSTORM_DISPATCH_OPTIONS");

        bstorm_context_config_Default(&context_config);
        if (options_env != nullptr) {
            B_STORM_DEBUG("BSTORM_DISPATCH_OPTIONS: %s", options_env);
            std::string options_str(options_env);
            B_STORM_CHECKED_CALL(rc, parse_options, (options_str), err_parse_options);
        }
        if (!config_.hw_remote.empty()) {
            context_config.bstm.hw_config.remote.server = config_.hw_remote.c_str();
            B_STORM_DEBUG("Using remote BSTM hardware: %s", config_.hw_remote.c_str());
        }
        if (config_.bstm == bstorm_engine_disable) {
            context_config.engine.allow.bstm = false;
        } else if (config_.bstm == bstorm_engine_enable) {
            context_config.engine.allow.bstm = true;
        }
        B_STORM_CHECKED_NULL_CALL(rc, bstorm_context_, bstorm_context_create, (&context_config), err_context);
        B_STORM_CHECKED_CALL(rc, bstorm_context_get_status, (bstorm_context_, &status), err_status);
        if (config_.bstm == bstorm_engine_enable) {
            B_STORM_CONDITION(rc, status.engine.bstm.enabled, err_engine);
        }

        return rc;

    err_engine:
    err_status:
        bstorm_context_destroy(bstorm_context_);
        bstorm_context_ = nullptr;
    err_context:
    err_parse_options:
        return rc;
    }

    struct bstorm_context *get_bstorm_context() const
    {
        B_STORM_ASSERT(bstorm_context_);
        return bstorm_context_;
    }

    const bstorm_dispatch_config& get_config() const
    {
        return config_;
    }

    bstorm_result register_buffer(LiteRtTensorBuffer buffer, void** handle)
    {
        bstorm_result rc = BSTORM_RESULT_INITIALIZER();
        *handle = static_cast<void*>(buffer);
        buffer_map_[*handle] = buffer;
        return rc;
    }

    bstorm_result unregister_buffer(void* handle)
    {
        bstorm_result rc = BSTORM_RESULT_INITIALIZER();
        buffer_map_.erase(handle);
        return rc;
    }

    LiteRtTensorBuffer lookup_buffer(void* handle)
    {
        auto it = buffer_map_.find(handle);
        if (it != buffer_map_.end()) {
            return it->second;
        }
        return nullptr;
    }

  private:
    bstorm_result parse_options(const std::string& options_str)
    {
        bstorm_result rc = BSTORM_RESULT_INITIALIZER();
        size_t pos = 0;
        std::string token;
        std::string options = options_str;

        while ((pos = options.find(',')) != std::string::npos) {
            token = options.substr(0, pos);
            B_STORM_CHECKED_CALL(rc, parse_option_pair, (token), err_parse_option_pair);
            options.erase(0, pos + 1);
        }
        // Parse the last token (or the only token if no comma was found)
        if (!options.empty()) {
            B_STORM_CHECKED_CALL(rc, parse_option_pair, (options), err_parse_option_pair);
        }
        return rc;
    err_parse_option_pair:
        return rc;
    }

    bstorm_result parse_option_pair(const std::string& option)
    {
        bstorm_result rc = BSTORM_RESULT_INITIALIZER();
        size_t eq_pos = option.find('=');
        if (eq_pos != std::string::npos) {
            std::string key = option.substr(0, eq_pos);
            std::string value = option.substr(eq_pos + 1);
            const char* cvalue = value.c_str();

            if (key == "graph-path") {
                config_.graph_path = value;
            } else if (key == "bstm") {
                config_.bstm = bstorm_engine_control_from_arg(cvalue);
            } else if (key == "direct-access") {
                config_.direct_access = atoi(cvalue);
            } else if (key == "bstm-hw-remote") {
                config_.hw_remote = value;
                auto slash = config_.hw_remote.rfind('/');
                if (slash != std::string::npos) {
                    config_.hw_remote[slash] = ':';
                }
            } else {
                B_STORM_ERROR(rc, NotSupported, err_invalid_option);
            }
        }
        return rc;
    err_invalid_option:
        return rc;
    }

    struct bstorm_context *bstorm_context_ = nullptr;
    std::map<void*, LiteRtTensorBuffer> buffer_map_;
    bstorm_dispatch_config config_;
};

//==============================================================================
// Graph Class Implementation
//==============================================================================

class bstorm_dispatch_graph {
    public:
      bstorm_dispatch_graph(bstorm_device_context* device_context)
          : device_context_(device_context)
      {
          memset(&flatbuf_, 0, sizeof(flatbuf_));
          memset(&graph_state_, 0, sizeof(graph_state_));
      }

      ~bstorm_dispatch_graph()
      {
          unprepare_graph();
          unload_graph();
      }

      bstorm_result load_graph(const std::string& graph_name, const std::string& graph_path, unsigned& num_inputs)
      {
          bstorm_result rc = BSTORM_RESULT_INITIALIZER();
          struct bstorm_Graph_Info info;
          std::string resolved_graph_path = graph_name;

          B_STORM_PRECONDITION(rc, !graph_loaded_, err_loaded);
          if (!graph_path.empty()) {
              resolved_graph_path = graph_path + "/" + graph_name;
          }
          B_STORM_DEBUG("Using bstorm graph: %s", resolved_graph_path.c_str());
          B_STORM_CHECKED_CALL(rc, bstorm_flatbuf_read, (resolved_graph_path.c_str(), &flatbuf_, nullptr), err_read);
          B_STORM_ASSERT(flatbuf_.graph != NULL);
          B_STORM_ASSERT(flatbuf_.graph->graph != NULL);
          bstorm_graph_ = flatbuf_.graph->graph;
          graph_loaded_ = true;

          bstorm_Graph_GetInfo(bstorm_graph_, &info);
          B_STORM_DEBUG("Loaded graph: nodes=%u, blobs=%u, inputs=%u, outputs=%u",
                        info.nodes, info.blobs, info.inputs, info.outputs);
          num_inputs = info.inputs;
          return rc;

      err_read:
      err_loaded:
          return rc;
      }

      void unload_graph()
      {
          if (graph_loaded_) {
              bstorm_flatbuf_free(&flatbuf_);
              graph_loaded_ = false;
              bstorm_graph_ = NULL;
          }
      }

      bstorm_result prepare_graph(struct bstorm_Blobs& output_blobs)
      {
          bstorm_result rc = BSTORM_RESULT_INITIALIZER();

          B_STORM_PRECONDITION(rc, graph_loaded_, err_loaded);
          B_STORM_PRECONDITION(rc, !graph_prepared_, err_prepared);
          B_STORM_CHECKED_CALL(rc, bstorm_Graph_Prepare, (device_context_->get_bstorm_context(), bstorm_graph_, &graph_state_, &output_blobs), err_prepare);
          graph_prepared_ = true;
          return rc;

      err_prepare:
      err_prepared:
      err_loaded:
          return rc;
      }

      void unprepare_graph()
      {
          if (graph_prepared_) {
              bstorm_Graph_Unprepare(&graph_state_);
              graph_prepared_ = false;
          }
      }

      bstorm_result execute_graph(struct bstorm_Blobs& input_blobs, struct bstorm_Blobs& output_blobs)
      {
          bstorm_result rc = BSTORM_RESULT_INITIALIZER();

          B_STORM_PRECONDITION(rc, graph_prepared_, err_not_prepared);
          B_STORM_CHECKED_CALL(rc, bstorm_Graph_Execute, (&graph_state_, &input_blobs, &output_blobs), err_execute);
          return rc;

      err_execute:
      err_not_prepared:
          return rc;
      }

      bstorm_result copy_shape(unsigned blob_index, struct bstorm_Blob& blob, bool is_input)
      {
          bstorm_result rc = BSTORM_RESULT_INITIALIZER();
          const struct bstorm_GraphInfo *graph_info;
          const struct bstorm_Blobs *graph_blobs;
          const struct bstorm_Blob *graph_blob;

          B_STORM_PRECONDITION(rc, graph_loaded_, err_not_loaded);
          bstorm_Graph_GetGraphInfo(bstorm_graph_, &graph_info);
          B_STORM_ASSERT(graph_info != NULL);
          graph_blobs = (is_input) ? &graph_info->inputs : &graph_info->outputs;
          B_STORM_CHECKED_NULL_CALL(rc, graph_blob, bstorm_Blobs_GetBlob, (graph_blobs, blob_index), err_copy);
          B_STORM_CHECKED_CALL(rc, bstorm_BlobShape_Copy, (&blob.shape, &graph_blob->shape), err_copy);
          return rc;

      err_copy:
      err_not_loaded:
          return rc;
      }

  private:
    bool graph_loaded_ = false;
    bool graph_prepared_ = false;
    struct bstorm_Graph* bstorm_graph_ = NULL;
    struct bstorm_flatbuf flatbuf_;
    struct bstorm_GraphState graph_state_;
    bstorm_device_context* device_context_;
};

//==============================================================================
// Precompiled Graph Class Implementation
// Loads .bstm files and executes via bstorm_bstm_precompiled_exec()
//==============================================================================

class bstorm_dispatch_precompiled_graph {
    public:
      bstorm_dispatch_precompiled_graph(bstorm_device_context* device_context)
          : device_context_(device_context)
      {
      }

      ~bstorm_dispatch_precompiled_graph()
      {
          unload_model();
      }

      bstorm_result load_model_from_file(const std::string& bstm_path, const std::string& graph_path, unsigned& num_inputs)
      {
          bstorm_result rc = BSTORM_RESULT_INITIALIZER();
          struct bstorm_bstm_precompiled_model_config config;
          std::string resolved_path = bstm_path;

          B_STORM_PRECONDITION(rc, !model_loaded_, err_loaded);
          if (!graph_path.empty()) {
              resolved_path = graph_path + "/" + bstm_path;
          }
          B_STORM_DEBUG("Loading precompiled .bstm from file: %s", resolved_path.c_str());
          init_load_config(config);
          precompiled_model_ = bstorm_bstm_precompiled_model_load(
              device_context_->get_bstorm_context(), resolved_path.c_str(), &config);
          return finish_load(num_inputs);

      err_loaded:
          return rc;
      }

      bstorm_result load_model_from_buffer(const struct bstorm_compiler_bstm_offline_output_buffer& buffer, unsigned& num_inputs)
      {
          bstorm_result rc = BSTORM_RESULT_INITIALIZER();
          struct bstorm_bstm_precompiled_model_config config;

          B_STORM_PRECONDITION(rc, !model_loaded_, err_loaded);
          B_STORM_DEBUG("Loading precompiled .bstm from buffer (%zu bytes)", buffer.buffer_size);
          init_load_config(config);
          precompiled_model_ = bstorm_bstm_precompiled_model_load_from_buffer(
              device_context_->get_bstorm_context(), &buffer, &config);
          return finish_load(num_inputs);

      err_loaded:
          return rc;
      }

      void unload_model()
      {
          if (model_loaded_) {
              bstorm_bstm_precompiled_model_release(precompiled_model_);
              precompiled_model_ = NULL;
              model_loaded_ = false;
          }
      }

      bstorm_result execute(struct bstorm_Blobs& input_blobs, struct bstorm_Blobs& output_blobs)
      {
          bstorm_result rc = BSTORM_RESULT_INITIALIZER();
          struct bstorm_bstm_PrecompiledExecuteStats stats;
          unsigned i;

          B_STORM_PRECONDITION(rc, model_loaded_, err_not_loaded);
          for (i = 0; i < input_blobs.count; i++) {
              const struct bstorm_Blob* blob = bstorm_Blobs_GetBlob(&input_blobs, i);
              if (blob && blob->data) {
                  B_STORM_CHECKED_CALL(rc, bstorm_bstm_precompiled_write_input,
                      (precompiled_model_, i, blob->data, bstorm_BlobShape_Size(&blob->shape)), err_write);
              }
          }
          memset(&stats, 0, sizeof(stats));
          B_STORM_CHECKED_CALL(rc, bstorm_bstm_precompiled_exec,
              (device_context_->get_bstorm_context(), precompiled_model_, &stats), err_exec);
          B_STORM_DEBUG("Precompiled exec: cpu_time=%u us, cycles=%u", stats.cpu_time, stats.cycles);
          for (i = 0; i < output_blobs.count; i++) {
              const struct bstorm_Blob* blob = bstorm_Blobs_GetBlob(&output_blobs, i);
              if (blob && blob->data) {
                  B_STORM_CHECKED_CALL(rc, bstorm_bstm_precompiled_read_output,
                      (precompiled_model_, i, blob->data, bstorm_BlobShape_Size(&blob->shape)), err_read);
              }
          }
          return rc;

      err_read:
      err_exec:
      err_write:
      err_not_loaded:
          return rc;
      }

      unsigned get_num_outputs() const { return num_outputs_; }

  private:
    void init_load_config(struct bstorm_bstm_precompiled_model_config& config)
    {
        direct_access_ = device_context_->get_config().hw_remote.empty()
                         && device_context_->get_config().direct_access;
        bstorm_bstm_precompiled_model_config_default(&config);
        if (direct_access_) {
            config.payload_access = bstorm_bstm_payload_access_direct;
        }
    }

    bstorm_result finish_load(unsigned& num_inputs)
    {
        bstorm_result rc = BSTORM_RESULT_INITIALIZER();
        struct bstorm_bstm_precompiled_model_info info;

        if (!precompiled_model_) {
            B_STORM_ERROR(rc, Unknown, err_load);
        }
        B_STORM_CHECKED_CALL(rc, bstorm_bstm_precompiled_get_model_info, (precompiled_model_, &info), err_info);
        num_inputs = info.input.count;
        num_outputs_ = info.output.count;
        model_loaded_ = true;
        B_STORM_DEBUG("Loaded precompiled model: inputs=%u, outputs=%u, size=%u",
                      num_inputs, num_outputs_, info.size);
        return rc;

    err_info:
        bstorm_bstm_precompiled_model_release(precompiled_model_);
        precompiled_model_ = NULL;
    err_load:
        return rc;
    }

    bool model_loaded_ = false;
    bool direct_access_ = false;
    unsigned num_outputs_ = 0;
    struct bstorm_bstm_precompiled_model* precompiled_model_ = NULL;
    bstorm_device_context* device_context_;
};

//==============================================================================
// Invocation Context Class Implementation
//==============================================================================

class bstorm_invocation_context {
  public:
    bstorm_invocation_context() {}

    ~bstorm_invocation_context()
    {
        if (input_blobs_allocated_) {
            bstorm_Blobs_Clear(&input_blobs_);
            bstorm_Blobs_Uninit(&input_blobs_);
        }
        if (output_blobs_allocated_) {
            bstorm_Blobs_Clear(&output_blobs_);
            bstorm_Blobs_Uninit(&output_blobs_);
        }
    }

    bstorm_result init(
        bstorm_device_context* device_context,
        LiteRtDispatchExecutableType exec_type,
        const LiteRtMemBuffer* mem_buffer,
        const char* function_name,
        unsigned num_inputs,
        unsigned num_outputs)
    {
        bstorm_result rc = BSTORM_RESULT_INITIALIZER();
        std::string function_name_str(function_name);
        unsigned i;

        B_STORM_PRECONDITION(rc, device_context_ == NULL, err_init);
        if (!device_context || !mem_buffer || !function_name) {
            B_STORM_ERROR(rc, InvalidParameter, err_invalid_args);
        }
        device_context_ = device_context;

        bstorm_Blobs_Init(&input_blobs_);
        B_STORM_CHECKED_CALL(rc, bstorm_Blobs_AllocateBlobs, (&input_blobs_, num_inputs), err_input_blobs);
        input_blobs_allocated_ = true;
        for (i = 0; i < num_inputs; i++) {
            B_STORM_CHECKED_CALL(rc, bstorm_Blobs_UseInlineBlob, (&input_blobs_, i), err_input_blobs);
        }

        bstorm_Blobs_Init(&output_blobs_);
        B_STORM_CHECKED_CALL(rc, bstorm_Blobs_AllocateBlobs, (&output_blobs_, num_outputs), err_output_blobs);
        output_blobs_allocated_ = true;
        for (i = 0; i < num_outputs; i++) {
            B_STORM_CHECKED_CALL(rc, bstorm_Blobs_UseInlineBlob, (&output_blobs_, i), err_output_blobs);
        }

        {
            unsigned graph_num_inputs;
            const uint8_t* data = static_cast<const uint8_t*>(mem_buffer->base_addr);

            if (function_name_str == "bstm.embedded") {
                struct bstorm_compiler_bstm_offline_output_buffer bstm_buf = {(void*)(data + mem_buffer->offset), mem_buffer->size};

                B_STORM_DEBUG("Dispatch: function_name='%s' buffer_size=%zu", function_name, bstm_buf.buffer_size);
                precompiled_graph_ = std::make_unique<bstorm_dispatch_precompiled_graph>(device_context_);
                B_STORM_ASSERT(precompiled_graph_);
                B_STORM_CHECKED_CALL(rc, precompiled_graph_->load_model_from_buffer, (bstm_buf, graph_num_inputs), err_load_precompiled);
                B_STORM_ASSERT(graph_num_inputs == num_inputs);
                B_STORM_ASSERT(precompiled_graph_->get_num_outputs() == num_outputs);
            } else {
                std::string file_name(reinterpret_cast<const char*>(data + mem_buffer->offset), mem_buffer->size);
                const std::string& graph_path = device_context_->get_config().graph_path;

                B_STORM_DEBUG("Dispatch: function_name='%s' file='%s'", function_name, file_name.c_str());
                if (function_name_str == "bstm") {
                    precompiled_graph_ = std::make_unique<bstorm_dispatch_precompiled_graph>(device_context_);
                    B_STORM_ASSERT(precompiled_graph_);
                    B_STORM_CHECKED_CALL(rc, precompiled_graph_->load_model_from_file, (file_name, graph_path, graph_num_inputs), err_load_precompiled);
                    B_STORM_ASSERT(graph_num_inputs == num_inputs);
                    B_STORM_ASSERT(precompiled_graph_->get_num_outputs() == num_outputs);
                } else {
                    dispatch_graph_ = std::make_unique<bstorm_dispatch_graph>(device_context_);
                    B_STORM_ASSERT(dispatch_graph_);
                    B_STORM_DEBUG("Loading graph from file: %s", file_name.c_str());
                    B_STORM_CHECKED_CALL(rc, dispatch_graph_->load_graph, (file_name, graph_path, graph_num_inputs), err_load_graph);
                    B_STORM_ASSERT(graph_num_inputs == num_inputs);
                    B_STORM_CHECKED_CALL(rc, dispatch_graph_->prepare_graph, (output_blobs_), err_prepare);
                    B_STORM_ASSERT(output_blobs_.count == num_outputs);
                }
            }
        }
        return rc;

    err_load_precompiled:
        if (precompiled_graph_) {
            precompiled_graph_->unload_model();
        }
    err_prepare:
        if (dispatch_graph_) {
            dispatch_graph_->unload_graph();
        }
    err_load_graph:
    err_output_blobs:
        bstorm_Blobs_Clear(&output_blobs_);
        bstorm_Blobs_Uninit(&output_blobs_);
        output_blobs_allocated_ = false;
    err_input_blobs:
        bstorm_Blobs_Clear(&input_blobs_);
        bstorm_Blobs_Uninit(&input_blobs_);
        input_blobs_allocated_ = false;
        device_context_ = NULL;
    err_invalid_args:
    err_init:
        return rc;
    }

    bstorm_result attach_input(unsigned graph_input_index, void* handle)
    {
        return attach_blob(graph_input_index, handle, input_blobs_, true);
    }

    bstorm_result attach_output(unsigned graph_output_index, void* handle)
    {
        return attach_blob(graph_output_index, handle, output_blobs_, false);
    }

    bstorm_result detach_input(unsigned graph_input_index, void* handle)
    {
        return detach_blob(graph_input_index, handle, input_blobs_);
    }

    bstorm_result detach_output(unsigned graph_output_index, void* handle)
    {
        return detach_blob(graph_output_index, handle, output_blobs_);
    }

    bstorm_result invoke()
    {
        bstorm_result rc = BSTORM_RESULT_INITIALIZER();
        if (precompiled_graph_) {
            B_STORM_CHECKED_CALL(rc, precompiled_graph_->execute, (input_blobs_, output_blobs_), err_execute);
        } else {
            B_STORM_ASSERT(dispatch_graph_);
            B_STORM_CHECKED_CALL(rc, dispatch_graph_->execute_graph, (input_blobs_, output_blobs_), err_execute);
        }
        return rc;

    err_execute:
        return rc;
    }

    bstorm_result get_graph(LiteRtDispatchGraph* graph) {
        bstorm_result rc = BSTORM_RESULT_INITIALIZER();

        B_STORM_CONDITION(rc, dispatch_graph_, err_graph);
        B_STORM_ASSERT(graph);
        *graph = reinterpret_cast<LiteRtDispatchGraph>(dispatch_graph_.get());
        return rc;

    err_graph:
        *graph = nullptr;
        return rc;
    }

  private:
    bstorm_result attach_blob(unsigned index, void* handle, struct bstorm_Blobs& blobs, bool is_input)
    {
        bstorm_result rc = BSTORM_RESULT_INITIALIZER();
        LiteRtTensorBuffer tensor_buffer;
        struct bstorm_Blob* blob;

        B_STORM_PRECONDITION(rc, index < blobs.count, err_invalid_index);
        B_STORM_CHECKED_NULL_CALL(rc, tensor_buffer, device_context_->lookup_buffer, (handle), err_invalid_buffer);
        blob = blobs.entry[index];
        B_STORM_CHECKED_CALL(rc, bstorm_LiteRt_BlobFromTensorBuffer, (blob, tensor_buffer), err_blob);

        // If dispatch_graph_ is available, copy the blob shape and quantization parameters from the graph.
        // This is necessary because the quantization parameters are not available in the tensor_buffer.
        if (dispatch_graph_ != NULL) {
            B_STORM_CHECKED_CALL(rc, dispatch_graph_->copy_shape, (index, *blob, is_input), err_copy_shape);
        }

        return rc;

    err_copy_shape:
    err_blob:
    err_invalid_buffer:
    err_invalid_index:
        return rc;
    }

    static bstorm_result detach_blob(unsigned index, void* handle, struct bstorm_Blobs& blobs)
    {
        bstorm_result rc = BSTORM_RESULT_INITIALIZER();
        struct bstorm_Blob* blob;

        B_STORM_PRECONDITION(rc, index < blobs.count, err_invalid_index);
        blob = blobs.entry[index];
        bstorm_Blob_Default(blob);
        return rc;

    err_invalid_index:
        return rc;
    }

    bstorm_device_context* device_context_ = NULL;
    bool input_blobs_allocated_ = false;
    bool output_blobs_allocated_ = false;
    struct bstorm_Blobs input_blobs_;
    struct bstorm_Blobs output_blobs_;
    std::unique_ptr<bstorm_dispatch_graph> dispatch_graph_;
    std::unique_ptr<bstorm_dispatch_precompiled_graph> precompiled_graph_;
};

//==============================================================================
// LiteRT Type Aliases
//==============================================================================

class LiteRtDispatchDeviceContextT : public bstorm_device_context { };
class LiteRtDispatchInvocationContextT : public bstorm_invocation_context { };

//==============================================================================
// LiteRT API Implementation
//==============================================================================

static constexpr char kVendorId[] = BSTORM_VENDOR_ID;
static constexpr char kBuildId[] = "BstormDispatch_1.0";

static LiteRtStatus bstorm_LiteRt_initialize(
    const LiteRtRuntimeContext* runtime_context,
    LiteRtEnvironment environment, LiteRtOptions options)
{
    return kLiteRtStatusOk;
}

static LiteRtStatus bstorm_LiteRt_get_vendor_id(const char** vendor_id)
{
    *vendor_id = kVendorId;
    return kLiteRtStatusOk;
}

static LiteRtStatus bstorm_LiteRt_get_build_id(const char** build_id)
{
    *build_id = kBuildId;
    return kLiteRtStatusOk;
}

static LiteRtStatus bstorm_LiteRt_get_capabilities(int* capabilities)
{
    *capabilities = kLiteRtDispatchCapabilitiesBasic;
    return kLiteRtStatusOk;
}

static LiteRtStatus bstorm_LiteRt_device_context_create(
    const LiteRtRuntimeContext* runtime_context,
    LiteRtOptions options, LiteRtDispatchDeviceContext* device_context)
{
    bstorm_result rc = BSTORM_RESULT_INITIALIZER();
    *device_context = new LiteRtDispatchDeviceContextT();
    B_STORM_CHECKED_CALL(rc, (*device_context)->init, (), err_init);
    return kLiteRtStatusOk;
err_init:
    delete *device_context;
    return kLiteRtStatusErrorRuntimeFailure;
}

static LiteRtStatus bstorm_LiteRt_device_context_destroy(LiteRtDispatchDeviceContext device_context)
{
    delete device_context;
    return kLiteRtStatusOk;
}

static LiteRtStatus bstorm_LiteRt_get_tensor_buffer_requirements(
    const LiteRtRankedTensorType& tensor_type,
    LiteRtTensorBufferRequirements* tensor_buffer_requirements)
{
    litert::RankedTensorType t(tensor_type);
    static constexpr LiteRtTensorBufferType types[] = {
        kLiteRtTensorBufferTypeHostMemory
    };
    auto size_result = t.Bytes();
    if (!size_result) {
        return kLiteRtStatusErrorRuntimeFailure;
    }
    return LiteRtCreateTensorBufferRequirements(
        1, types, *size_result, 0, nullptr, tensor_buffer_requirements);
}

static LiteRtStatus bstorm_LiteRt_get_input_requirements(
    LiteRtDispatchInvocationContext invocation_context, int input_index,
    const LiteRtRankedTensorType* tensor_type,
    LiteRtTensorBufferRequirements* tensor_buffer_requirements)
{
    return bstorm_LiteRt_get_tensor_buffer_requirements(*tensor_type, tensor_buffer_requirements);
}

static LiteRtStatus bstorm_LiteRt_get_output_requirements(
    LiteRtDispatchInvocationContext invocation_context, int output_index,
    const LiteRtRankedTensorType* tensor_type,
    LiteRtTensorBufferRequirements* tensor_buffer_requirements)
{
    return bstorm_LiteRt_get_tensor_buffer_requirements(*tensor_type, tensor_buffer_requirements);
}

static LiteRtStatus bstorm_LiteRt_register_tensor_buffer(
    LiteRtDispatchDeviceContext device_context, LiteRtTensorBuffer buffer,
    LiteRtTensorBufferHandle* tensor_buffer_handle)
{
    bstorm_result rc = BSTORM_RESULT_INITIALIZER();
    void* handle = nullptr;
    B_STORM_CHECKED_CALL(rc, device_context->register_buffer, (buffer, &handle), err_register);
    *tensor_buffer_handle = reinterpret_cast<LiteRtTensorBufferHandle>(handle);
    return kLiteRtStatusOk;
err_register:
    return kLiteRtStatusErrorRuntimeFailure;
}

static LiteRtStatus bstorm_LiteRt_unregister_tensor_buffer(LiteRtDispatchDeviceContext device_context,
                                    LiteRtTensorBufferHandle handle)
{
    bstorm_result rc = BSTORM_RESULT_INITIALIZER();
    void* buffer_handle = reinterpret_cast<void*>(handle);
    B_STORM_CHECKED_CALL(rc, device_context->unregister_buffer, (buffer_handle), err_unregister);
    return kLiteRtStatusOk;
err_unregister:
    return kLiteRtStatusErrorRuntimeFailure;
}

static LiteRtStatus bstorm_LiteRt_invocation_context_create(
    const LiteRtRuntimeContext* runtime_context,
    LiteRtDispatchDeviceContext device_context,
    LiteRtDispatchExecutableType exec_type,
    const LiteRtMemBuffer* mem_buffer, const char* function_name,
    int num_inputs, int num_outputs,
    LiteRtDispatchInvocationContext* invocation_context)
{
    bstorm_result rc = BSTORM_RESULT_INITIALIZER();
    if (num_inputs < 0 || num_outputs < 0) {
        return kLiteRtStatusErrorInvalidArgument;
    }
    *invocation_context = new LiteRtDispatchInvocationContextT();
    B_STORM_CHECKED_CALL(rc, (*invocation_context)->init, (
        device_context, exec_type, mem_buffer, function_name,
        num_inputs, num_outputs), err_init);
    return kLiteRtStatusOk;
err_init:
    delete *invocation_context;
    return kLiteRtStatusErrorRuntimeFailure;
}

static LiteRtStatus bstorm_LiteRt_invocation_context_destroy(
    LiteRtDispatchInvocationContext invocation_context)
{
    delete invocation_context;
    return kLiteRtStatusOk;
}

static LiteRtStatus bstorm_LiteRt_attach_input(LiteRtDispatchInvocationContext invocation_context,
                         int graph_input_index,
                         LiteRtTensorBufferHandle tensor_buffer_handle)
{
    void* handle = reinterpret_cast<void*>(tensor_buffer_handle);
    bstorm_result rc = BSTORM_RESULT_INITIALIZER();
    if (graph_input_index < 0) {
        return kLiteRtStatusErrorInvalidArgument;
    }
    B_STORM_CHECKED_CALL(rc, invocation_context->attach_input, (graph_input_index, handle), err_attach_input);
    return kLiteRtStatusOk;
err_attach_input:
    return kLiteRtStatusErrorRuntimeFailure;
}

static LiteRtStatus bstorm_LiteRt_attach_output(LiteRtDispatchInvocationContext invocation_context,
                          int graph_output_index,
                          LiteRtTensorBufferHandle tensor_buffer_handle)
{
    void* handle = reinterpret_cast<void*>(tensor_buffer_handle);
    bstorm_result rc = BSTORM_RESULT_INITIALIZER();
    if (graph_output_index < 0) {
        return kLiteRtStatusErrorInvalidArgument;
    }
    B_STORM_CHECKED_CALL(rc, invocation_context->attach_output, (graph_output_index, handle), err_attach_output);
    return kLiteRtStatusOk;
err_attach_output:
    return kLiteRtStatusErrorRuntimeFailure;
}

static LiteRtStatus bstorm_LiteRt_detach_input(LiteRtDispatchInvocationContext invocation_context,
                         int graph_input_index,
                         LiteRtTensorBufferHandle tensor_buffer_handle)
{
    void* handle = reinterpret_cast<void*>(tensor_buffer_handle);
    bstorm_result rc = BSTORM_RESULT_INITIALIZER();
    if (graph_input_index < 0) {
        return kLiteRtStatusErrorInvalidArgument;
    }
    B_STORM_CHECKED_CALL(rc, invocation_context->detach_input, (graph_input_index, handle), err_detach_input);
    return kLiteRtStatusOk;
err_detach_input:
    return kLiteRtStatusErrorRuntimeFailure;
}

static LiteRtStatus bstorm_LiteRt_detach_output(LiteRtDispatchInvocationContext invocation_context,
                          int graph_output_index,
                          LiteRtTensorBufferHandle tensor_buffer_handle)
{
    void* handle = reinterpret_cast<void*>(tensor_buffer_handle);
    bstorm_result rc = BSTORM_RESULT_INITIALIZER();
    if (graph_output_index < 0) {
        return kLiteRtStatusErrorInvalidArgument;
    }
    B_STORM_CHECKED_CALL(rc, invocation_context->detach_output, (graph_output_index, handle), err_detach_output);
    return kLiteRtStatusOk;
err_detach_output:
    return kLiteRtStatusErrorRuntimeFailure;
}

static LiteRtStatus bstorm_LiteRt_invoke(LiteRtDispatchInvocationContext invocation_context)
{
    bstorm_result rc = BSTORM_RESULT_INITIALIZER();
    B_STORM_CHECKED_CALL(rc, invocation_context->invoke, (), err_invoke);
    return kLiteRtStatusOk;
err_invoke:
    return kLiteRtStatusErrorRuntimeFailure;
}

static LiteRtStatus bstorm_LiteRt_invocation_context_set_scheduling_info(
    LiteRtDispatchInvocationContext invocation_context,
    const LiteRtSchedulingInfo* scheduling_info)
{
    return kLiteRtStatusOk;
}

static LiteRtStatus bstorm_LiteRt_check_runtime_compatibility(
    LiteRtApiVersion api_version, LiteRtEnvironmentOptions env,
    LiteRtOptions options)
{
    return kLiteRtStatusOk;
}

static LiteRtStatus bstorm_LiteRt_invocation_context_set_options(
    LiteRtDispatchInvocationContext invocation_context, LiteRtOptions options)
{
    return kLiteRtStatusOk;
}

static LiteRtStatus bstorm_LiteRt_invocation_context_get_graph(
    LiteRtDispatchInvocationContext invocation_context,
    LiteRtDispatchGraph* graph)
{
    bstorm_result rc = BSTORM_RESULT_INITIALIZER();
    B_STORM_CHECKED_CALL(rc, invocation_context->get_graph, (graph), err_get);
    return kLiteRtStatusOk;

err_get:
    return kLiteRtStatusErrorRuntimeFailure;
}

// Dispatch interface structure
static LiteRtDispatchInterface bstorm_LiteRt_dispatch_interface = {
    /*.initialize=*/bstorm_LiteRt_initialize,
    /*.get_vendor_id=*/bstorm_LiteRt_get_vendor_id,
    /*.get_build_id=*/bstorm_LiteRt_get_build_id,
    /*.get_capabilities=*/bstorm_LiteRt_get_capabilities,
    /*.device_context_create=*/bstorm_LiteRt_device_context_create,
    /*.device_context_destroy=*/bstorm_LiteRt_device_context_destroy,
    /*.get_input_requirements=*/bstorm_LiteRt_get_input_requirements,
    /*.get_output_requirements=*/bstorm_LiteRt_get_output_requirements,
    /*.register_tensor_buffer=*/bstorm_LiteRt_register_tensor_buffer,
    /*.unregister_tensor_buffer=*/bstorm_LiteRt_unregister_tensor_buffer,
    /*.invocation_context_create=*/bstorm_LiteRt_invocation_context_create,
    /*.invocation_context_destroy=*/bstorm_LiteRt_invocation_context_destroy,
    /*.invocation_context_set_scheduling_info=*/bstorm_LiteRt_invocation_context_set_scheduling_info,
    /*.attach_input=*/bstorm_LiteRt_attach_input,
    /*.attach_output=*/bstorm_LiteRt_attach_output,
    /*.detach_input=*/bstorm_LiteRt_detach_input,
    /*.detach_output=*/bstorm_LiteRt_detach_output,
    /*.invoke=*/bstorm_LiteRt_invoke,
    /*.start_metrics_collection=*/nullptr,
    /*.stop_metrics_collection=*/nullptr,
    /*.get_num_metrics=*/nullptr,
    /*.get_metric=*/nullptr,
    /*.destroy_metrics=*/nullptr,
    /*.check_runtime_compatibility=*/bstorm_LiteRt_check_runtime_compatibility,
    /*.invocation_context_set_options=*/bstorm_LiteRt_invocation_context_set_options,
};

static LiteRtDispatchGraphInterface bstorm_LiteRt_graph_interface = {
    /*.graph_create=*/nullptr,
    /*.graph_destroy=*/nullptr,
    /*.add_node=*/nullptr,
    /*.add_edge=*/nullptr,
    /*.connect_node_input=*/nullptr,
    /*.connect_node_output=*/nullptr,
    /*.connect_graph_input=*/nullptr,
    /*.connect_graph_output=*/nullptr,
    /*.load_executable=*/nullptr,
    /*.unload_executable=*/nullptr,
    /*.assign_node_function=*/nullptr,
    /*.annotate_graph=*/nullptr,
    /*.annotate_node=*/nullptr,
    /*.annotate_edge=*/nullptr,
    /*.invocation_context_create_from_graph=*/nullptr,
    /*.invocation_context_get_graph=*/bstorm_LiteRt_invocation_context_get_graph,
};

static LiteRtDispatchApi bstorm_LiteRt_dispatch_api = {
    /*.version=*/{/*.major=*/LITERT_API_VERSION_MAJOR,
                  /*.minor=*/LITERT_API_VERSION_MINOR,
                  /*.patch=*/LITERT_API_VERSION_PATCH},
    /*.interface=*/&bstorm_LiteRt_dispatch_interface,
    /*.async_interface=*/nullptr,
    /*.graph_interface=*/&bstorm_LiteRt_graph_interface,
};

// Export the main API function
LiteRtStatus LiteRtDispatchGetApi(LiteRtDispatchApi* api) {
    *api = bstorm_LiteRt_dispatch_api;
    return kLiteRtStatusOk;
}
