#!/usr/bin/env python3
# Copyright 2025 Google LLC.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

import sys


def main():
  if len(sys.argv) < 4:
    print(
        'Usage: generate_registry.py <output_cc> <output_h> <cpu_accel1>'
        ' <cpu_accel2> ... --gpu <gpu_accel1> ...'
    )
    sys.exit(1)

  output_cc = sys.argv[1]
  output_h = sys.argv[2]
  cpu_accels = []
  gpu_accels = []

  current_list = cpu_accels
  for arg in sys.argv[3:]:
    if arg == '--gpu':
      current_list = gpu_accels
      continue
    current_list.append(arg)

  # Generate Header File
  with open(output_h, 'w') as f:
    f.write('// Auto-generated by generate_registry.py. DO NOT EDIT.\n')
    f.write(
        '#ifndef'
        ' THIRD_PARTY_ODML_LITERT_LITERT_RUNTIME_ACCELERATORS_BUILTIN_ACCELERATORS_H_\n'
    )
    f.write(
        '#define'
        ' THIRD_PARTY_ODML_LITERT_LITERT_RUNTIME_ACCELERATORS_BUILTIN_ACCELERATORS_H_\n\n'
    )
    f.write('#include <cstddef>\n\n')
    f.write(
        '#include'
        ' "third_party/odml/litert/litert/c/internal/litert_accelerator_def.h"\n\n'
    )
    f.write('namespace litert::internal {\n\n')
    f.write('const LiteRtAcceleratorDef* const* GetBuiltinCpuAccelerators();\n')
    f.write('size_t GetBuiltinCpuAcceleratorsSize();\n\n')
    f.write('const LiteRtAcceleratorDef* const* GetBuiltinGpuAccelerators();\n')
    f.write('size_t GetBuiltinGpuAcceleratorsSize();\n\n')
    f.write('}  // namespace litert::internal\n\n')
    f.write(
        '#endif  //'
        ' THIRD_PARTY_ODML_LITERT_LITERT_RUNTIME_ACCELERATORS_BUILTIN_ACCELERATORS_H_\n'
    )

  # Generate Source File
  with open(output_cc, 'w') as f:
    f.write('// Auto-generated by generate_registry.py. DO NOT EDIT.\n')
    f.write(
        '#include'
        ' "third_party/odml/litert/litert/runtime/accelerators/builtin_accelerators.h"\n\n'
    )
    f.write('#include <cstddef>\n')
    f.write(
        '#include'
        ' "third_party/odml/litert/litert/c/internal/litert_accelerator_def.h"\n\n'
    )

    f.write('#if defined(_WIN32)\n')
    f.write('#include <windows.h>\n')
    f.write('#elif defined(__APPLE__)\n')
    f.write('#include <dlfcn.h>\n')
    f.write('#endif\n\n')

    f.write('extern "C" {\n')
    f.write('#if !defined(_WIN32) && !defined(__APPLE__)\n')
    f.write('#define LITERT_WEAK __attribute__((weak))\n')
    for accel in cpu_accels + gpu_accels:
      f.write(f'extern const LiteRtAcceleratorDef {accel}Impl LITERT_WEAK;\n')
    f.write('#endif\n')
    f.write('}  // extern "C"\n\n')

    f.write('namespace litert::internal {\n\n')

    f.write('namespace {\n')
    f.write('#if defined(_WIN32)\n')
    f.write('const LiteRtAcceleratorDef* ResolveSymbol(const char* name) {\n')
    f.write('  HMODULE module = GetModuleHandle(NULL);\n')
    f.write('  if (module == NULL) return nullptr;\n')
    f.write(
        '  return reinterpret_cast<const'
        ' LiteRtAcceleratorDef*>(GetProcAddress(module, name));\n'
    )
    f.write('}\n')
    f.write('#elif defined(__APPLE__)\n')
    f.write('const LiteRtAcceleratorDef* ResolveSymbol(const char* name) {\n')
    f.write(
        '  return reinterpret_cast<const'
        ' LiteRtAcceleratorDef*>(dlsym(RTLD_DEFAULT, name));\n'
    )
    f.write('}\n')
    f.write('#else\n')
    f.write(
        'const LiteRtAcceleratorDef* GetIfDefined(const LiteRtAcceleratorDef*'
        ' def) {\n'
    )
    f.write('  void* volatile addr = (void*)def;\n')
    f.write('  return reinterpret_cast<const LiteRtAcceleratorDef*>(addr);\n')
    f.write('}\n')
    f.write('#endif\n')
    f.write('}  // namespace\n\n')

    f.write(
        'const LiteRtAcceleratorDef* const* GetBuiltinCpuAccelerators() {\n'
    )
    f.write('  static const LiteRtAcceleratorDef* kCpuAccelerators[] = {\n')
    for accel in cpu_accels:
      f.write('#if defined(_WIN32) || defined(__APPLE__)\n')
      f.write(f'      ResolveSymbol("{accel}Impl"),\n')
      f.write('#else\n')
      f.write(f'      GetIfDefined(&{accel}Impl),\n')
      f.write('#endif\n')
    f.write('  };\n')
    f.write('  return kCpuAccelerators;\n')
    f.write('}\n\n')

    f.write('size_t GetBuiltinCpuAcceleratorsSize() {\n')
    f.write(f'  return {len(cpu_accels)};\n')
    f.write('}\n\n')

    f.write(
        'const LiteRtAcceleratorDef* const* GetBuiltinGpuAccelerators() {\n'
    )
    f.write('  static const LiteRtAcceleratorDef* kGpuAccelerators[] = {\n')
    for accel in gpu_accels:
      f.write('#if defined(_WIN32) || defined(__APPLE__)\n')
      f.write(f'      ResolveSymbol("{accel}Impl"),\n')
      f.write('#else\n')
      f.write(f'      GetIfDefined(&{accel}Impl),\n')
      f.write('#endif\n')
    f.write('  };\n')
    f.write('  return kGpuAccelerators;\n')
    f.write('}\n\n')

    f.write('size_t GetBuiltinGpuAcceleratorsSize() {\n')
    f.write(f'  return {len(gpu_accels)};\n')
    f.write('}\n\n')

    f.write('}  // namespace litert::internal\n')


if __name__ == '__main__':
  main()
