/******************************************************************************
 * Copyright (C) 2025 Broadcom.
 * The term "Broadcom" refers to Broadcom Inc. and/or its subsidiaries.
 *
 * This program is the proprietary software of Broadcom and/or its licensors,
 * and may only be used, duplicated, modified or distributed pursuant to
 * the terms and conditions of a separate, written license agreement executed
 * between you and Broadcom (an "Authorized License").  Except as set forth in
 * an Authorized License, Broadcom grants no license (express or implied),
 * right to use, or waiver of any kind with respect to the Software, and
 * Broadcom expressly reserves all rights in and to the Software and all
 * intellectual property rights therein. IF YOU HAVE NO AUTHORIZED LICENSE,
 * THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 * IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.
 *
 * Except as expressly set forth in the Authorized License,
 *
 * 1.     This program, including its structure, sequence and organization,
 * constitutes the valuable trade secrets of Broadcom, and you shall use all
 * reasonable efforts to protect the confidentiality thereof, and to use this
 * information only in connection with your use of Broadcom integrated circuit
 * products.
 *
 * 2.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED
 * "AS IS" AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS
 * OR WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH
 * RESPECT TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL
 * IMPLIED WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR
 * A PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS, QUIET
 * ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION. YOU ASSUME
 * THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE SOFTWARE.
 *
 * 3.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM
 * OR ITS LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL,
 * INDIRECT, OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY
 * RELATING TO YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM
 * HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN
 * EXCESS OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1,
 * WHICHEVER IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY
 * FAILURE OF ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
 ******************************************************************************/
/* Portions generated by GENAI: Cursor 2.2.36 (IDE), Claude Sonnet 4.5 */

/* #define BSTORM_DEBUG_LEVEL_VERBOSE 1 */
#include "bstorm_core_internal.h"
#include "bstorm_compiler_graph.h"

#include "bstorm_common.h"
#include "bstorm_operations.h"
#include "bstorm_types.h"

#include "litert/c/litert_model.h"
#include "litert/c/litert_op_options.h"
#include "litert/cc/internal/litert_op_options.h"
#include "common/bstorm_util_litert.h"

#include <vector>

using namespace litert;

static void bstorm_LiteRt_free_shapes(const struct bstorm_Blobs &blobs)
{
    for (unsigned i=0;i<blobs.count;i++) {
        bstorm_Blob *blob = blobs.entry[i];
        if (blob) {
            bstorm_BlobShape_Free(&blob->shape);
        }
    }
    return;
}

static bstorm_result bstorm_LiteRt_convert_activation(
    LiteRtOp op,
    enum bstorm_ActivationFunctionType &activation,
    LiteRtStatus (*get_activation_func)(LiteRtOp, ActivationFunction*))
{
    bstorm_result rc = BSTORM_RESULT_INITIALIZER();
    ActivationFunction fused_activation;

    B_STORM_CHECKED_LITERT_CALL(rc, get_activation_func, (op, &fused_activation), err_convert);
    switch (fused_activation) {
        case kActivationFunctionTypeNone:
            activation = bstorm_ActivationFunctionType_None;
            break;
        case kActivationFunctionTypeRelu:
            activation = bstorm_ActivationFunctionType_Relu;
            break;
        case kActivationFunctionTypeReluN1To1:
            activation = bstorm_ActivationFunctionType_Relu1;
            break;
        case kActivationFunctionTypeRelu6:
            activation = bstorm_ActivationFunctionType_Relu6;
            break;
        default:
            B_STORM_ERROR_VERBOSE(rc, NotSupported, err_convert,
                "Not supported activation:%u",fused_activation);
    }
    return rc;

err_convert:
    return rc;
}

static bstorm_result bstorm_LiteRt_convert_padding(
    LiteRtOp op,
    bstorm_Padding &padding,
    LiteRtStatus (*get_padding_func)(LiteRtOp, uint32_t*))
{
    bstorm_result rc = BSTORM_RESULT_INITIALIZER();
    uint32_t tf_padding;

    B_STORM_CHECKED_LITERT_CALL(rc, get_padding_func, (op, &tf_padding), err_convert);

    switch((PaddingType)tf_padding) {
        case kPaddingSame: padding.type = bstorm_PaddingType_Same; break;
        case kPaddingValid: padding.type = bstorm_PaddingType_Valid; break;
        default:
            B_STORM_ERROR_VERBOSE(rc, NotSupported, err_convert, "Not supported padding:%u", tf_padding);
    }
    return rc;

err_convert:
    return rc;
}

static bstorm_result bstorm_LiteRt_convert_2D(
    LiteRtOp op,
    bstorm_2D &_2d,
    LiteRtStatus (*get_width_func)(LiteRtOp, int32_t*),
    LiteRtStatus (*get_height_func)(LiteRtOp, int32_t*))
{
    bstorm_result rc = BSTORM_RESULT_INITIALIZER();
    int32_t width, height;

    B_STORM_CHECKED_LITERT_CALL(rc, get_width_func, (op, &width), err_convert);
    B_STORM_CHECKED_LITERT_CALL(rc, get_height_func, (op, &height), err_convert);
    B_STORM_PRECONDITION(rc, width >= 0, err_convert);
    B_STORM_PRECONDITION(rc, height >= 0, err_convert);
    _2d.width = width;
    _2d.height = height;
    return rc;

err_convert:
    return rc;
}

static bstorm_result bstorm_LiteRt_convert_3D(
    LiteRtOp op,
    bstorm_3D &_3d,
    LiteRtStatus (*get_width_func)(LiteRtOp, int32_t*),
    LiteRtStatus (*get_height_func)(LiteRtOp, int32_t*),
    LiteRtStatus (*get_depth_func)(LiteRtOp, int32_t*))
{
    bstorm_result rc = BSTORM_RESULT_INITIALIZER();
    int32_t width, height, depth;

    B_STORM_CHECKED_LITERT_CALL(rc, get_width_func, (op, &width), err_convert);
    B_STORM_CHECKED_LITERT_CALL(rc, get_height_func, (op, &height), err_convert);
    B_STORM_CHECKED_LITERT_CALL(rc, get_depth_func, (op, &depth), err_convert);
    B_STORM_PRECONDITION(rc, width >= 0, err_convert);
    B_STORM_PRECONDITION(rc, height >= 0, err_convert);
    B_STORM_PRECONDITION(rc, depth >= 0, err_convert);
    _3d.width = width;
    _3d.height = height;
    _3d.depth = depth;
    return rc;

err_convert:
    return rc;
}

static bstorm_result bstorm_LiteRt_convert_ReducerConfig(
    LiteRtOp op,
    struct bstorm_ReducerConfig &config,
    LiteRtStatus (*get_keep_dims_func)(LiteRtOp, bool*))
{
    bstorm_result rc = BSTORM_RESULT_INITIALIZER();
    B_STORM_CHECKED_LITERT_CALL(rc, get_keep_dims_func, (op, &config.keep_dims), err_convert);
    return rc;

err_convert:
    return rc;
}

static bstorm_result bstorm_LiteRt_convert_Add(
    struct bstorm_AddConfig &config, LiteRtOp op)
{
    bstorm_result rc = BSTORM_RESULT_INITIALIZER();
    B_STORM_CHECKED_CALL(rc, bstorm_LiteRt_convert_activation, (op, config.activation, LiteRtGetAddFusedActivationOption), err_convert);
    return rc;

err_convert:
    return rc;
}

static bstorm_result bstorm_LiteRt_convert_ArgMax(
    struct bstorm_ArgMaxConfig &config, LiteRtOp op)
{
    bstorm_result rc = BSTORM_RESULT_INITIALIZER();
    LiteRtTensor output_tensor;
    LiteRtRankedTensorType output_type;

    // Get the output tensor to determine the output data type
    B_STORM_CHECKED_LITERT_CALL(rc, LiteRtGetOpOutput, (op, 0, &output_tensor), err_convert);
    B_STORM_CHECKED_LITERT_CALL(rc, LiteRtGetRankedTensorType, (output_tensor, &output_type), err_convert);
    B_STORM_CHECKED_CALL(rc, bstorm_LiteRt_convert_datatype, (output_type.element_type,config.outputType), err_convert);
    return rc;

err_convert:
    return rc;
}

static bstorm_result bstorm_LiteRt_convert_AveragePool2D(
    struct bstorm_AveragePool2DConfig &config, LiteRtOp op)
{
    bstorm_result rc = BSTORM_RESULT_INITIALIZER();
    B_STORM_CHECKED_CALL(rc, bstorm_LiteRt_convert_activation, (op, config.common.activation, LiteRtGetAveragePool2dFusedActivationOption), err_convert);
    B_STORM_CHECKED_CALL(rc, bstorm_LiteRt_convert_padding, (op, config.common.padding, LiteRtGetAveragePool2dPaddingOption), err_convert);
    B_STORM_CHECKED_CALL(rc, bstorm_LiteRt_convert_2D, (op, config.common.stride, LiteRtGetAveragePool2dStrideWOption, LiteRtGetAveragePool2dStrideHOption), err_convert);
    B_STORM_CHECKED_CALL(rc, bstorm_LiteRt_convert_2D, (op, config.common.filter, LiteRtGetAveragePool2dFilterWidthOption, LiteRtGetAveragePool2dFilterHeightOption), err_convert);
    return rc;

err_convert:
    return rc;
}

static bstorm_result bstorm_LiteRt_convert_BatchMatMul(
    struct bstorm_BatchMatMulConfig &config, LiteRtOp op)
{
    bstorm_result rc = BSTORM_RESULT_INITIALIZER();
    B_STORM_CHECKED_LITERT_CALL(rc, LiteRtGetBatchMatmulAdjXOption, (op, &config.adj_x), err_convert);
    B_STORM_CHECKED_LITERT_CALL(rc, LiteRtGetBatchMatmulAdjYOption, (op, &config.adj_y), err_convert);
    B_STORM_CHECKED_LITERT_CALL(rc, LiteRtGetBatchMatmulAsymmetricQuantizeInputOption, (op, &config.asymmetric_quantize_inputs), err_convert);
    return rc;

err_convert:
    return rc;
}

static bstorm_result bstorm_LiteRt_convert_Concatenate(
    struct bstorm_ConcatenateConfig &config, LiteRtOp op)
{
    bstorm_result rc = BSTORM_RESULT_INITIALIZER();
    B_STORM_CHECKED_CALL(rc, bstorm_LiteRt_convert_activation, (op, config.activation, LiteRtGetConcatenationFusedActivationOption), err_convert);
    B_STORM_CHECKED_LITERT_CALL(rc, LiteRtGetConcatenationAxisOption, (op, &config.axis), err_convert);
    return rc;

err_convert:
    return rc;
}

static bstorm_result bstorm_LiteRt_convert_Conv2D(
    struct bstorm_Conv2DConfig &config, LiteRtOp op)
{
    bstorm_result rc = BSTORM_RESULT_INITIALIZER();
    B_STORM_CHECKED_CALL(rc, bstorm_LiteRt_convert_activation, (op, config.activation, LiteRtGetConv2dFusedActivationOption), err_convert);
    B_STORM_CHECKED_CALL(rc, bstorm_LiteRt_convert_padding, (op, config.padding, LiteRtGetConv2dPaddingOption), err_convert);
    B_STORM_CHECKED_CALL(rc, bstorm_LiteRt_convert_2D, (op, config.stride, LiteRtGetConv2dStrideWOption, LiteRtGetConv2dStrideHOption), err_convert);
    B_STORM_CHECKED_CALL(rc, bstorm_LiteRt_convert_2D, (op, config.dilation_factor, LiteRtGetConv2dDilationWOption, LiteRtGetConv2dDilationHOption), err_convert);
    return rc;

err_convert:
    return rc;
}

static bstorm_result bstorm_LiteRt_convert_Conv3D(
    struct bstorm_Conv3DConfig &config, LiteRtOp op)
{
    bstorm_result rc = BSTORM_RESULT_INITIALIZER();
    B_STORM_CHECKED_CALL(rc, bstorm_LiteRt_convert_activation, (op, config.common.activation, LiteRtGetConv3dFusedActivationOption), err_convert);
    B_STORM_CHECKED_CALL(rc, bstorm_LiteRt_convert_padding, (op, config.common.padding, LiteRtGetConv3dPaddingOption), err_convert);
    B_STORM_CHECKED_CALL(rc, bstorm_LiteRt_convert_3D, (op, config.common.stride,
        LiteRtGetConv3dStrideWOption, LiteRtGetConv3dStrideHOption, LiteRtGetConv3dStrideDOption), err_convert);
    B_STORM_CHECKED_CALL(rc, bstorm_LiteRt_convert_3D, (op, config.common.dilation_factor,
        LiteRtGetConv3dDilationWOption, LiteRtGetConv3dDilationHOption, LiteRtGetConv3dDilationDOption), err_convert);
    config.common.dataLayout = bstorm_DataLayoutType_NDHWC;
    return rc;

err_convert:
    return rc;
}

static bstorm_result bstorm_LiteRt_convert_Cumsum(
    struct bstorm_CumsumConfig &config, LiteRtOp op)
{
    bstorm_result rc = BSTORM_RESULT_INITIALIZER();
    B_STORM_CHECKED_LITERT_CALL(rc, LiteRtGetCumsumExclusiveOption, (op, &config.exclusive), err_convert);
    B_STORM_CHECKED_LITERT_CALL(rc, LiteRtGetCumsumReverseOption, (op, &config.reverse), err_convert);
    return rc;

err_convert:
    return rc;
}

static bstorm_result bstorm_LiteRt_convert_DepthToSpace(
    struct bstorm_DepthToSpaceConfig &config, LiteRtOp op)
{
    bstorm_result rc = BSTORM_RESULT_INITIALIZER();
    int32_t block_size;
    B_STORM_CHECKED_LITERT_CALL(rc, LiteRtGetDepthToSpaceBlockSizeOption, (op, &block_size), err_convert);
    B_STORM_PRECONDITION(rc, block_size > 0, err_convert);
    config.block_size = block_size;
    return rc;

err_convert:
    return rc;
}

static bstorm_result bstorm_LiteRt_convert_DepthWiseConv2D(
    struct bstorm_DepthWiseConv2DConfig &config, LiteRtOp op)
{
    bstorm_result rc = BSTORM_RESULT_INITIALIZER();
    int32_t depth_multiplier;

    B_STORM_CHECKED_CALL(rc, bstorm_LiteRt_convert_activation, (op, config.activation, LiteRtGetDepthwiseConv2dFusedActivationOption), err_convert);
    B_STORM_CHECKED_CALL(rc, bstorm_LiteRt_convert_padding, (op, config.padding, LiteRtGetDepthwiseConv2dPaddingOption), err_convert);
    B_STORM_CHECKED_CALL(rc, bstorm_LiteRt_convert_2D, (op, config.stride, LiteRtGetDepthwiseConv2dStrideWOption, LiteRtGetDepthwiseConv2dStrideHOption), err_convert);
    B_STORM_CHECKED_CALL(rc, bstorm_LiteRt_convert_2D, (op, config.dilation_factor, LiteRtGetDepthwiseConv2dDilationWOption, LiteRtGetDepthwiseConv2dDilationHOption), err_convert);
    B_STORM_CHECKED_LITERT_CALL(rc, LiteRtGetDepthwiseConv2dDepthMultiplierOption, (op, &depth_multiplier), err_convert);
    config.depth_multiplier = depth_multiplier;
    return rc;

err_convert:
    return rc;
}

static bstorm_result bstorm_LiteRt_convert_Div(
    struct bstorm_DivConfig &config, LiteRtOp op)
{
    bstorm_result rc = BSTORM_RESULT_INITIALIZER();
    B_STORM_CHECKED_CALL(rc, bstorm_LiteRt_convert_activation, (op, config.activation, LiteRtGetDivFusedActivationOption), err_convert);
    return rc;

err_convert:
    return rc;
}

static bstorm_result bstorm_LiteRt_convert_FullyConnected(
    struct bstorm_FullyConnectedConfig &config, LiteRtOp op)
{
    bstorm_result rc = BSTORM_RESULT_INITIALIZER();
    B_STORM_CHECKED_CALL(rc, bstorm_LiteRt_convert_activation, (op, config.activation, LiteRtGetFullyConnectedFusedActivationOption), err_convert);
    B_STORM_CHECKED_LITERT_CALL(rc, LiteRtGetFullyConnectedKeepNumDimsOption, (op, &config.keep_num_dims), err_convert);
    return rc;

err_convert:
    return rc;
}

static bstorm_result bstorm_LiteRt_convert_Gather(
    struct bstorm_GatherConfig &config, LiteRtOp op)
{
    bstorm_result rc = BSTORM_RESULT_INITIALIZER();
    B_STORM_CHECKED_LITERT_CALL(rc, LiteRtGetGatherAxisOption, (op, &config.axis), err_convert);
    return rc;

err_convert:
    return rc;
}

static bstorm_result bstorm_LiteRt_convert_Gelu(
    struct bstorm_GeluConfig &config, LiteRtOp op)
{
    bstorm_result rc = BSTORM_RESULT_INITIALIZER();
    B_STORM_CHECKED_LITERT_CALL(rc, LiteRtGetGeluApproximateOption, (op, &config.approximate), err_convert);
    return rc;

err_convert:
    return rc;
}

static bstorm_result bstorm_LiteRt_convert_LeakyRelu(
    struct bstorm_LeakyReluConfig &config, LiteRtOp op)
{
    bstorm_result rc = BSTORM_RESULT_INITIALIZER();
    B_STORM_CHECKED_LITERT_CALL(rc, LiteRtGetLeakyReluAlphaOption, (op, &config.alpha), err_convert);
    return rc;

err_convert:
    return rc;
}

static bstorm_result bstorm_LiteRt_convert_MaxPool2D(
    struct bstorm_MaxPool2DConfig &config, LiteRtOp op)
{
    bstorm_result rc = BSTORM_RESULT_INITIALIZER();
    B_STORM_CHECKED_CALL(rc, bstorm_LiteRt_convert_activation, (op, config.common.activation, LiteRtGetMaxPool2dFusedActivationOption), err_convert);
    B_STORM_CHECKED_CALL(rc, bstorm_LiteRt_convert_padding, (op, config.common.padding, LiteRtGetMaxPool2dPaddingOption), err_convert);
    B_STORM_CHECKED_CALL(rc, bstorm_LiteRt_convert_2D, (op, config.common.stride, LiteRtGetMaxPool2dStrideWOption, LiteRtGetMaxPool2dStrideHOption), err_convert);
    B_STORM_CHECKED_CALL(rc, bstorm_LiteRt_convert_2D, (op, config.common.filter, LiteRtGetMaxPool2dFilterWidthOption, LiteRtGetMaxPool2dFilterHeightOption), err_convert);
    return rc;

err_convert:
    return rc;
}

static bstorm_result bstorm_LiteRt_convert_Mean(
    struct bstorm_MeanConfig &config, LiteRtOp op)
{
    bstorm_result rc = BSTORM_RESULT_INITIALIZER();
    B_STORM_CHECKED_CALL(rc, bstorm_LiteRt_convert_ReducerConfig, (op, config.reducer, LiteRtGetMeanKeepDimsOption), err_convert);
    return rc;

err_convert:
    return rc;
}

static bstorm_result bstorm_LiteRt_convert_MirrorPad(
    struct bstorm_MirrorPadConfig &config, LiteRtOp op)
{
    bstorm_result rc = BSTORM_RESULT_INITIALIZER();
    uint32_t mode;

    B_STORM_CHECKED_LITERT_CALL(rc, LiteRtGetMirrorPadModeOption, (op, &mode), err_convert);
    switch((MirrorPadModeType)mode) {
        case kMirrorPadModeReflect:
            config.mode = bstorm_MirrorPaddingType_Reflect;
            break;
        case kMirrorPadModeSymmetric:
            config.mode = bstorm_MirrorPaddingType_Symmetric;
            break;
        default:
            B_STORM_ERROR_VERBOSE(rc, NotSupported, err_convert, "Unsupported MirrorPad mode:%u", mode);
    }
    return rc;

err_convert:
    return rc;
}

static bstorm_result bstorm_LiteRt_convert_Mul(
    struct bstorm_MulConfig &config, LiteRtOp op)
{
    bstorm_result rc = BSTORM_RESULT_INITIALIZER();
    B_STORM_CHECKED_CALL(rc, bstorm_LiteRt_convert_activation, (op, config.activation, LiteRtGetMulFusedActivationOption), err_convert);
    return rc;

err_convert:
    return rc;
}

static bstorm_result bstorm_LiteRt_convert_Pack(
    struct bstorm_PackConfig &config, LiteRtOp op)
{
    bstorm_result rc = BSTORM_RESULT_INITIALIZER();
    int32_t values_count;
    B_STORM_CHECKED_LITERT_CALL(rc, LiteRtGetPackAxisOption, (op, &config.axis), err_convert);
    B_STORM_CHECKED_LITERT_CALL(rc, LiteRtGetPackValuesCountOption, (op, &values_count), err_convert);
    B_STORM_PRECONDITION(rc, values_count >= 0, err_convert);
    config.values_count = values_count;
    return rc;

err_convert:
    return rc;
}

static bstorm_result bstorm_LiteRt_convert_ReduceAll(
    struct bstorm_ReduceAllConfig &config, LiteRtOp op)
{
    bstorm_result rc = BSTORM_RESULT_INITIALIZER();
    B_STORM_CHECKED_CALL(rc, bstorm_LiteRt_convert_ReducerConfig, (op, config.reducer, LiteRtGetReduceAllKeepDimsOption), err_convert);
    return rc;

err_convert:
    return rc;
}

static bstorm_result bstorm_LiteRt_convert_ReduceMax(
    struct bstorm_ReduceMaxConfig &config, LiteRtOp op)
{
    bstorm_result rc = BSTORM_RESULT_INITIALIZER();
    B_STORM_CHECKED_CALL(rc, bstorm_LiteRt_convert_ReducerConfig, (op, config.reducer, LiteRtGetReduceMaxKeepDimsOption), err_convert);
    return rc;

err_convert:
    return rc;
}

static bstorm_result bstorm_LiteRt_convert_ReduceMin(
    struct bstorm_ReduceMinConfig &config, LiteRtOp op)
{
    bstorm_result rc = BSTORM_RESULT_INITIALIZER();
    B_STORM_CHECKED_CALL(rc, bstorm_LiteRt_convert_ReducerConfig, (op, config.reducer, LiteRtGetReduceMinKeepDimsOption), err_convert);
    return rc;

err_convert:
    return rc;
}

static bstorm_result bstorm_LiteRt_convert_ReduceAny(
    struct bstorm_ReduceAnyConfig &config, LiteRtOp op)
{
    bstorm_result rc = BSTORM_RESULT_INITIALIZER();
    B_STORM_CHECKED_CALL(rc, bstorm_LiteRt_convert_ReducerConfig, (op, config.reducer, LiteRtGetReduceAnyKeepDimsOption), err_convert);
    return rc;

err_convert:
    return rc;
}

static bstorm_result bstorm_LiteRt_convert_ResizeBilinear(
    struct bstorm_ResizeBilinearConfig &config, LiteRtOp op)
{
    bstorm_result rc = BSTORM_RESULT_INITIALIZER();
    B_STORM_CHECKED_LITERT_CALL(rc, LiteRtGetResizeBilinearAlignCornersOption, (op, &config.resize_config.align_corners), err_convert);
    B_STORM_CHECKED_LITERT_CALL(rc, LiteRtGetResizeBilinearHalfPixelCenterOption, (op, &config.resize_config.half_pixel_centers), err_convert);
    return rc;

err_convert:
    return rc;
}

static bstorm_result bstorm_LiteRt_convert_ResizeNearestNeighbor(
    struct bstorm_ResizeNearestNeighborConfig &config, LiteRtOp op)
{
    bstorm_result rc = BSTORM_RESULT_INITIALIZER();
    B_STORM_CHECKED_LITERT_CALL(rc, LiteRtGetResizeNearestNeighborAlignCornersOption, (op, &config.resize_config.align_corners), err_convert);
    B_STORM_CHECKED_LITERT_CALL(rc, LiteRtGetResizeNearestNeighborHalfPixelCenterOption, (op, &config.resize_config.half_pixel_centers), err_convert);
    return rc;

err_convert:
    return rc;
}

static bstorm_result bstorm_LiteRt_convert_SoftMax(
    struct bstorm_SoftMaxConfig &config, LiteRtOp op)
{
    bstorm_result rc = BSTORM_RESULT_INITIALIZER();
    B_STORM_CHECKED_LITERT_CALL(rc, LiteRtGetSoftmaxBetaOption, (op, &config.beta), err_convert);
    return rc;

err_convert:
    return rc;
}

static bstorm_result bstorm_LiteRt_convert_SpaceToDepth(
    struct bstorm_SpaceToDepthConfig &config, LiteRtOp op)
{
    bstorm_result rc = BSTORM_RESULT_INITIALIZER();
    int32_t block_size;
    B_STORM_CHECKED_LITERT_CALL(rc, LiteRtGetSpaceToDepthBlockSizeOption, (op, &block_size), err_convert);
    B_STORM_PRECONDITION(rc, block_size > 0, err_convert);
    config.block_size = block_size;
    return rc;

err_convert:
    return rc;
}

static bstorm_result bstorm_LiteRt_convert_Split(
    struct bstorm_SplitConfig &config, LiteRtOp op)
{
    bstorm_result rc = BSTORM_RESULT_INITIALIZER();
    int32_t num_splits;
    B_STORM_CHECKED_LITERT_CALL(rc, LiteRtGetSplitNumSplitsOption, (op, &num_splits), err_convert);
    B_STORM_PRECONDITION(rc, num_splits > 0, err_convert);
    config.num_splits = num_splits;
    return rc;

err_convert:
    return rc;
}

static bstorm_result bstorm_LiteRt_convert_Squeeze(
    struct bstorm_SqueezeConfig &config, LiteRtOp op)
{
    bstorm_result rc = BSTORM_RESULT_INITIALIZER();
    const int32_t *squeeze_dims;
    int32_t num_squeeze_dims;

    B_STORM_CHECKED_LITERT_CALL(rc, LiteRtGetSqueezeDimsOption, (op, &squeeze_dims, &num_squeeze_dims), err_convert);
    B_STORM_PRECONDITION(rc, num_squeeze_dims <= BSTORM_BLOB_SHAPE_MAX, err_convert);

    config.shape.dimensions = num_squeeze_dims;
    for(int i=0; i<num_squeeze_dims; i++) {
         config.shape.s[i] = squeeze_dims[i];
    }
    return rc;

err_convert:
    return rc;
}

static bstorm_result bstorm_LiteRt_convert_StridedSlice(
    struct bstorm_StridedSliceConfig &config, LiteRtOp op)
{
    bstorm_result rc = BSTORM_RESULT_INITIALIZER();
    int32_t begin_mask, end_mask, ellipsis_mask, new_axis_mask, shrink_axis_mask;

    B_STORM_CHECKED_LITERT_CALL(rc, LiteRtGetStridedSliceBeginMaskOption, (op, &begin_mask), err_convert);
    B_STORM_CHECKED_LITERT_CALL(rc, LiteRtGetStridedSliceEndMaskOption, (op, &end_mask), err_convert);
    B_STORM_CHECKED_LITERT_CALL(rc, LiteRtGetStridedSliceEllipsisMaskOption, (op, &ellipsis_mask), err_convert);
    B_STORM_CHECKED_LITERT_CALL(rc, LiteRtGetStridedSliceNewAxisMaskOption, (op, &new_axis_mask), err_convert);
    B_STORM_CHECKED_LITERT_CALL(rc, LiteRtGetStridedSliceShrinkAxisMaskOption, (op, &shrink_axis_mask), err_convert);

    B_STORM_PRECONDITION(rc, begin_mask >= 0, err_args);
    B_STORM_PRECONDITION(rc, end_mask >= 0, err_args);
    B_STORM_PRECONDITION(rc, ellipsis_mask >= 0, err_args);
    B_STORM_PRECONDITION(rc, new_axis_mask >= 0, err_args);
    B_STORM_PRECONDITION(rc, shrink_axis_mask >= 0, err_args);

    config.begin_mask = begin_mask;
    config.end_mask = end_mask;
    config.ellipsis_mask = ellipsis_mask;
    config.new_axis_mask = new_axis_mask;
    config.shrink_axis_mask = shrink_axis_mask;
    return rc;

err_args:
err_convert:
    return rc;
}

static bstorm_result bstorm_LiteRt_convert_Sub(
    struct bstorm_SubConfig &config, LiteRtOp op)
{
    bstorm_result rc = BSTORM_RESULT_INITIALIZER();
    B_STORM_CHECKED_CALL(rc, bstorm_LiteRt_convert_activation, (op, config.activation, LiteRtGetSubFusedActivationOption), err_convert);
    return rc;

err_convert:
    return rc;
}

static bstorm_result bstorm_LiteRt_convert_Sum(
    struct bstorm_SumConfig &config, LiteRtOp op)
{
    bstorm_result rc = BSTORM_RESULT_INITIALIZER();
    B_STORM_CHECKED_CALL(rc, bstorm_LiteRt_convert_ReducerConfig, (op, config.reducer, LiteRtGetSumKeepDimsOption), err_convert);
    return rc;

err_convert:
    return rc;
}

static bstorm_result bstorm_LiteRt_convert_TransposeConv2D(
    struct bstorm_TransposeConv2DConfig &config, LiteRtOp op)
{
    bstorm_result rc = BSTORM_RESULT_INITIALIZER();
    B_STORM_CHECKED_CALL(rc, bstorm_LiteRt_convert_activation, (op, config.activation, LiteRtGetTransposeConvFusedActivationOption), err_convert);
    B_STORM_CHECKED_CALL(rc, bstorm_LiteRt_convert_padding, (op, config.padding, LiteRtGetTransposeConvPaddingOption), err_convert);
    B_STORM_CHECKED_CALL(rc, bstorm_LiteRt_convert_2D, (op, config.stride, LiteRtGetTransposeConvStrideWOption, LiteRtGetTransposeConvStrideHOption), err_convert);
    return rc;

err_convert:
    return rc;
}

static bstorm_result bstorm_LiteRt_convert_Unpack(
    struct bstorm_UnpackConfig &config, LiteRtOp op)
{
    bstorm_result rc = BSTORM_RESULT_INITIALIZER();
    int32_t num;
    B_STORM_CHECKED_LITERT_CALL(rc, LiteRtGetUnpackAxisOption, (op, &config.axis), err_convert);
    B_STORM_CHECKED_LITERT_CALL(rc, LiteRtGetUnpackNumOption, (op, &num), err_convert);
    B_STORM_PRECONDITION(rc, num >= 0, err_convert);
    config.num = num;
    return rc;

err_convert:
    return rc;
}

bstorm_result bstorm_LiteRt_compiler_graph::operation_convert(
    struct bstorm_Operation& operation, LiteRtOp op)
{
    bstorm_result rc = BSTORM_RESULT_INITIALIZER();
    LiteRtOpCode op_code;
    LiteRtParamIndex num_inputs, num_outputs;

    B_STORM_CHECKED_LITERT_CALL(rc, LiteRtGetOpCode, (op, &op_code), err_init);
    B_STORM_CHECKED_LITERT_CALL(rc, LiteRtGetNumOpInputs, (op, &num_inputs), err_init);
    B_STORM_CHECKED_LITERT_CALL(rc, LiteRtGetNumOpOutputs, (op, &num_outputs), err_init);

    switch (op_code) {
#define B_UTIL_CONVERT(tfCode, configName) { \
    B_STORM_CHECKED_CALL(rc, bstorm_Operation_init, (&operation, bstorm_Operation_Type_e##configName, num_inputs, num_outputs), err_init); \
    B_STORM_CHECKED_CALL(rc, bstorm_LiteRt_convert_##configName, (operation.config.configName, op), err_operation); } break

#define B_UTIL_NO_ARGS(tfCode, configName) { \
    B_STORM_CHECKED_CALL(rc, bstorm_Operation_init, (&operation, bstorm_Operation_Type_e##configName, num_inputs, num_outputs), err_init); } break

#define B_UTIL_UNSUPPORTED_LITERT(tfCode, configName) { \
    B_STORM_ERROR_VERBOSE(rc, NotSupported, err_operation, "LiteRT V2 API missing : %s", #configName); } break

#define B_UTIL(tfCode, configName, kind) case kLiteRtOpCodeTfl##tfCode: B_UTIL_##kind(tfCode, configName)

        B_UTIL(Abs, Abs, NO_ARGS);
        B_UTIL(Add, Add, CONVERT);
        B_UTIL(ArgMax, ArgMax, CONVERT);
        B_UTIL(AveragePool2d, AveragePool2D, CONVERT);
        B_UTIL(BatchMatmul, BatchMatMul, CONVERT);
        B_UTIL(BatchToSpaceNd, BatchToSpace, NO_ARGS);
        B_UTIL(BroadcastTo, BroadcastTo, NO_ARGS);
        B_UTIL(Cast, Cast, NO_ARGS);
        B_UTIL(Ceil, Ceil, NO_ARGS);
        B_UTIL(ComplexAbs, ComplexAbs, NO_ARGS);
        B_UTIL(Concatenation, Concatenate, CONVERT);
        B_UTIL(Conv2d, Conv2D, CONVERT);
        B_UTIL(Conv3d, Conv3D, CONVERT);
        B_UTIL(Cos, Cos, NO_ARGS);
        B_UTIL(Cumsum, Cumsum, CONVERT);
        B_UTIL(DepthToSpace, DepthToSpace, CONVERT);
        B_UTIL(DepthwiseConv2d, DepthWiseConv2D, CONVERT);
        B_UTIL(Dequantize, Dequantize, NO_ARGS);
        B_UTIL(Div, Div, CONVERT);
        B_UTIL(DynamicUpdateSlice, DynamicUpdateSlice, NO_ARGS);
        B_UTIL(Elu, Elu, NO_ARGS);
        B_UTIL(EmbeddingLookup, EmbeddingLookup, NO_ARGS);
        B_UTIL(Equal, Equal, NO_ARGS);
        B_UTIL(Exp, Exp, NO_ARGS);
        B_UTIL(Floor, Floor, NO_ARGS);
        B_UTIL(FloorDiv, FloorDiv, NO_ARGS);
        B_UTIL(FloorMod, FloorMod, NO_ARGS);
        B_UTIL(FullyConnected, FullyConnected, CONVERT);
        B_UTIL(Gather, Gather, CONVERT);
        B_UTIL(GatherNd, GatherNd, NO_ARGS);
        B_UTIL(Gelu, Gelu, CONVERT);
        B_UTIL(Greater, Greater, NO_ARGS);
        B_UTIL(GreaterEqual, GreaterEqual, NO_ARGS);
        B_UTIL(HardSwish, HardSwish, NO_ARGS);
        B_UTIL(Imag, Imag, NO_ARGS);
        B_UTIL(L2Normalization, L2Normalization, NO_ARGS);
        B_UTIL(LeakyRelu, LeakyRelu, CONVERT);
        B_UTIL(Less, Less, NO_ARGS);
        B_UTIL(LessEqual, LessEqual, NO_ARGS);
        B_UTIL(Log, Log, NO_ARGS);
        B_UTIL(LogSoftmax, LogSoftMax, NO_ARGS);
        B_UTIL(LogicalAnd, LogicalAnd, NO_ARGS);
        B_UTIL(LogicalNot, LogicalNot, NO_ARGS);
        B_UTIL(LogicalOr, LogicalOr, NO_ARGS);
        B_UTIL(Logistic, Logistic, NO_ARGS);
        B_UTIL(MaxPool2d, MaxPool2D, CONVERT);
        B_UTIL(Maximum, Maximum, NO_ARGS);
        B_UTIL(Mean, Mean, CONVERT);
        B_UTIL(Minimum, Minimum, NO_ARGS);
        B_UTIL(MirrorPad, MirrorPad, CONVERT);
        B_UTIL(Mul, Mul, CONVERT);
        B_UTIL(Neg, Neg, NO_ARGS);
        B_UTIL(NotEqual, NotEqual, NO_ARGS);
        B_UTIL(Pack, Pack, CONVERT);
        B_UTIL(Pad, Pad, NO_ARGS);
        B_UTIL(Padv2, Pad, NO_ARGS);
        B_UTIL(Pow, Pow, NO_ARGS);
        B_UTIL(Prelu, Prelu, NO_ARGS);
        B_UTIL(Quantize, Quantize, NO_ARGS);
        B_UTIL(Range, Range, NO_ARGS);
        B_UTIL(Real, Real, NO_ARGS);
        B_UTIL(ReduceAll, ReduceAll, CONVERT);
        B_UTIL(ReduceAny, ReduceAny, CONVERT);
        B_UTIL(ReduceMax, ReduceMax, CONVERT);
        B_UTIL(ReduceMin, ReduceMin, CONVERT);
        B_UTIL(Relu, Relu, NO_ARGS);
        B_UTIL(Relu0To1, Relu0To1, NO_ARGS);
        B_UTIL(Relu6, Relu6, NO_ARGS);
        B_UTIL(ReluN1To1, Relu1, NO_ARGS);
        B_UTIL(Reshape, Reshape, NO_ARGS);
        B_UTIL(ResizeBilinear, ResizeBilinear, CONVERT);
        B_UTIL(ResizeNearestNeighbor, ResizeNearestNeighbor, CONVERT);
        B_UTIL(ReverseV2, ReverseV2, NO_ARGS);
        B_UTIL(Rfft2d, Rfft2d, NO_ARGS);
        B_UTIL(Round, Round, NO_ARGS);
        B_UTIL(Rsqrt, Rsqrt, NO_ARGS);
        B_UTIL(Select, Select, NO_ARGS);
        B_UTIL(SelectV2, SelectV2, NO_ARGS);
        B_UTIL(Sin, Sin, NO_ARGS);
        B_UTIL(Slice, Slice, NO_ARGS);
        B_UTIL(Softmax, SoftMax, CONVERT);
        B_UTIL(SpaceToBatchNd, SpaceToBatch, NO_ARGS);
        B_UTIL(SpaceToDepth, SpaceToDepth, CONVERT);
        B_UTIL(Split, Split, CONVERT);
        B_UTIL(SplitV, SplitV, NO_ARGS);
        B_UTIL(Squeeze, Squeeze, CONVERT);
        B_UTIL(Sqrt, Sqrt, NO_ARGS);
        B_UTIL(Square, Square, NO_ARGS);
        B_UTIL(SquaredDifference, SquaredDifference, NO_ARGS);
        B_UTIL(StridedSlice, StridedSlice, CONVERT);
        B_UTIL(Sub, Sub, CONVERT);
        B_UTIL(Sum, Sum, CONVERT);
        B_UTIL(Tanh, Tanh, NO_ARGS);
        B_UTIL(Tile, Tile, NO_ARGS);
        B_UTIL(TopkV2, TopKV2, NO_ARGS);
        B_UTIL(Transpose, Transpose, NO_ARGS);
        B_UTIL(TransposeConv, TransposeConv2D, CONVERT);
        B_UTIL(Unpack, Unpack, CONVERT);
        B_UTIL(Where, Where, NO_ARGS);

#undef B_UTIL_CONVERT
#undef B_UTIL_NO_ARGS
#undef B_UTIL_UNSUPPORTED_LITERT
#undef B_UTIL
        default:
            goto err_not_supported;
    }
    return rc;

err_not_supported:
    B_STORM_ERROR_VERBOSE(rc, NotSupported, err_operation, "Not supported operation:%d", op_code);

err_operation:
    B_STORM_CHECKED_CALL(rc, bstorm_Operation_init, (&operation, bstorm_Operation_Type_eUnknownOperation, num_inputs, num_outputs), err_init);
    operation.config.UnknownOperation.opcode = op_code;
    return rc;

err_init:
    return rc;
}

static bool bstorm_LiteRt_is_constant(const LiteRtTensor tensor)
{
    bstorm_result rc = BSTORM_RESULT_INITIALIZER();
    LiteRtWeights weights;
    const void* addr;
    size_t size;
    B_STORM_CHECKED_LITERT_CALL(rc, LiteRtGetTensorWeights, (tensor, &weights), err_litert);
    B_STORM_CHECKED_LITERT_CALL(rc, LiteRtGetWeightsBytes, (weights, &addr, &size), err_litert);
    return (addr != nullptr);

err_litert:
    return false;
}

template <typename TensorContainer>
bstorm_result bstorm_LiteRt_compiler_graph::read_shapes(const TensorContainer &tensors, struct bstorm_Blobs &blobs, std::vector<int> &indices)
{
    bstorm_result rc = BSTORM_RESULT_INITIALIZER();

    for (unsigned i = 0, bstorm_index = 0; i < (unsigned)tensors.size(); i++) {
        uint32_t tensor_index;
        LiteRtTensor tensor = tensors[i].Get();
        B_STORM_CHECKED_CALL(rc, bstorm_Blobs_UseInlineBlob, (&blobs, bstorm_index), err_convert);
        B_STORM_ASSERT(blobs.entry[bstorm_index]);
        struct bstorm_Blob &blob = *blobs.entry[bstorm_index];
        bstorm_Blob_Default(&blob);
        B_STORM_CHECKED_CALL(rc, bstorm_LiteRt_BlobShapeFromTensor, (&blob.shape, tensor), err_convert);
        blob.shape.state = bstorm_BlobShapeDimension_Known;
        B_STORM_CHECKED_LITERT_CALL(rc, LiteRtGetTensorIndex, (tensor, &tensor_index), err_convert);
        indices.push_back(tensor_index);
        bstorm_index++;
    }
    return rc;

err_convert:
    return rc;
}

bstorm_result bstorm_LiteRt_compiler_graph::link_blobs(const SubgraphInputs &tensors, struct bstorm_Blobs &blobs)
{
    bstorm_result rc = BSTORM_RESULT_INITIALIZER();

    for (unsigned i = 0, bstorm_index = 0; i < (unsigned)tensors.size(); i++) {
        LiteRtTensor tensor = tensors[i].Get();
        if (bstorm_LiteRt_is_constant(tensor)) {
            LiteRtWeights weights;
            const void* weights_data;
            size_t weights_size;
            LiteRtRankedTensorType tensor_type;
            B_STORM_ASSERT(blobs.entry[bstorm_index]);
            struct bstorm_Blob &blob = *blobs.entry[bstorm_index];
            blob.type = bstorm_BlobType_Constant;
            B_STORM_CHECKED_LITERT_CALL(rc, LiteRtGetTensorWeights, (tensor, &weights), err_convert);
            B_STORM_CHECKED_LITERT_CALL(rc, LiteRtGetWeightsBytes, (weights, &weights_data, &weights_size), err_convert);
            B_STORM_CHECKED_LITERT_CALL(rc, LiteRtGetRankedTensorType, (tensor, &tensor_type), err_convert);
            B_STORM_CHECKED_CALL(rc, bstorm_LiteRt_LinkPayload, (tensor_type, const_cast<void*>(weights_data), weights_size, blob), err_convert);
        }
        bstorm_index++;
    }
    return rc;

err_convert:
    return rc;
}

bstorm_result bstorm_LiteRt_compiler_graph::node_convert(const litert::Op &op)
{
    bstorm_result rc = BSTORM_RESULT_INITIALIZER();
    bstorm_Operation operation;
    std::vector<int> input_indices;
    std::vector<int> output_indices;
    B_STORM_CHECKED_CALL(rc, operation_convert, (operation, op.Get()), err_operation);
    B_STORM_CHECKED_CALL(rc, read_shapes, (op.Inputs(), operation.inputs, input_indices), err_operation);
    B_STORM_CHECKED_CALL(rc, link_blobs, (op.Inputs(), operation.inputs), err_operation);
    B_STORM_CHECKED_CALL(rc, read_shapes, (op.Outputs(), operation.outputs, output_indices), err_operation);
    B_STORM_CHECKED_CALL(rc, bstorm_Graph_SetNode, (bstorm_graph_, &operation, input_indices.data(), output_indices.data()), err_operation);
    return rc;

err_operation:
    bstorm_LiteRt_free_shapes(operation.inputs);
    bstorm_LiteRt_free_shapes(operation.outputs);
    bstorm_Operation_free_blobs(&operation);
    return rc;
}
