/******************************************************************************
 * Copyright (C) 2025 Broadcom.
 * The term "Broadcom" refers to Broadcom Inc. and/or its subsidiaries.
 *
 * This program is the proprietary software of Broadcom and/or its licensors,
 * and may only be used, duplicated, modified or distributed pursuant to
 * the terms and conditions of a separate, written license agreement executed
 * between you and Broadcom (an "Authorized License").  Except as set forth in
 * an Authorized License, Broadcom grants no license (express or implied),
 * right to use, or waiver of any kind with respect to the Software, and
 * Broadcom expressly reserves all rights in and to the Software and all
 * intellectual property rights therein. IF YOU HAVE NO AUTHORIZED LICENSE,
 * THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 * IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.
 *
 * Except as expressly set forth in the Authorized License,
 *
 * 1.     This program, including its structure, sequence and organization,
 * constitutes the valuable trade secrets of Broadcom, and you shall use all
 * reasonable efforts to protect the confidentiality thereof, and to use this
 * information only in connection with your use of Broadcom integrated circuit
 * products.
 *
 * 2.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED
 * "AS IS" AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS
 * OR WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH
 * RESPECT TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL
 * IMPLIED WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR
 * A PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS, QUIET
 * ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION. YOU ASSUME
 * THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE SOFTWARE.
 *
 * 3.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM
 * OR ITS LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL,
 * INDIRECT, OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY
 * RELATING TO YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM
 * HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN
 * EXCESS OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1,
 * WHICHEVER IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY
 * FAILURE OF ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
 *
 * Portions generated by GenAI: Cursor 2.0, Claude Sonnet 4.5
 *
 ******************************************************************************/
#include "bstorm_core_internal.h"
#include "bstorm_compiler_graph.h"

#include "flatbuf/bstorm_flatbuf.h"
#include "common/bstorm_util_litert.h"

#include <memory>
#include <vector>
#include <sys/wait.h>

template <typename TensorContainer>
static unsigned bstorm_LiteRt_update_max_blob(const TensorContainer &tensors, unsigned max_blob)
{
    for (unsigned i = 0; i < (unsigned)tensors.size(); i++) {
        uint32_t tensor_index;
        LiteRtTensor tensor = tensors[i].Get();
        LiteRtGetTensorIndex(tensor, &tensor_index);
        if(tensor_index>0 && tensor_index > (int)max_blob) {
            max_blob = tensor_index;
        }
    }
    return max_blob;
}

bstorm_LiteRt_compiler_graph::~bstorm_LiteRt_compiler_graph()
{
    if (subgraph_ != nullptr) {
        if (bstorm_graph_ != nullptr) {
            bstorm_Graph_Destroy(bstorm_graph_);
            bstorm_graph_ = nullptr;
        }
        subgraph_ = nullptr;
    }
    return;
}

bstorm_result bstorm_LiteRt_compiler_graph::create_graph(LiteRtSubgraph subgraph)
{
    bstorm_result rc = BSTORM_RESULT_INITIALIZER();
    const litert::Subgraph sg(subgraph);
    uint32_t tensor_index;
    unsigned nodes_count = 0;
    unsigned max_blob = 0;

    B_STORM_PRECONDITION(rc, subgraph_ == nullptr, err_exists);

    // Discover number of nodes/tensors for bstorm graph
    for (const auto& op : sg.Ops()) {
        nodes_count++;
        max_blob = bstorm_LiteRt_update_max_blob(op.Inputs(), max_blob);
        max_blob = bstorm_LiteRt_update_max_blob(op.Outputs(), max_blob);
    }

    // Create Bstorm graph
    org_blobs_count_ = max_blob + 1;
    B_STORM_CHECKED_NULL_CALL(rc, bstorm_graph_, bstorm_Graph_Create, (nodes_count, org_blobs_count_), err_create);
    B_STORM_DEBUG("BstormGraph:%p nodes:%u blobs:%u", (void*)bstorm_graph_, nodes_count, org_blobs_count_);

    // Convert LiteRt subgraph ops to Bstorm ops
    for (const auto& op : sg.Ops()) {
        B_STORM_CHECKED_CALL(rc, node_convert, (op), err_convert);
    }

    // Set graph inputs and outputs
    {
        std::vector<int> input_indices;
        std::vector<int> output_indices;

        for (const auto& input : sg.Inputs()) {
            B_STORM_CHECKED_LITERT_CALL(rc, LiteRtGetTensorIndex, (input.Get(), &tensor_index), err_convert);
            input_indices.push_back(tensor_index);
        }
        for (const auto& output : sg.Outputs()) {
            B_STORM_CHECKED_LITERT_CALL(rc, LiteRtGetTensorIndex, (output.Get(), &tensor_index), err_convert);
            output_indices.push_back(tensor_index);
        }
        B_STORM_CHECKED_CALL(rc, bstorm_Graph_SetInputAndOutput, (bstorm_graph_,
                reinterpret_cast<const int*>(input_indices.data()), input_indices.size(),
                reinterpret_cast<const int*>(output_indices.data()), output_indices.size()), err_convert);
    }

    subgraph_ = subgraph;
    return rc;

err_convert:
    bstorm_Graph_Destroy(bstorm_graph_);
    bstorm_graph_ = nullptr;
err_create:
err_exists:
    return rc;
}

bstorm_result bstorm_LiteRt_compiler_graph::get_supported_operations(
    struct bstorm_context *context, std::vector<bool> &supported_nodes)
{
    bstorm_result rc = BSTORM_RESULT_INITIALIZER();

    if (bstorm_graph_ == nullptr) {
        BSTORM_ERROR(rc, NotSupported);
        return rc;
    }

    struct bstorm_Graph_Info info;
    bstorm_Graph_GetInfo(bstorm_graph_, &info);
    std::unique_ptr<bool[]> supported(new bool[info.nodes]);
    struct bstorm_Graph_GetSupportedNodesOptions options;
    bstorm_Graph_GetSupportedNodesOptions_Default(&options);
    B_STORM_CHECKED_CALL(rc, bstorm_Graph_GetSupportedNodes,
        (context, bstorm_graph_, supported.get(), info.nodes, &options), err_supported);
    for (unsigned i = 0; i < info.nodes; ++i) {
        if (supported[i]) {
            supported_nodes.push_back(supported[i]);
        }
    }
    return rc;

err_supported:
    return rc;
}

bstorm_result bstorm_LiteRt_compiler_graph::graph_write(const std::string& name, const std::string& prefix)
{
    bstorm_result rc = BSTORM_RESULT_INITIALIZER();
    std::string file_name = prefix + name + ".graph.bstorm";

    B_STORM_CHECKED_CALL(rc, bstorm_flatbuf_write_graph, (file_name.c_str(), bstorm_graph_), err_write_graph);
    return rc;

err_write_graph:
    return rc;
}

static void bstorm_LiteRt_offline_config_init(struct bstorm_compiler_bstm_offline_config* offline_config,
                                              struct bstorm_bstm_config* bstm_config)
{
    bstorm_compiler_bstm_offline_config_default(offline_config);
    bstorm_bstm_config_Default(bstm_config);
    bstm_config->memory_mode = bstorm_bstm_memory_mode_mmu;
    return;
}

#if !defined(__arm__) && !defined(__aarch64__)
static bstorm_result bstorm_LiteRt_run_graph_tool(const struct bstorm_Graph* src_graph,
                                                   const std::string& tool_path,
                                                   const std::string& options,
                                                   struct bstorm_flatbuf& flatbuf)
{
    bstorm_result rc = BSTORM_RESULT_INITIALIZER();
    char tmp_dir[] = "/tmp/bstorm.XXXXXX";
    char tmp_in[256], tmp_out[256];
    char* tdir = mkdtemp(tmp_dir);
    pid_t pid;
    int prc;
    char _in[] = "--in";
    char _out[] = "--out";
    std::vector<char*> args;
    std::vector<std::string> vec_opts;
    bool debug = false;

    B_STORM_ASSERT(src_graph);
    B_STORM_CONDITION(rc, tdir, err_tmp_dir);
    prc = snprintf(tmp_in, sizeof(tmp_in), "%s/in.graph.bstorm", tmp_dir);
    B_STORM_CONDITION(rc, prc >= 0, err_tmp_name);
    B_STORM_CONDITION(rc, (unsigned)prc < (unsigned)sizeof(tmp_in), err_tmp_name);
    prc = snprintf(tmp_out, sizeof(tmp_out), "%s/out.graph.bstorm", tmp_dir);
    B_STORM_CONDITION(rc, prc >= 0, err_tmp_name);
    B_STORM_CONDITION(rc, (unsigned)prc < (unsigned)sizeof(tmp_out), err_tmp_name);
    B_STORM_CHECKED_CALL(rc, bstorm_flatbuf_write_graph, (tmp_in, src_graph), err_write);
    args.push_back(const_cast<char*>(tool_path.c_str()));
    if (!options.empty()) {
        std::istringstream opts(options);
        std::string tmp;

        while (std::getline(opts, tmp, ' ')) {
            vec_opts.push_back(tmp);
        }
        for (const std::string& s: vec_opts) {
            args.push_back(const_cast<char*>(s.c_str()));
        }
    }
    args.push_back(_in);
    args.push_back(tmp_in);
    args.push_back(_out);
    args.push_back(tmp_out);
    args.push_back(nullptr);
    if (debug) {
        std::ostringstream tmp;
        std::copy(args.begin(), args.end() - 1, std::ostream_iterator<std::string>(tmp, " "));
        tmp << args.back();
        std::string cmd = tmp.str();
        B_STORM_DEBUG("Executing: '%s'", cmd.c_str());
    }
    pid = fork();
    if (pid == -1) {
        B_STORM_ERROR(rc, NotSupported, err_exec);
    } else if (pid == 0) {
        execvp(tool_path.c_str(), args.data());
        B_STORM_ERROR(rc, NotSupported, err_exec);
    } else {
        int status;
        prc = waitpid(pid, &status, 0);
        B_STORM_CONDITION(rc, prc != -1, err_wait);
        B_STORM_CONDITION(rc, prc == pid, err_wait);
        B_STORM_CONDITION(rc, WIFEXITED(status), err_wait);
    }
    B_STORM_CHECKED_CALL(rc, bstorm_flatbuf_read, (tmp_out, &flatbuf, NULL), err_read);
    B_STORM_CONDITION(rc, flatbuf.graph, err_graph_read);
    unlink(tmp_out);
    unlink(tmp_in);
    rmdir(tmp_dir);
    return rc;

err_graph_read:
    bstorm_flatbuf_free(&flatbuf);
err_read:
    unlink(tmp_in);
err_wait:
    unlink(tmp_out);
err_exec:
    unlink(tmp_in);
err_write:
err_tmp_name:
    rmdir(tmp_dir);
err_tmp_dir:
    return rc;
}
#endif /* !__arm__ && !__aarch64__ */

static bstorm_result bstorm_LiteRt_precompile_prepare(
    const struct bstorm_Graph* src_graph,
    const std::string& tool_path,
    const std::string& tool_options,
    struct bstorm_compiler_bstm_offline_config& offline_config,
    struct bstorm_bstm_config& bstm_config,
    struct bstorm_flatbuf& transformed,
    const struct bstorm_Graph*& graph_to_compile,
    bool bstm_compress)
{
    bstorm_result rc = BSTORM_RESULT_INITIALIZER();
    bstorm_LiteRt_offline_config_init(&offline_config, &bstm_config);
    if (bstm_compress) {
        bstm_config.weight_compression = 1;
    }
    graph_to_compile = src_graph;
#if !defined(__arm__) && !defined(__aarch64__)
    if (!tool_path.empty()) {
        B_STORM_CHECKED_CALL(rc, bstorm_LiteRt_run_graph_tool, (src_graph, tool_path, tool_options, transformed), err_tool);
        graph_to_compile = transformed.graph->graph;
    }
#else
    (void)tool_path; (void)tool_options;
#endif
    return rc;
err_tool:
    return rc;
}

bstorm_result bstorm_LiteRt_compiler_graph::graph_precompile_to_file(struct bstorm_context* context,
                                                                       const std::string& bstm_file,
                                                                       const std::string& tool_path,
                                                                       const std::string& tool_options,
                                                                       bool bstm_compress)
{
    bstorm_result rc = BSTORM_RESULT_INITIALIZER();
    struct bstorm_compiler_bstm_offline_config offline_config;
    struct bstorm_bstm_config bstm_config;
    struct bstorm_flatbuf transformed;
    const struct bstorm_Graph* graph_to_compile;

    B_STORM_CHECKED_CALL(rc, bstorm_LiteRt_precompile_prepare,
        (bstorm_graph_, tool_path, tool_options,
         offline_config, bstm_config, transformed, graph_to_compile, bstm_compress), err_prepare);
    B_STORM_DEBUG("Offline compile to file: %s", bstm_file.c_str());
    B_STORM_CHECKED_CALL(rc, bstorm_compiler_bstm_offline_process,
        (context, &offline_config, &bstm_config, graph_to_compile, NULL, NULL, NULL, bstm_file.c_str()),
        err_compile);
    if (transformed.graph) bstorm_flatbuf_free(&transformed);
    return rc;

err_compile:
    if (transformed.graph) bstorm_flatbuf_free(&transformed);
err_prepare:
    return rc;
}

bstorm_result bstorm_LiteRt_compiler_graph::graph_precompile_to_buffer(struct bstorm_context* context,
                                                                         struct bstorm_compiler_bstm_offline_output_buffer& out,
                                                                         const std::string& tool_path,
                                                                         const std::string& tool_options,
                                                                         bool bstm_compress)
{
    bstorm_result rc = BSTORM_RESULT_INITIALIZER();
    struct bstorm_compiler_bstm_offline_config offline_config;
    struct bstorm_bstm_config bstm_config;
    struct bstorm_flatbuf transformed;
    const struct bstorm_Graph* graph_to_compile;

    B_STORM_CHECKED_CALL(rc, bstorm_LiteRt_precompile_prepare,
        (bstorm_graph_, tool_path, tool_options,
         offline_config, bstm_config, transformed, graph_to_compile, bstm_compress), err_prepare);
    B_STORM_CHECKED_CALL(rc, bstorm_compiler_bstm_offline_process_to_buffer,
        (context, &offline_config, &bstm_config, graph_to_compile, &out),
        err_compile);
    if (transformed.graph) bstorm_flatbuf_free(&transformed);
    return rc;

err_compile:
    if (transformed.graph) bstorm_flatbuf_free(&transformed);
err_prepare:
    return rc;
}
