/******************************************************************************
 * Copyright (C) 2025 Broadcom.
 * The term "Broadcom" refers to Broadcom Inc. and/or its subsidiaries.
 *
 * This program is the proprietary software of Broadcom and/or its licensors,
 * and may only be used, duplicated, modified or distributed pursuant to
 * the terms and conditions of a separate, written license agreement executed
 * between you and Broadcom (an "Authorized License").  Except as set forth in
 * an Authorized License, Broadcom grants no license (express or implied),
 * right to use, or waiver of any kind with respect to the Software, and
 * Broadcom expressly reserves all rights in and to the Software and all
 * intellectual property rights therein. IF YOU HAVE NO AUTHORIZED LICENSE,
 * THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 * IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.
 *
 * Except as expressly set forth in the Authorized License,
 *
 * 1.     This program, including its structure, sequence and organization,
 * constitutes the valuable trade secrets of Broadcom, and you shall use all
 * reasonable efforts to protect the confidentiality thereof, and to use this
 * information only in connection with your use of Broadcom integrated circuit
 * products.
 *
 * 2.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED
 * "AS IS" AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS
 * OR WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH
 * RESPECT TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL
 * IMPLIED WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR
 * A PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS, QUIET
 * ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION. YOU ASSUME
 * THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE SOFTWARE.
 *
 * 3.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM
 * OR ITS LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL,
 * INDIRECT, OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY
 * RELATING TO YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM
 * HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN
 * EXCESS OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1,
 * WHICHEVER IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY
 * FAILURE OF ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
 *
 * Portions generated by GenAI: Cursor 2.0, Claude Sonnet 4.5
 *
 ******************************************************************************/
#include "bstorm_core_internal.h"
#include "bstorm_compiler_graph.h"

#include "flatbuf/bstorm_flatbuf.h"
#include "common/bstorm_util_litert.h"

#include <memory>
#include <vector>

template <typename TensorContainer>
static unsigned bstorm_LiteRt_update_max_blob(const TensorContainer &tensors, unsigned max_blob)
{
    for (unsigned i = 0; i < (unsigned)tensors.size(); i++) {
        uint32_t tensor_index;
        LiteRtTensor tensor = tensors[i].Get();
        LiteRtGetTensorIndex(tensor, &tensor_index);
        if(tensor_index>0 && tensor_index > (int)max_blob) {
            max_blob = tensor_index;
        }
    }
    return max_blob;
}

bstorm_LiteRt_compiler_graph::~bstorm_LiteRt_compiler_graph()
{
    if (subgraph_ != nullptr) {
        if (bstorm_graph_ != nullptr) {
            bstorm_Graph_Destroy(bstorm_graph_);
            bstorm_graph_ = nullptr;
        }
        subgraph_ = nullptr;
    }
    return;
}

bstorm_result bstorm_LiteRt_compiler_graph::create_graph(LiteRtSubgraph subgraph)
{
    bstorm_result rc = BSTORM_RESULT_INITIALIZER();
    const litert::Subgraph sg(subgraph);
    uint32_t tensor_index;
    unsigned nodes_count = 0;
    unsigned max_blob = 0;

    B_STORM_PRECONDITION(rc, subgraph_ == nullptr, err_exists);

    // Discover number of nodes/tensors for bstorm graph
    for (const auto& op : sg.Ops()) {
        nodes_count++;
        max_blob = bstorm_LiteRt_update_max_blob(op.Inputs(), max_blob);
        max_blob = bstorm_LiteRt_update_max_blob(op.Outputs(), max_blob);
    }

    // Create Bstorm graph
    org_blobs_count_ = max_blob + 1;
    B_STORM_CHECKED_NULL_CALL(rc, bstorm_graph_, bstorm_Graph_Create, (nodes_count, org_blobs_count_), err_create);
    B_STORM_DEBUG("BstormGraph:%p nodes:%u blobs:%u", (void*)bstorm_graph_, nodes_count, org_blobs_count_);

    // Convert LiteRt subgraph ops to Bstorm ops
    for (const auto& op : sg.Ops()) {
        B_STORM_CHECKED_CALL(rc, node_convert, (op), err_convert);
    }

    // Set graph inputs and outputs
    {
        std::vector<int> input_indices;
        std::vector<int> output_indices;

        for (const auto& input : sg.Inputs()) {
            B_STORM_CHECKED_LITERT_CALL(rc, LiteRtGetTensorIndex, (input.Get(), &tensor_index), err_convert);
            input_indices.push_back(tensor_index);
        }
        for (const auto& output : sg.Outputs()) {
            B_STORM_CHECKED_LITERT_CALL(rc, LiteRtGetTensorIndex, (output.Get(), &tensor_index), err_convert);
            output_indices.push_back(tensor_index);
        }
        B_STORM_CHECKED_CALL(rc, bstorm_Graph_SetInputAndOutput, (bstorm_graph_,
                reinterpret_cast<const int*>(input_indices.data()), input_indices.size(),
                reinterpret_cast<const int*>(output_indices.data()), output_indices.size()), err_convert);
    }

    subgraph_ = subgraph;
    return rc;

err_convert:
    bstorm_Graph_Destroy(bstorm_graph_);
    bstorm_graph_ = nullptr;
err_create:
err_exists:
    return rc;
}

bstorm_result bstorm_LiteRt_compiler_graph::get_supported_operations(
    struct bstorm_context *context, std::vector<bool> &supported_nodes)
{
    bstorm_result rc = BSTORM_RESULT_INITIALIZER();

    if (bstorm_graph_ == nullptr) {
        BSTORM_ERROR(rc, NotSupported);
        return rc;
    }

    struct bstorm_Graph_Info info;
    bstorm_Graph_GetInfo(bstorm_graph_, &info);
    std::unique_ptr<bool[]> supported(new bool[info.nodes]);
    struct bstorm_Graph_GetSupportedNodesOptions options;
    bstorm_Graph_GetSupportedNodesOptions_Default(&options);
    B_STORM_CHECKED_CALL(rc, bstorm_Graph_GetSupportedNodes,
        (context, bstorm_graph_, supported.get(), info.nodes, &options), err_supported);
    for (unsigned i = 0; i < info.nodes; ++i) {
        if (supported[i]) {
            supported_nodes.push_back(supported[i]);
        }
    }
    return rc;

err_supported:
    return rc;
}

bstorm_result bstorm_LiteRt_compiler_graph::graph_write(const std::string& name, const std::string& prefix)
{
    bstorm_result rc = BSTORM_RESULT_INITIALIZER();
    std::string file_name = prefix + name + ".graph.bstorm";

    B_STORM_CHECKED_CALL(rc, bstorm_flatbuf_write_graph, (file_name.c_str(), bstorm_graph_), err_write_graph);
    return rc;

err_write_graph:
    return rc;
}

static void bstorm_LiteRt_offline_config_init(struct bstorm_compiler_bstm_offline_config* offline_config,
                                              struct bstorm_bstm_config* bstm_config)
{
    bstorm_compiler_bstm_offline_config_default(offline_config);
    bstorm_bstm_config_Default(bstm_config);
    bstm_config->memory_mode = bstorm_bstm_memory_mode_mmu;
    return;
}

bstorm_result bstorm_LiteRt_compiler_graph::graph_precompile_to_file(struct bstorm_context* context, const std::string& bstm_file)
{
    bstorm_result rc = BSTORM_RESULT_INITIALIZER();
    struct bstorm_compiler_bstm_offline_config offline_config;
    struct bstorm_bstm_config bstm_config;

    bstorm_LiteRt_offline_config_init(&offline_config, &bstm_config);
    B_STORM_DEBUG("Running offline compilation to file: %s", bstm_file.c_str());
    B_STORM_CHECKED_CALL(rc, bstorm_compiler_bstm_offline_process,
        (context, &offline_config, &bstm_config, bstorm_graph_, NULL, NULL, NULL, bstm_file.c_str()),
        err_compile);
    B_STORM_DEBUG("Wrote precompiled .bstm: %s", bstm_file.c_str());
    return rc;

err_compile:
    return rc;
}

bstorm_result bstorm_LiteRt_compiler_graph::graph_precompile_to_buffer(struct bstorm_context* context, struct bstorm_compiler_bstm_offline_output_buffer& out)
{
    bstorm_result rc = BSTORM_RESULT_INITIALIZER();
    struct bstorm_compiler_bstm_offline_config offline_config;
    struct bstorm_bstm_config bstm_config;

    bstorm_LiteRt_offline_config_init(&offline_config, &bstm_config);
    B_STORM_DEBUG_PRINT("Running offline compilation to buffer");
    B_STORM_CHECKED_CALL(rc, bstorm_compiler_bstm_offline_process_to_buffer,
        (context, &offline_config, &bstm_config, bstorm_graph_, &out),
        err_compile);
    B_STORM_DEBUG("Compiled .bstm to buffer: %zu bytes", out.buffer_size);
    return rc;

err_compile:
    return rc;
}
