/******************************************************************************
 * Copyright (C) 2025 Broadcom.
 * The term "Broadcom" refers to Broadcom Inc. and/or its subsidiaries.
 *
 * This program is the proprietary software of Broadcom and/or its licensors,
 * and may only be used, duplicated, modified or distributed pursuant to
 * the terms and conditions of a separate, written license agreement executed
 * between you and Broadcom (an "Authorized License").  Except as set forth in
 * an Authorized License, Broadcom grants no license (express or implied),
 * right to use, or waiver of any kind with respect to the Software, and
 * Broadcom expressly reserves all rights in and to the Software and all
 * intellectual property rights therein. IF YOU HAVE NO AUTHORIZED LICENSE,
 * THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 * IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.
 *
 * Except as expressly set forth in the Authorized License,
 *
 * 1.     This program, including its structure, sequence and organization,
 * constitutes the valuable trade secrets of Broadcom, and you shall use all
 * reasonable efforts to protect the confidentiality thereof, and to use this
 * information only in connection with your use of Broadcom integrated circuit
 * products.
 *
 * 2.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED
 * "AS IS" AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS
 * OR WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH
 * RESPECT TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL
 * IMPLIED WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR
 * A PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS, QUIET
 * ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION. YOU ASSUME
 * THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE SOFTWARE.
 *
 * 3.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM
 * OR ITS LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL,
 * INDIRECT, OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY
 * RELATING TO YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM
 * HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN
 * EXCESS OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1,
 * WHICHEVER IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY
 * FAILURE OF ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
 ******************************************************************************/
/* Portions generated by GENAI: Cursor 2.2.36 (IDE), Claude Sonnet 4.5 */
#include "bstorm_core_internal.h"
#include "bstorm_compiler_graph.h"
#include "common/bstorm_util_litert.h"

#include "litert/c/litert_common.h"
#include "litert/c/litert_model.h"
#include "litert/c/litert_op_code.h"
#include "litert/cc/litert_environment_options.h"
#include "litert/cc/litert_macros.h"
#include "litert/cc/litert_model.h"
#include "litert/cc/internal/litert_op_options.h"
#include "litert/cc/litert_opaque_options.h"
#include "litert/cc/litert_options.h"
#include "litert/vendors/c/litert_compiler_plugin.h"

#include <cstdlib>
#include <memory>
#include <set>
#include <sstream>
#include <string>
#include <vector>

struct bstorm_compiler_plugin_config {
    std::string graph_type;
    std::string graph_name;
    std::string graph_path;
    std::set<unsigned> skip_nodes;
    bool precompile;
    bool embed_precompiled;
};

class bstorm_compiler_plugin {
  public:
    bstorm_compiler_plugin() : bstorm_context_(nullptr) {
        config_.precompile = false;
        config_.embed_precompiled = true;
    }

    ~bstorm_compiler_plugin() {
        if (bstorm_context_) {
            bstorm_context_destroy(bstorm_context_);
        }
    }

    bstorm_result init() {
        bstorm_result rc = BSTORM_RESULT_INITIALIZER();
        B_STORM_CHECKED_NULL_CALL(rc, bstorm_context_, bstorm_context_create, (NULL), err_context);

        {
            const char* options_env = std::getenv("BSTORM_COMPILER_PLUGIN_OPTIONS");
            if (options_env != nullptr) {
                std::string options_str(options_env);
                B_STORM_CHECKED_CALL(rc, parse_options, (options_str), err_parse_options);
            }
        }

        return rc;
    err_parse_options:
    err_context:
        return rc;
    }

    struct bstorm_context *get_bstorm_context() const {
        B_STORM_ASSERT(bstorm_context_);
        return bstorm_context_;
    }

    const bstorm_compiler_plugin_config& get_config() const {
        return config_;
    }

  private:
    bstorm_result parse_options(const std::string& options_str) {
        bstorm_result rc = BSTORM_RESULT_INITIALIZER();
        size_t pos = 0;
        std::string token;
        std::string options = options_str;

        while ((pos = options.find(',')) != std::string::npos) {
            token = options.substr(0, pos);
            B_STORM_CHECKED_CALL(rc, parse_option_pair, (token), err_parse_option_pair);
            options.erase(0, pos + 1);
        }
        // Parse the last token (or the only token if no comma was found)
        if (!options.empty()) {
            B_STORM_CHECKED_CALL(rc, parse_option_pair, (options), err_parse_option_pair);
        }
        return rc;
    err_parse_option_pair:
        return rc;
    }

    bstorm_result parse_skip_nodes_value(const std::string& value) {
        bstorm_result rc = BSTORM_RESULT_INITIALIZER();
        if (value.empty()) {
            return rc;
        }
        // Parse either a single node or a range (e.g., "37" or "22-37")
        B_STORM_CHECKED_CALL(rc, parse_single_node_or_range, (value), err_parse_node);
        return rc;
    err_parse_node:
        return rc;
    }

    bstorm_result parse_single_node_or_range(const std::string& token) {
        bstorm_result rc = BSTORM_RESULT_INITIALIZER();
        size_t dash_pos = token.find('-');
        if (dash_pos != std::string::npos) {
            // Handle range (e.g., "20-22")
            std::string start_str = token.substr(0, dash_pos);
            std::string end_str = token.substr(dash_pos + 1);
            try {
                int start = std::stoi(start_str);
                int end = std::stoi(end_str);
                if (start > end) {
                    B_STORM_ERROR(rc, InvalidParameter, err_invalid_range);
                }
                for (int i = start; i <= end; ++i) {
                    config_.skip_nodes.insert(i);
                }
            } catch (const std::exception&) {
                B_STORM_ERROR(rc, InvalidParameter, err_invalid_number);
            }
        } else {
            // Handle single number (e.g., "20")
            try {
                int node = std::stoi(token);
                config_.skip_nodes.insert(node);
            } catch (const std::exception&) {
                B_STORM_ERROR(rc, InvalidParameter, err_invalid_number);
            }
        }
        return rc;
    err_invalid_range:
    err_invalid_number:
        return rc;
    }

    bstorm_result parse_option_pair(const std::string& option) {
        bstorm_result rc = BSTORM_RESULT_INITIALIZER();
        size_t eq_pos = option.find('=');
        if (eq_pos != std::string::npos) {
            std::string key = option.substr(0, eq_pos);
            std::string value = option.substr(eq_pos + 1);
            if (key == "graph-type") {
                config_.graph_type = value;
            } else if (key == "graph-name") {
                config_.graph_name = value;
            } else if (key == "graph-path") {
                config_.graph_path = value;
            } else if (key == "skip-nodes") {
                B_STORM_CHECKED_CALL(rc, parse_skip_nodes_value, (value), err_parse_skip_nodes);
            } else if (key == "precompile") {
                config_.precompile = bstorm_boolean_from_arg(value.c_str());
            } else if (key == "embed-precompiled") {
                config_.embed_precompiled = bstorm_boolean_from_arg(value.c_str());
            } else {
                B_STORM_ERROR(rc, NotSupported, err_invalid_option);
            }
        }
        return rc;
    err_parse_skip_nodes:
    err_invalid_option:
        return rc;
    }

    struct bstorm_context *bstorm_context_;
    bstorm_compiler_plugin_config config_;
};

class LiteRtCompilerPluginT : public bstorm_compiler_plugin { };

constexpr char kPluginManufacturer[] = BSTORM_VENDOR_ID;
constexpr char kPluginSdkVersion[] = "1.0";
constexpr const char* kPluginSocModels[] = {"7712_C0"};
constexpr unsigned kNumPluginSocModels =
    sizeof(kPluginSocModels) / sizeof(kPluginSocModels[0]);

//
// LiteRT Compiler Plugin API
//

LiteRtStatus LiteRtGetCompilerPluginVersion(LiteRtApiVersion *api_version)
{
    if (!api_version) {
        return kLiteRtStatusErrorInvalidArgument;
    }
    api_version->major = LITERT_API_VERSION_MAJOR;
    api_version->minor = LITERT_API_VERSION_MINOR;
    api_version->patch = LITERT_API_VERSION_PATCH;
    return kLiteRtStatusOk;
}

LiteRtStatus LiteRtGetCompilerPluginSupportedHardware(
    LiteRtCompilerPlugin compiler_plugin,
    LiteRtHwAccelerators *supported_hardware)
{
    if (!compiler_plugin || !supported_hardware) {
        return kLiteRtStatusErrorInvalidArgument;
    }
    *supported_hardware = kLiteRtHwAcceleratorNpu;
    return kLiteRtStatusOk;
}

const char* LiteRtGetCompilerPluginSocManufacturer()
{
    return kPluginManufacturer;
}

LiteRtStatus LiteRtGetNumCompilerPluginSupportedSocModels(
    LiteRtCompilerPlugin compiler_plugin,
    LiteRtParamIndex *num_supported_soc_models)
{
    if (!compiler_plugin || !num_supported_soc_models) {
        return kLiteRtStatusErrorInvalidArgument;
    }
    *num_supported_soc_models = kNumPluginSocModels;
    return kLiteRtStatusOk;
}

LiteRtStatus LiteRtGetCompilerPluginSupportedSocModel(
    LiteRtCompilerPlugin compiler_plugin, LiteRtParamIndex soc_model_idx,
    const char **soc_model_name)
{
    if (!compiler_plugin || !soc_model_name) {
        return kLiteRtStatusErrorInvalidArgument;
    } else if (soc_model_idx >= kNumPluginSocModels) {
        return kLiteRtStatusErrorUnsupported;
    }
    *soc_model_name = kPluginSocModels[soc_model_idx];
    return kLiteRtStatusOk;
}

LiteRtStatus LiteRtGetCompilerPluginSDKVersion(
    LiteRtCompilerPlugin compiler_plugin, const char** sdk_version)
{
    if (!compiler_plugin || !sdk_version) {
        return kLiteRtStatusErrorInvalidArgument;
    }
    *sdk_version = kPluginSdkVersion;
    return kLiteRtStatusOk;
}

//
// Compiled Result Definition
//

// Simple compiled result def holds byte code and per op data.
class bstorm_compiled_result {
  public:
    std::vector<std::string> byte_code;
    std::vector<std::string> per_op_data;
};

class LiteRtCompiledResultT : public bstorm_compiled_result { };

LiteRtStatus LiteRtGetCompiledResultByteCode(
    LiteRtCompiledResult compiled_result, LiteRtParamIndex byte_code_idx,
    const void **byte_code, size_t *byte_code_size)
{
    if (!compiled_result) {
        return kLiteRtStatusErrorInvalidArgument;
    }
    *byte_code = compiled_result->byte_code[byte_code_idx].data();
    *byte_code_size = compiled_result->byte_code[byte_code_idx].size();
    return kLiteRtStatusOk;
}

LiteRtStatus LiteRtGetCompiledResultCallInfo(
    LiteRtCompiledResult compiled_result, LiteRtParamIndex call_idx,
    const void **call_info, size_t *call_info_size,
    LiteRtParamIndex *byte_code_idx)
{
    if (call_idx >= compiled_result->per_op_data.size()) {
        return kLiteRtStatusErrorIndexOOB;
    }
    *call_info = compiled_result->per_op_data.at(call_idx).data();
    *call_info_size = compiled_result->per_op_data.at(call_idx).size();
    *byte_code_idx = call_idx;
    return kLiteRtStatusOk;
}

LiteRtStatus LiteRtGetNumCompiledResultCalls(
    LiteRtCompiledResult compiled_result, LiteRtParamIndex *num_calls)
{
    if (!compiled_result) {
        return kLiteRtStatusErrorInvalidArgument;
    }
    *num_calls = compiled_result->per_op_data.size();
    return kLiteRtStatusOk;
}

LiteRtStatus LiteRtCompiledResultNumByteCodeModules(
    LiteRtCompiledResult compiled_result, LiteRtParamIndex *num_byte_code)
{
    *num_byte_code = compiled_result->byte_code.size();
    return kLiteRtStatusOk;
}

void LiteRtDestroyCompiledResult(LiteRtCompiledResult compiled_result)
{
    delete compiled_result;
}

//
// Plugin Definition
//

LiteRtStatus LiteRtCreateCompilerPlugin(
    const LiteRtCompilerContext* compiler_context,
    LiteRtCompilerPlugin *compiler_plugin,
    LiteRtEnvironmentOptions env, LiteRtOptions options)
{
    bstorm_result rc = BSTORM_RESULT_INITIALIZER();
    *compiler_plugin = new LiteRtCompilerPluginT();
    B_STORM_CHECKED_CALL(rc, (*compiler_plugin)->init, (), err_init);
    return kLiteRtStatusOk;
err_init:
    delete *compiler_plugin;
    return kLiteRtStatusErrorRuntimeFailure;
}

void LiteRtDestroyCompilerPlugin(LiteRtCompilerPlugin compiler_plugin)
{
    delete compiler_plugin;
}

LiteRtStatus LiteRtCompilerPluginPartition(LiteRtCompilerPlugin compiler_plugin,
                                           const char* soc_model,
                                           LiteRtSubgraph subgraph,
                                           LiteRtOpList selected_ops)
{
    bstorm_result rc = BSTORM_RESULT_INITIALIZER();
    bstorm_LiteRt_compiler_graph graph;
    std::vector<bool> supported_nodes;
    const litert::Subgraph sg(subgraph);
    unsigned op_index = 0;

    const bstorm_compiler_plugin_config& config = compiler_plugin->get_config();

    B_STORM_CHECKED_CALL(rc, graph.create_graph, (subgraph), err_graph);
    B_STORM_CHECKED_CALL(rc, graph.get_supported_operations, (compiler_plugin->get_bstorm_context(), supported_nodes), err_supported);

    // Iterate through operations and push supported ones to selected_ops
    for (const auto& op : sg.Ops()) {
        // Check if this node should be skipped
        if (config.skip_nodes.find(op_index) != config.skip_nodes.end()) {
            B_STORM_DEBUG("Skipping node %u", op_index);
            op_index++;
            continue;
        }

        if (op_index < supported_nodes.size() && supported_nodes[op_index]) {
            LITERT_RETURN_IF_ERROR(LiteRtPushOp(selected_ops, op.Get(), 0));
        }
        op_index++;
    }
    return kLiteRtStatusOk;

err_supported:
err_graph:
    return kLiteRtStatusErrorRuntimeFailure;
}

static LiteRtStatus bstorm_LiteRt_compile_partition(LiteRtCompilerPlugin compiler_plugin,
                                    LiteRtParamIndex partition_index,
                                    LiteRtSubgraph subgraph,
                                    LiteRtCompiledResultT &result,
                                    int byte_code_idx)
{
    bstorm_result rc = BSTORM_RESULT_INITIALIZER();
    bstorm_LiteRt_compiler_graph graph;

    // Use graph config from environment variable if provided
    const bstorm_compiler_plugin_config& config = compiler_plugin->get_config();
    std::string graph_type = config.graph_type;
    std::string graph_name = config.graph_name;
    std::string graph_path = config.graph_path;

    // Fall back to default if not provided
    if (graph_type.empty()) {
        graph_type = "bstorm";
    }
    if (!graph_path.empty() && graph_path.back() != '/') {
        graph_path += "/";
    }

    graph_name = graph_name + ".partition_" + std::to_string(partition_index);

    std::string per_op_data = graph_type;

    B_STORM_CHECKED_CALL(rc, graph.create_graph, (subgraph), err_graph);
    if (config.embed_precompiled) {
        struct bstorm_compiler_bstm_offline_output_buffer bstm_out = {nullptr, 0};

        B_STORM_CHECKED_CALL(rc, graph.graph_precompile_to_buffer, (compiler_plugin->get_bstorm_context(), bstm_out), err_write);
        result.byte_code[byte_code_idx].assign(static_cast<const char*>(bstm_out.buffer), bstm_out.buffer_size);
        free(bstm_out.buffer);
        per_op_data = "bstm.embedded";
    } else if (config.precompile) {
        std::string bstm_file = graph_path + graph_name + ".bstm";
        std::string bstm_name = graph_name + ".bstm";

        B_STORM_CHECKED_CALL(rc, graph.graph_precompile_to_file, (compiler_plugin->get_bstorm_context(), bstm_file), err_write);
        result.byte_code[byte_code_idx].append(bstm_name);
        per_op_data = "bstm";
    } else {
        std::string byte_code = graph_name + ".graph." + graph_type;
        result.byte_code[byte_code_idx].append(byte_code);
        B_STORM_CHECKED_CALL(rc, graph.graph_write, (graph_name, graph_path), err_write);
    }
    result.per_op_data.push_back(per_op_data);
    return kLiteRtStatusOk;

err_write:
err_graph:
    return kLiteRtStatusErrorRuntimeFailure;
}

LiteRtStatus LiteRtCompilerPluginCompile(
    LiteRtCompilerPlugin compiler_plugin, const char* soc_model,
    LiteRtModel partitions, LiteRtCompiledResult *compiled_result)
{
    LiteRtParamIndex num_partitions;
    LITERT_RETURN_IF_ERROR(LiteRtGetNumModelSubgraphs(partitions, &num_partitions));
    auto result = std::make_unique<LiteRtCompiledResultT>();
    result->byte_code.resize(num_partitions);
    for (auto i = 0; i < num_partitions; ++i) {
        LiteRtSubgraph subgraph;
        LITERT_RETURN_IF_ERROR(LiteRtGetModelSubgraph(partitions, i, &subgraph));
        LITERT_RETURN_IF_ERROR(bstorm_LiteRt_compile_partition(compiler_plugin, i, subgraph, *result, i));
    }
    *compiled_result = result.release();

    return kLiteRtStatusOk;
}

LiteRtStatus LiteRtCompilerPluginRegisterAllTransformations(
    LiteRtCompilerPlugin compiler_plugin,
    LiteRtTransformation** transformations, LiteRtParamIndex* num_patterns)
{
    if (!compiler_plugin || !transformations || !num_patterns) {
        return kLiteRtStatusErrorInvalidArgument;
    }
    // No transformations for bstorm plugin
    *num_patterns = 0;
    *transformations = nullptr;
    return kLiteRtStatusOk;
}

LiteRtStatus LiteRtCompilerPluginCheckCompilerCompatibility(
    LiteRtApiVersion api_version, LiteRtCompilerPlugin compiler_plugin,
    LiteRtEnvironmentOptions env, LiteRtOptions options,
    const char* soc_model_name)
{
    return kLiteRtStatusOk;
}
