/******************************************************************************
 * Copyright (C) 2025 Broadcom.
 * The term "Broadcom" refers to Broadcom Inc. and/or its subsidiaries.
 *
 * This program is the proprietary software of Broadcom and/or its licensors,
 * and may only be used, duplicated, modified or distributed pursuant to
 * the terms and conditions of a separate, written license agreement executed
 * between you and Broadcom (an "Authorized License").  Except as set forth in
 * an Authorized License, Broadcom grants no license (express or implied),
 * right to use, or waiver of any kind with respect to the Software, and
 * Broadcom expressly reserves all rights in and to the Software and all
 * intellectual property rights therein. IF YOU HAVE NO AUTHORIZED LICENSE,
 * THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 * IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.
 *
 * Except as expressly set forth in the Authorized License,
 *
 * 1.     This program, including its structure, sequence and organization,
 * constitutes the valuable trade secrets of Broadcom, and you shall use all
 * reasonable efforts to protect the confidentiality thereof, and to use this
 * information only in connection with your use of Broadcom integrated circuit
 * products.
 *
 * 2.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED
 * "AS IS" AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS
 * OR WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH
 * RESPECT TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL
 * IMPLIED WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR
 * A PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS, QUIET
 * ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION. YOU ASSUME
 * THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE SOFTWARE.
 *
 * 3.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM
 * OR ITS LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL,
 * INDIRECT, OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY
 * RELATING TO YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM
 * HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN
 * EXCESS OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1,
 * WHICHEVER IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY
 * FAILURE OF ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
 ******************************************************************************/
/* Portions generated by GENAI: Cursor 2.2.36 (IDE), Claude Sonnet 4.5 */
#ifndef BSTORM_COMPILER_GRAPH_H_
#define BSTORM_COMPILER_GRAPH_H_

#include "bstorm_common.h"
#include "bstorm_operations.h"
#include "bstorm_types.h"

#include "litert/cc/litert_model.h"
#include "litert/cc/internal/litert_extended_model.h"
#include "bstm/compiler/bstorm_compiler_bstm_offline.h"
#include "common/bstorm_util_litert.h"

#include <string>
#include <vector>

class bstorm_LiteRt_compiler_graph {
  public:
    bstorm_LiteRt_compiler_graph() {}
    ~bstorm_LiteRt_compiler_graph();

    bstorm_result create_graph(LiteRtSubgraph subgraph);
    bstorm_result node_convert(const litert::Op &op);
    bstorm_result get_supported_operations(struct bstorm_context *context, std::vector<bool> &supported_nodes);
    bstorm_result graph_write(const std::string& name, const std::string& prefix);
    bstorm_result graph_precompile_to_file(struct bstorm_context* context, const std::string& bstm_file);
    bstorm_result graph_precompile_to_buffer(struct bstorm_context* context, struct bstorm_compiler_bstm_offline_output_buffer& out);

  private:
    bstorm_result operation_convert(struct bstorm_Operation& operation, LiteRtOp op);

    template <typename TensorContainer>
    bstorm_result read_shapes(const TensorContainer &tensors,
                              struct bstorm_Blobs &blobs,
                              std::vector<int> &indices);
    bstorm_result link_blobs(const litert::SubgraphInputs &tensors, struct bstorm_Blobs &blobs);

    LiteRtSubgraph subgraph_ = nullptr;
    struct bstorm_Graph *bstorm_graph_ = nullptr;
    unsigned org_blobs_count_ = 0;
};
#endif /* #ifndef BSTORM_COMPILER_GRAPH_H_ */
