// Copyright 2025 Google LLC.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#include <any>
#include <cstdlib>
#include <memory>

#include "testing/base/public/gunit.h"
#include "ml_drift/common/ir_model.h"  // from @ml_drift
#include "ml_drift/common/operations.h"  // from @ml_drift
#include "ml_drift/common/shape.h"  // from @ml_drift
#include "third_party/odml/litert/ml_drift/tflite/convert/convert_testing_utils.h"
#include "third_party/odml/litert/ml_drift/tflite/convert/stub_delegate.h"
#include "tflite/builtin_ops.h"
#include "tflite/c/builtin_op_data.h"
#include "tflite/c/c_api.h"
#include "tflite/c/common.h"
#include "tflite/interpreter.h"

namespace litert::ml_drift::ir {
namespace {

class ConvertReshapeTest : public ::testing::TestWithParam<TfLiteType> {
 protected:
  void SetUp() override {
    delegate_ = CreateStubDelegate();
    ASSERT_TRUE(delegate_);
  }

  void TearDown() override { DeleteStubDelegate(delegate_); }

  TfLiteDelegate* delegate_;
};

TEST_P(ConvertReshapeTest, LoadModelAndRunInference) {
  // Generate a model with a reshape op.
  SingleOpInterpreterBuilder model(kTfLiteBuiltinReshape);
  model.AddInput(GetParam(), {4, 4});
  model.AddOutput(GetParam(), {2, 8});
  TfLiteReshapeParams* params = reinterpret_cast<TfLiteReshapeParams*>(
      calloc(1, sizeof(TfLiteReshapeParams)));
  params->num_dimensions = 2;
  params->shape[0] = 2;
  params->shape[1] = 8;
  model.SetParameters(params);

  // Build the interpreter and delegate it.
  std::unique_ptr<::tflite::Interpreter> interpreter = model.Build();
  ASSERT_TRUE(interpreter);
  ASSERT_EQ(interpreter->ModifyGraphWithDelegate(delegate_), kTfLiteOk);

  // Inspect the IrModel generated by the delegate.
  const ::ml_drift::ir::IrModel* ir_model = GetIrModel(delegate_);
  ASSERT_TRUE(ir_model);
  EXPECT_EQ(ir_model->inputs().size(), 1);
  EXPECT_EQ(ir_model->outputs().size(), 1);
  ASSERT_EQ(ir_model->ops().size(), 1);
  const ::ml_drift::ir::IrOp* ir_op =
      ir_model->op(ir_model->ops()[0]->id);
  EXPECT_EQ(ir_op->inputs.size(), 1);
  EXPECT_EQ(ir_op->outputs.size(), 1);
  EXPECT_EQ(ir_op->name, "reshape");
  const ::ml_drift::ReshapeAttributes* attr =
      std::any_cast<::ml_drift::ReshapeAttributes>(&ir_op->attr);
  ASSERT_TRUE(attr);
  EXPECT_EQ(attr->new_shape, ::ml_drift::BHWC(2, 1, 1, 8));

  // Sanity check inference.
  ASSERT_EQ(interpreter->AllocateTensors(), kTfLiteOk);
  ASSERT_EQ(interpreter->Invoke(), kTfLiteOk);
}

TEST_P(ConvertReshapeTest, LoadModelAndRunInference5D) {
  // Generate a model with a reshape op.
  SingleOpInterpreterBuilder model(kTfLiteBuiltinReshape);
  model.AddInput(GetParam(), {1, 2, 2, 2});
  model.AddOutput(GetParam(), {1, 1, 2, 2, 2});
  TfLiteReshapeParams* params = reinterpret_cast<TfLiteReshapeParams*>(
      calloc(1, sizeof(TfLiteReshapeParams)));
  params->num_dimensions = 5;
  params->shape[0] = 1;
  params->shape[1] = 1;
  params->shape[2] = 2;
  params->shape[3] = 2;
  params->shape[4] = 2;
  model.SetParameters(params);

  // Build the interpreter and delegate it.
  std::unique_ptr<::tflite::Interpreter> interpreter = model.Build();
  ASSERT_TRUE(interpreter);
  ASSERT_EQ(interpreter->ModifyGraphWithDelegate(delegate_), kTfLiteOk);

  // Inspect the IrModel generated by the delegate.
  const ::ml_drift::ir::IrModel* ir_model = GetIrModel(delegate_);
  ASSERT_TRUE(ir_model);
  EXPECT_EQ(ir_model->inputs().size(), 1);
  EXPECT_EQ(ir_model->outputs().size(), 1);
  ASSERT_EQ(ir_model->ops().size(), 1);
  const ::ml_drift::ir::IrOp* ir_op = ir_model->op(ir_model->ops()[0]->id);
  EXPECT_EQ(ir_op->inputs.size(), 1);
  EXPECT_EQ(ir_op->outputs.size(), 1);
  EXPECT_EQ(ir_op->name, "reshape");
  const ::ml_drift::Reshape3DAttributes* attr =
      std::any_cast<::ml_drift::Reshape3DAttributes>(&ir_op->attr);
  ASSERT_TRUE(attr);
  EXPECT_EQ(attr->new_shape, ::ml_drift::BHWDC(1, 1, 2, 2, 2));

  // Sanity check inference.
  ASSERT_EQ(interpreter->AllocateTensors(), kTfLiteOk);
  ASSERT_EQ(interpreter->Invoke(), kTfLiteOk);
}

TEST_F(ConvertReshapeTest, ReshapeWithOffsetTensorId) {
  // Generate a model with a reshape op, but add an unused input first to offset
  // the tensor IDs.
  SingleOpInterpreterBuilder model(kTfLiteBuiltinReshape);
  model.AddInput(kTfLiteFloat32, {1});      // Tensor 0: Dummy
  model.AddInput(kTfLiteFloat32, {4, 4});   // Tensor 1: Actual Input
  model.AddOutput(kTfLiteFloat32, {2, 8});  // Tensor 2: Actual Output
  TfLiteReshapeParams* params = reinterpret_cast<TfLiteReshapeParams*>(
      calloc(1, sizeof(TfLiteReshapeParams)));
  params->num_dimensions = 2;
  params->shape[0] = 2;
  params->shape[1] = 8;
  model.SetParameters(params);

  // Build the interpreter using only the actual input tensor.
  // This will result in TFLite tensor IDs [1] -> [2] for the delegated node.
  std::unique_ptr<::tflite::Interpreter> interpreter = model.Build({1});
  ASSERT_TRUE(interpreter);
  ASSERT_EQ(interpreter->ModifyGraphWithDelegate(delegate_), kTfLiteOk);

  // Inspect the IrModel generated by the delegate.
  const ::ml_drift::ir::IrModel* ir_model = GetIrModel(delegate_);
  ASSERT_TRUE(ir_model);
  ASSERT_EQ(ir_model->ops().size(), 1);
  const ::ml_drift::ir::IrOp* ir_op = ir_model->op(ir_model->ops()[0]->id);
  EXPECT_EQ(ir_op->name, "reshape");

  // Verify that attributes were correctly extracted from the output tensor.
  // Without the fix in convert_reshape.cc, this would have segfaulted because
  // it would try to access ir_model->tensor(2) instead of ir_model->tensor(1).
  const ::ml_drift::ReshapeAttributes* attr =
      std::any_cast<::ml_drift::ReshapeAttributes>(&ir_op->attr);
  ASSERT_TRUE(attr);
  EXPECT_EQ(attr->new_shape, ::ml_drift::BHWC(2, 1, 1, 8));
}

INSTANTIATE_TEST_SUITE_P(ConvertReshapeTest, ConvertReshapeTest,
                         ::testing::Values(  // clang-format off
      // go/keep-sorted start numeric=yes
      kTfLiteBool,
      kTfLiteFloat16,
      kTfLiteFloat32,
      kTfLiteInt8,
      kTfLiteInt16,
      kTfLiteInt32,
      kTfLiteUInt8,
      kTfLiteUInt16,
      kTfLiteUInt32
      // go/keep-sorted end
      // clang-format on
));

}  // namespace
}  // namespace litert::ml_drift::ir
