// Copyright 2026 Google LLC.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#include <any>
#include <cstdint>
#include <cstdlib>
#include <cstring>
#include <limits>
#include <memory>
#include <vector>

#include "testing/base/public/gunit.h"
#include "ml_drift/common/ir_model.h"  // from @ml_drift
#include "ml_drift/common/operations.h"  // from @ml_drift
#include "ml_drift/common/shape.h"  // from @ml_drift
#include "ml_drift/common/types.h"  // from @ml_drift
#include "third_party/odml/litert/ml_drift/tflite/convert/convert_testing_utils.h"
#include "third_party/odml/litert/ml_drift/tflite/convert/stub_delegate.h"
#include "third_party/odml/litert/ml_drift/tflite/ir_model_builder_helper.h"
#include "tflite/builtin_ops.h"
#include "tflite/c/builtin_op_data.h"
#include "tflite/c/c_api.h"
#include "tflite/c/common.h"
#include "tflite/interpreter.h"

namespace litert::ml_drift::ir {
namespace {

class ConvertPadTest : public ::testing::TestWithParam<TfLiteType> {
 protected:
  void SetUp() override {
    delegate_ = CreateStubDelegate();
    ASSERT_TRUE(delegate_);
  }

  void TearDown() override { DeleteStubDelegate(delegate_); }

  TfLiteDelegate* delegate_;
};

TEST_P(ConvertPadTest, BasicPad) {
  // Generate a model with a pad op.
  SingleOpInterpreterBuilder model(kTfLiteBuiltinPad, /*version=*/1);
  model.AddInput(GetParam(), {1, 2, 3, 4});  // input data
  std::vector<int32_t> paddings = {
      0, 0,  // batch
      1, 1,  // height
      1, 1,  // width
      0, 0   // channels
  };
  std::vector<uint8_t> paddings_bytes(paddings.size() * sizeof(int32_t));
  std::memcpy(paddings_bytes.data(), paddings.data(), paddings_bytes.size());
  model.AddConstInput(kTfLiteInt32, {4, 2}, paddings_bytes);  // paddings
  model.AddOutput(GetParam(), {1, 4, 5, 4});
  TfLitePadParams* params =
      reinterpret_cast<TfLitePadParams*>(calloc(1, sizeof(TfLitePadParams)));
  model.SetParameters(params);

  // Build the interpreter and delegate it.
  std::unique_ptr<::tflite::Interpreter> interpreter = model.Build();
  ASSERT_TRUE(interpreter);
  ASSERT_EQ(interpreter->ModifyGraphWithDelegate(delegate_), kTfLiteOk);

  // Inspect the IrModel generated by the delegate.
  const ::ml_drift::ir::IrModel* ir_model = GetIrModel(delegate_);
  ASSERT_TRUE(ir_model);
  EXPECT_EQ(ir_model->inputs().size(), 1);
  EXPECT_EQ(ir_model->outputs().size(), 1);
  // Constants are parsed into attr
  ASSERT_EQ(ir_model->ops().size(), 1);

  const ::ml_drift::ir::IrOp* pad_op = ir_model->op(0);
  EXPECT_EQ(pad_op->name, "pad");
  const ::ml_drift::PadAttributes* attr =
      std::any_cast<::ml_drift::PadAttributes>(&pad_op->attr);
  ASSERT_TRUE(attr);
  EXPECT_EQ(attr->type, ::ml_drift::PaddingContentType::ZEROS);
  EXPECT_EQ(attr->prepended.h, 1);
  EXPECT_EQ(attr->prepended.w, 1);
  EXPECT_EQ(attr->appended.h, 1);
  EXPECT_EQ(attr->appended.w, 1);

  // Sanity check inference.
  ASSERT_EQ(interpreter->AllocateTensors(), kTfLiteOk);
  ASSERT_EQ(interpreter->Invoke(), kTfLiteOk);
}

TEST_P(ConvertPadTest, BasicPad3x2) {
  // Generate a model with a pad op and 3D input -> 3x2 padding tensor.
  SingleOpInterpreterBuilder model(kTfLiteBuiltinPad, /*version=*/1);
  model.AddInput(GetParam(), {2, 3, 4});  // 3D input data
  std::vector<int32_t> paddings = {
      1, 2,  // height
      3, 1,  // width
      0, 0   // channels
  };
  std::vector<uint8_t> paddings_bytes(paddings.size() * sizeof(int32_t));
  std::memcpy(paddings_bytes.data(), paddings.data(), paddings_bytes.size());
  model.AddConstInput(kTfLiteInt32, {3, 2}, paddings_bytes);  // 3x2 paddings
  model.AddOutput(GetParam(), {5, 7, 4});
  TfLitePadParams* params =
      reinterpret_cast<TfLitePadParams*>(calloc(1, sizeof(TfLitePadParams)));
  model.SetParameters(params);

  // Build the interpreter and delegate it.
  std::unique_ptr<::tflite::Interpreter> interpreter = model.Build();
  ASSERT_TRUE(interpreter);
  ASSERT_EQ(interpreter->ModifyGraphWithDelegate(delegate_), kTfLiteOk);

  // Inspect the IrModel generated by the delegate.
  const ::ml_drift::ir::IrModel* ir_model = GetIrModel(delegate_);
  ASSERT_TRUE(ir_model);
  EXPECT_EQ(ir_model->inputs().size(), 1);
  EXPECT_EQ(ir_model->outputs().size(), 1);
  ASSERT_EQ(ir_model->ops().size(), 1);

  const ::ml_drift::ir::IrOp* pad_op = ir_model->op(0);
  EXPECT_EQ(pad_op->name, "pad");
  const ::ml_drift::PadAttributes* attr =
      std::any_cast<::ml_drift::PadAttributes>(&pad_op->attr);
  ASSERT_TRUE(attr);
  EXPECT_EQ(attr->type, ::ml_drift::PaddingContentType::ZEROS);

  // For 3x2, prepended/appended b is implicitly 1 based on mapping.
  EXPECT_EQ(attr->prepended.b, 1);
  EXPECT_EQ(attr->prepended.h, 1);
  EXPECT_EQ(attr->prepended.w, 3);
  EXPECT_EQ(attr->prepended.c, 0);

  EXPECT_EQ(attr->appended.b, 1);
  EXPECT_EQ(attr->appended.h, 2);
  EXPECT_EQ(attr->appended.w, 1);
  EXPECT_EQ(attr->appended.c, 0);

  // Sanity check inference.
  ASSERT_EQ(interpreter->AllocateTensors(), kTfLiteOk);
  ASSERT_EQ(interpreter->Invoke(), kTfLiteOk);
}

TEST_P(ConvertPadTest, PadV2) {
  if (GetParam() != kTfLiteFloat32) {
    GTEST_SKIP()
        << "Skipping constant input test for non-float32 types for simplicity.";
  }
  // Generate a model with a pad op.
  SingleOpInterpreterBuilder model(kTfLiteBuiltinPadv2, /*version=*/1);
  model.AddInput(kTfLiteFloat32, {1, 2, 3, 4});  // input data
  std::vector<int32_t> paddings = {
      0, 0,  // batch
      1, 2,  // height
      3, 4,  // width
      0, 0   // channels
  };
  std::vector<uint8_t> paddings_bytes(paddings.size() * sizeof(int32_t));
  std::memcpy(paddings_bytes.data(), paddings.data(), paddings_bytes.size());
  model.AddConstInput(kTfLiteInt32, {4, 2}, paddings_bytes);  // paddings

  std::vector<float> const_val = {3.14f};
  std::vector<uint8_t> const_val_bytes(sizeof(float));
  std::memcpy(const_val_bytes.data(), const_val.data(), sizeof(float));
  model.AddConstInput(kTfLiteFloat32, {1}, const_val_bytes);  // constant_values

  model.AddOutput(kTfLiteFloat32, {1, 5, 10, 4});
  TfLitePadV2Params* params = reinterpret_cast<TfLitePadV2Params*>(
      calloc(1, sizeof(TfLitePadV2Params)));
  model.SetParameters(params);

  // Build the interpreter and delegate it.
  std::unique_ptr<::tflite::Interpreter> interpreter = model.Build();
  ASSERT_TRUE(interpreter);
  ASSERT_EQ(interpreter->ModifyGraphWithDelegate(delegate_), kTfLiteOk);

  // Inspect the IrModel generated by the delegate.
  const ::ml_drift::ir::IrModel* ir_model = GetIrModel(delegate_);
  ASSERT_TRUE(ir_model);
  EXPECT_EQ(ir_model->ops().size(), 1);  // Only pad op

  const ::ml_drift::ir::IrOp* pad_op = ir_model->op(0);
  EXPECT_EQ(pad_op->name, "pad");
  const ::ml_drift::PadAttributes* attr =
      std::any_cast<::ml_drift::PadAttributes>(&pad_op->attr);
  ASSERT_TRUE(attr);
  EXPECT_EQ(attr->type, ::ml_drift::PaddingContentType::ZEROS);
  EXPECT_FLOAT_EQ(attr->constant_values, 3.14f);
  EXPECT_EQ(attr->prepended.h, 1);
  EXPECT_EQ(attr->prepended.w, 3);
  EXPECT_EQ(attr->appended.h, 2);
  EXPECT_EQ(attr->appended.w, 4);

  // Sanity check inference.
  ASSERT_EQ(interpreter->AllocateTensors(), kTfLiteOk);
  ASSERT_EQ(interpreter->Invoke(), kTfLiteOk);
}

TEST_P(ConvertPadTest, MirrorPad) {
  // Generate a model with a mirror pad op.
  SingleOpInterpreterBuilder model(kTfLiteBuiltinMirrorPad, /*version=*/1);
  model.AddInput(GetParam(), {1, 2, 3, 4});  // input data
  std::vector<int32_t> paddings = {
      0, 0,  // batch
      1, 1,  // height
      1, 1,  // width
      0, 0   // channels
  };
  std::vector<uint8_t> paddings_bytes(paddings.size() * sizeof(int32_t));
  std::memcpy(paddings_bytes.data(), paddings.data(), paddings_bytes.size());
  model.AddConstInput(kTfLiteInt32, {4, 2}, paddings_bytes);  // paddings
  model.AddOutput(GetParam(), {1, 4, 5, 4});
  TfLiteMirrorPaddingParams* params =
      reinterpret_cast<TfLiteMirrorPaddingParams*>(
          calloc(1, sizeof(TfLiteMirrorPaddingParams)));
  params->mode = TfLiteMirrorPaddingMode::kTfLiteMirrorPaddingReflect;
  model.SetParameters(params);

  // Build the interpreter and delegate it.
  std::unique_ptr<::tflite::Interpreter> interpreter = model.Build();
  ASSERT_TRUE(interpreter);
  ASSERT_EQ(interpreter->ModifyGraphWithDelegate(delegate_), kTfLiteOk);

  // Inspect the IrModel generated by the delegate.
  const ::ml_drift::ir::IrModel* ir_model = GetIrModel(delegate_);
  ASSERT_TRUE(ir_model);
  ASSERT_EQ(ir_model->ops().size(), 1);
  const ::ml_drift::ir::IrOp* pad_op = ir_model->op(0);
  EXPECT_EQ(pad_op->name, "pad");
  const ::ml_drift::PadAttributes* attr =
      std::any_cast<::ml_drift::PadAttributes>(&pad_op->attr);
  ASSERT_TRUE(attr);
  EXPECT_EQ(attr->type, ::ml_drift::PaddingContentType::REFLECT);

  // Sanity check inference.
  ASSERT_EQ(interpreter->AllocateTensors(), kTfLiteOk);
  ASSERT_EQ(interpreter->Invoke(), kTfLiteOk);
}

TEST_P(ConvertPadTest, PadV2WithCapping) {
  if (GetParam() != kTfLiteFloat32) {
    GTEST_SKIP()
        << "Skipping constant input test for non-float32 types for simplicity.";
  }
  // Generate a model with a pad op.
  SingleOpInterpreterBuilder model(kTfLiteBuiltinPadv2, /*version=*/1);
  model.AddInput(kTfLiteFloat16, {1, 2, 3, 4});  // fp16 input data
  std::vector<int32_t> paddings = {
      0, 0,  // batch
      1, 2,  // height
      3, 4,  // width
      0, 0   // channels
  };
  std::vector<uint8_t> paddings_bytes(paddings.size() * sizeof(int32_t));
  std::memcpy(paddings_bytes.data(), paddings.data(), paddings_bytes.size());
  model.AddConstInput(kTfLiteInt32, {4, 2}, paddings_bytes);  // paddings

  std::vector<uint16_t> const_val = {0x7C00};  // float16 representation of +inf
  std::vector<uint8_t> const_val_bytes(sizeof(uint16_t));
  std::memcpy(const_val_bytes.data(), const_val.data(), sizeof(uint16_t));
  model.AddConstInput(kTfLiteFloat16, {1}, const_val_bytes);  // constant_values

  model.AddOutput(kTfLiteFloat16, {1, 5, 10, 4});
  TfLitePadV2Params* params = reinterpret_cast<TfLitePadV2Params*>(
      calloc(1, sizeof(TfLitePadV2Params)));
  model.SetParameters(params);

  // Set options to enable capping
  IrModelBuilderOptions options;
  options.enable_infinite_float_capping = true;
  options.enable_reduced_precision = false;
  TfLiteDelegate* local_delegate = CreateStubDelegate(options);

  // Build the interpreter and delegate it.
  std::unique_ptr<::tflite::Interpreter> interpreter = model.Build();
  ASSERT_TRUE(interpreter);
  ASSERT_EQ(interpreter->ModifyGraphWithDelegate(local_delegate), kTfLiteOk);

  // Inspect the IrModel generated by the delegate.
  const ::ml_drift::ir::IrModel* ir_model = GetIrModel(local_delegate);
  ASSERT_TRUE(ir_model);
  EXPECT_EQ(ir_model->ops().size(), 1);  // Only pad op

  const ::ml_drift::ir::IrOp* pad_op = ir_model->op(0);
  EXPECT_EQ(pad_op->name, "pad");
  const ::ml_drift::PadAttributes* attr =
      std::any_cast<::ml_drift::PadAttributes>(&pad_op->attr);
  ASSERT_TRUE(attr);
  EXPECT_EQ(attr->type, ::ml_drift::PaddingContentType::ZEROS);

  // enable_reduced_precision is false, so we use max float
  EXPECT_FLOAT_EQ(attr->constant_values, ::ml_drift::kMaxHalf);

  interpreter.reset();
  DeleteStubDelegate(local_delegate);
}

TEST_P(ConvertPadTest, PadV2WithCappingNegInf) {
  if (GetParam() != kTfLiteFloat32) {
    GTEST_SKIP()
        << "Skipping constant input test for non-float32 types for simplicity.";
  }
  // Generate a model with a pad op.
  SingleOpInterpreterBuilder model(kTfLiteBuiltinPadv2, /*version=*/1);
  model.AddInput(kTfLiteFloat32, {1, 2, 3, 4});  // fp32 input data
  std::vector<int32_t> paddings = {
      0, 0,  // batch
      1, 2,  // height
      3, 4,  // width
      0, 0   // channels
  };
  std::vector<uint8_t> paddings_bytes(paddings.size() * sizeof(int32_t));
  std::memcpy(paddings_bytes.data(), paddings.data(), paddings_bytes.size());
  model.AddConstInput(kTfLiteInt32, {4, 2}, paddings_bytes);  // paddings

  std::vector<float> const_val = {-std::numeric_limits<float>::infinity()};
  std::vector<uint8_t> const_val_bytes(sizeof(float));
  std::memcpy(const_val_bytes.data(), const_val.data(), sizeof(float));
  model.AddConstInput(kTfLiteFloat32, {1}, const_val_bytes);  // constant_values

  model.AddOutput(kTfLiteFloat32, {1, 5, 10, 4});
  TfLitePadV2Params* params = reinterpret_cast<TfLitePadV2Params*>(
      calloc(1, sizeof(TfLitePadV2Params)));
  model.SetParameters(params);

  // Set options to enable capping
  IrModelBuilderOptions options;
  options.enable_infinite_float_capping = true;
  options.enable_reduced_precision = true;
  TfLiteDelegate* local_delegate = CreateStubDelegate(options);

  // Build the interpreter and delegate it.
  std::unique_ptr<::tflite::Interpreter> interpreter = model.Build();
  ASSERT_TRUE(interpreter);
  ASSERT_EQ(interpreter->ModifyGraphWithDelegate(local_delegate), kTfLiteOk);

  // Inspect the IrModel generated by the delegate.
  const ::ml_drift::ir::IrModel* ir_model = GetIrModel(local_delegate);
  ASSERT_TRUE(ir_model);
  EXPECT_EQ(ir_model->ops().size(), 1);  // Only pad op

  const ::ml_drift::ir::IrOp* pad_op = ir_model->op(0);
  EXPECT_EQ(pad_op->name, "pad");
  const ::ml_drift::PadAttributes* attr =
      std::any_cast<::ml_drift::PadAttributes>(&pad_op->attr);
  ASSERT_TRUE(attr);
  EXPECT_EQ(attr->type, ::ml_drift::PaddingContentType::ZEROS);

  // enable_reduced_precision means we use -kMaxHalf
  EXPECT_FLOAT_EQ(attr->constant_values, -::ml_drift::kMaxHalf);

  interpreter.reset();
  DeleteStubDelegate(local_delegate);
}

INSTANTIATE_TEST_SUITE_P(ConvertPadTest, ConvertPadTest,
                         ::testing::Values(  // clang-format off
      // go/keep-sorted start numeric=yes
      kTfLiteBFloat16,
      kTfLiteBool,
      kTfLiteFloat16,
      kTfLiteFloat32,
      kTfLiteInt8,
      kTfLiteInt16,
      kTfLiteInt32,
      kTfLiteUInt8,
      kTfLiteUInt16,
      kTfLiteUInt32
      // go/keep-sorted end
                                             // clang-format on
                             ));

}  // namespace
}  // namespace litert::ml_drift::ir
