// Copyright 2025 Google LLC.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#include <any>
#include <memory>
#include <vector>

#include "testing/base/public/gunit.h"
#include "ml_drift/common/ir_model.h"  // from @ml_drift
#include "ml_drift/common/operations.h"  // from @ml_drift
#include "ml_drift/common/shape.h"  // from @ml_drift
#include "third_party/odml/litert/ml_drift/tflite/convert/convert_testing_utils.h"
#include "third_party/odml/litert/ml_drift/tflite/convert/stub_delegate.h"
#include "tflite/builtin_ops.h"
#include "tflite/c/builtin_op_data.h"
#include "tflite/c/c_api.h"
#include "tflite/c/common.h"
#include "tflite/interpreter.h"

namespace litert::ml_drift::ir {
namespace {

class ConvertBroadcastInDimTest : public ::testing::TestWithParam<TfLiteType> {
 protected:
  void SetUp() override {
    delegate_ = CreateStubDelegate();
    ASSERT_TRUE(delegate_);
  }

  void TearDown() override { DeleteStubDelegate(delegate_); }

  TfLiteDelegate* delegate_;
};

TEST_P(ConvertBroadcastInDimTest, LoadModelAndRunInference) {
  // Generate a model with a broadcast_in_dim op.
  SingleOpInterpreterBuilder model(kTfLiteBuiltinStablehloBroadcastInDim,
                                   /*version=*/1);
  model.AddInput(GetParam(), {1, 2, 3, 4});  // input data
  model.AddInput(kTfLiteInt32, {4});         // broadcast_dimensions
  model.AddOutput(GetParam(), {1, 2, 3, 4});
  std::vector<int> broadcast_dims_data = {0, 1, 2, 3};

  // Build the interpreter and delegate it.
  std::unique_ptr<::tflite::Interpreter> interpreter = model.Build();
  ASSERT_TRUE(interpreter);

  TfLiteTensor* const_tensor = interpreter->tensor(interpreter->inputs()[1]);
  const_tensor->allocation_type = kTfLiteMmapRo;
  const_tensor->data.i32 = broadcast_dims_data.data();

  ASSERT_EQ(interpreter->ModifyGraphWithDelegate(delegate_), kTfLiteOk);

  // Inspect the IrModel generated by the delegate.
  const ::ml_drift::ir::IrModel* ir_model = GetIrModel(delegate_);
  ASSERT_TRUE(ir_model);
  EXPECT_EQ(ir_model->inputs().size(), 1);
  EXPECT_EQ(ir_model->outputs().size(), 1);
  ASSERT_EQ(ir_model->ops().size(), 1);
  const ::ml_drift::ir::IrOp* transpose_op = ir_model->op(0);
  EXPECT_EQ(transpose_op->inputs.size(), 1);
  EXPECT_EQ(transpose_op->outputs.size(), 1);
  EXPECT_EQ(transpose_op->name, "transpose");
  const ::ml_drift::Transpose3DAttributes* attr =
      std::any_cast<::ml_drift::Transpose3DAttributes>(&transpose_op->attr);
  ASSERT_TRUE(attr);
  EXPECT_EQ(attr->perm, ::ml_drift::BHWDC(0, 1, 2, 3, 4));

  // Sanity check inference.
  ASSERT_EQ(interpreter->AllocateTensors(), kTfLiteOk);
  ASSERT_EQ(interpreter->Invoke(), kTfLiteOk);
}

TEST_P(ConvertBroadcastInDimTest, BroadcastWithTile) {
  // Generate a model with a broadcast_in_dim op.
  SingleOpInterpreterBuilder model(kTfLiteBuiltinStablehloBroadcastInDim,
                                   /*version=*/1);
  model.AddInput(GetParam(), {1, 2, 3, 1});  // input data
  model.AddInput(kTfLiteInt32, {4});         // broadcast_dimensions
  model.AddOutput(GetParam(), {1, 2, 3, 4});
  std::vector<int> broadcast_dims_data = {0, 1, 2, 3};

  // Build the interpreter and delegate it.
  std::unique_ptr<::tflite::Interpreter> interpreter = model.Build();
  ASSERT_TRUE(interpreter);

  // Set input 1 as constant tensor with data.
  // This requires hacking allocation type and data, because
  // SingleOpInterpreterBuilder doesn't support constant inputs.
  TfLiteTensor* const_tensor = interpreter->tensor(interpreter->inputs()[1]);
  const_tensor->allocation_type = kTfLiteMmapRo;
  const_tensor->data.i32 = broadcast_dims_data.data();

  ASSERT_EQ(interpreter->ModifyGraphWithDelegate(delegate_), kTfLiteOk);

  // Inspect the IrModel generated by the delegate.
  const ::ml_drift::ir::IrModel* ir_model = GetIrModel(delegate_);
  ASSERT_TRUE(ir_model);
  EXPECT_EQ(ir_model->inputs().size(), 1);
  EXPECT_EQ(ir_model->outputs().size(), 1);
  ASSERT_EQ(ir_model->ops().size(), 2);
  const ::ml_drift::ir::IrOp* transpose_op = ir_model->op(0);
  EXPECT_EQ(transpose_op->inputs.size(), 1);
  EXPECT_EQ(transpose_op->outputs.size(), 1);
  EXPECT_EQ(transpose_op->name, "transpose");
  const ::ml_drift::Transpose3DAttributes* attr =
      std::any_cast<::ml_drift::Transpose3DAttributes>(&transpose_op->attr);
  ASSERT_TRUE(attr);
  EXPECT_EQ(attr->perm, ::ml_drift::BHWDC(0, 1, 2, 3, 4));
  const ::ml_drift::ir::IrOp* tile_op = ir_model->op(1);
  EXPECT_EQ(tile_op->inputs.size(), 1);
  EXPECT_EQ(tile_op->outputs.size(), 1);
  EXPECT_EQ(tile_op->name, "tile");

  // Sanity check inference.
  ASSERT_EQ(interpreter->AllocateTensors(), kTfLiteOk);
  ASSERT_EQ(interpreter->Invoke(), kTfLiteOk);
}

bool CanTile(const ::ml_drift::ir::IrTensor& in_tensor,
             const ::ml_drift::ir::IrTensor& out_tensor) {
  const ::ml_drift::BHWDC in_shape = in_tensor.desc.GetBHWDCShape();
  const ::ml_drift::BHWDC out_shape = out_tensor.desc.GetBHWDCShape();
  if (in_shape.b != 1 && in_shape.b != out_shape.b) return false;
  if (in_shape.h != 1 && in_shape.h != out_shape.h) return false;
  if (in_shape.w != 1 && in_shape.w != out_shape.w) return false;
  if (in_shape.d != 1 && in_shape.d != out_shape.d) return false;
  if (in_shape.c != 1 && in_shape.c != out_shape.c) return false;
  return true;
}

TEST_P(ConvertBroadcastInDimTest, Permute) {
  // Generate a model with a broadcast_in_dim op.
  SingleOpInterpreterBuilder model(kTfLiteBuiltinStablehloBroadcastInDim,
                                   /*version=*/1);
  model.AddInput(GetParam(), {1, 10, 20, 30});  // input data
  model.AddInput(kTfLiteInt32, {4});            // broadcast_dimensions
  model.AddOutput(GetParam(), {1, 10, 30, 20});
  std::vector<int> broadcast_dims_data = {0, 1, 3, 2};

  // Build the interpreter and delegate it.
  std::unique_ptr<::tflite::Interpreter> interpreter = model.Build();
  ASSERT_TRUE(interpreter);

  TfLiteTensor* const_tensor = interpreter->tensor(interpreter->inputs()[1]);
  const_tensor->allocation_type = kTfLiteMmapRo;
  const_tensor->data.i32 = broadcast_dims_data.data();

  ASSERT_EQ(interpreter->ModifyGraphWithDelegate(delegate_), kTfLiteOk);

  // Inspect the IrModel generated by the delegate.
  const ::ml_drift::ir::IrModel* ir_model = GetIrModel(delegate_);
  ASSERT_TRUE(ir_model);
  EXPECT_EQ(ir_model->inputs().size(), 1);
  EXPECT_EQ(ir_model->outputs().size(), 1);
  ASSERT_EQ(ir_model->ops().size(), 1);
  const ::ml_drift::ir::IrOp* transpose_op = ir_model->op(0);
  EXPECT_EQ(transpose_op->inputs.size(), 1);
  EXPECT_EQ(transpose_op->outputs.size(), 1);
  EXPECT_EQ(transpose_op->name, "transpose");
  const ::ml_drift::Transpose3DAttributes* attr =
      std::any_cast<::ml_drift::Transpose3DAttributes>(&transpose_op->attr);
  ASSERT_TRUE(attr);
  EXPECT_EQ(attr->perm, ::ml_drift::BHWDC(0, 1, 4, 3, 2));

  // Sanity check inference.
  ASSERT_EQ(interpreter->AllocateTensors(), kTfLiteOk);
  ASSERT_EQ(interpreter->Invoke(), kTfLiteOk);
}

// Want to make sure we broadcast correctly taking into account the layout of
// the tensor.
TEST_P(ConvertBroadcastInDimTest, IndicesWithMapHW) {
  // Generate a model with a broadcast_in_dim op.
  SingleOpInterpreterBuilder model(kTfLiteBuiltinStablehloBroadcastInDim,
                                   /*version=*/1);
  model.AddInput(GetParam(), {1});    // input data
  model.AddInput(kTfLiteInt32, {1});  // broadcast_dimensions
  model.AddOutput(GetParam(), {1, 4});
  std::vector<int> broadcast_dims_data = {1};

  // Build the interpreter and delegate it.
  std::unique_ptr<::tflite::Interpreter> interpreter = model.Build();
  ASSERT_TRUE(interpreter);

  // Set input 1 as constant tensor with data.
  // This requires hacking allocation type and data, because
  // SingleOpInterpreterBuilder doesn't support constant inputs.
  TfLiteTensor* const_tensor = interpreter->tensor(interpreter->inputs()[1]);
  const_tensor->allocation_type = kTfLiteMmapRo;
  const_tensor->data.i32 = broadcast_dims_data.data();

  ASSERT_EQ(interpreter->ModifyGraphWithDelegate(delegate_), kTfLiteOk);

  // Inspect the IrModel generated by the delegate.
  const ::ml_drift::ir::IrModel* ir_model = GetIrModel(delegate_);
  ASSERT_TRUE(ir_model);
  EXPECT_EQ(ir_model->inputs().size(), 1);
  EXPECT_EQ(ir_model->outputs().size(), 1);
  ASSERT_EQ(ir_model->ops().size(), 2);
  const ::ml_drift::ir::IrOp* transpose_op = ir_model->op(0);
  EXPECT_EQ(transpose_op->inputs.size(), 1);
  EXPECT_EQ(transpose_op->outputs.size(), 1);
  EXPECT_EQ(transpose_op->name, "transpose");
  const ::ml_drift::Transpose3DAttributes* attr =
      std::any_cast<::ml_drift::Transpose3DAttributes>(&transpose_op->attr);
  ASSERT_TRUE(attr);

  const ::ml_drift::ir::IrOp* tile_op = ir_model->op(1);
  const ::ml_drift::ir::IrTensor* tile_in =
      ir_model->tensor(tile_op->inputs[0]);
  const ::ml_drift::ir::IrTensor* tile_out =
      ir_model->tensor(tile_op->outputs[0]);
  EXPECT_TRUE(CanTile(*tile_in, *tile_out));

  // Sanity check inference.
  ASSERT_EQ(interpreter->AllocateTensors(), kTfLiteOk);
  ASSERT_EQ(interpreter->Invoke(), kTfLiteOk);
}

TEST_P(ConvertBroadcastInDimTest, IndicesWithMapHWC) {
  // Generate a model with a broadcast_in_dim op.
  SingleOpInterpreterBuilder model(kTfLiteBuiltinStablehloBroadcastInDim,
                                   /*version=*/1);
  model.AddInput(GetParam(), {1});    // input data
  model.AddInput(kTfLiteInt32, {1});  // broadcast_dimensions
  model.AddOutput(GetParam(), {1, 4, 1});
  std::vector<int> broadcast_dims_data = {1};

  // Build the interpreter and delegate it.
  std::unique_ptr<::tflite::Interpreter> interpreter = model.Build();
  ASSERT_TRUE(interpreter);

  // Set input 1 as constant tensor with data.
  // This requires hacking allocation type and data, because
  // SingleOpInterpreterBuilder doesn't support constant inputs.
  TfLiteTensor* const_tensor = interpreter->tensor(interpreter->inputs()[1]);
  const_tensor->allocation_type = kTfLiteMmapRo;
  const_tensor->data.i32 = broadcast_dims_data.data();

  ASSERT_EQ(interpreter->ModifyGraphWithDelegate(delegate_), kTfLiteOk);

  // Inspect the IrModel generated by the delegate.
  const ::ml_drift::ir::IrModel* ir_model = GetIrModel(delegate_);
  ASSERT_TRUE(ir_model);
  EXPECT_EQ(ir_model->inputs().size(), 1);
  EXPECT_EQ(ir_model->outputs().size(), 1);
  ASSERT_EQ(ir_model->ops().size(), 2);
  const ::ml_drift::ir::IrOp* transpose_op = ir_model->op(0);
  EXPECT_EQ(transpose_op->inputs.size(), 1);
  EXPECT_EQ(transpose_op->outputs.size(), 1);
  EXPECT_EQ(transpose_op->name, "transpose");
  const ::ml_drift::Transpose3DAttributes* attr =
      std::any_cast<::ml_drift::Transpose3DAttributes>(&transpose_op->attr);
  ASSERT_TRUE(attr);

  const ::ml_drift::ir::IrOp* tile_op = ir_model->op(1);
  const ::ml_drift::ir::IrTensor* tile_in =
      ir_model->tensor(tile_op->inputs[0]);
  const ::ml_drift::ir::IrTensor* tile_out =
      ir_model->tensor(tile_op->outputs[0]);
  EXPECT_TRUE(CanTile(*tile_in, *tile_out));

  // Sanity check inference.
  ASSERT_EQ(interpreter->AllocateTensors(), kTfLiteOk);
  ASSERT_EQ(interpreter->Invoke(), kTfLiteOk);
}

TEST_P(ConvertBroadcastInDimTest, IndicesWithMapBHWC) {
  // Generate a model with a broadcast_in_dim op.
  SingleOpInterpreterBuilder model(kTfLiteBuiltinStablehloBroadcastInDim,
                                   /*version=*/1);
  model.AddInput(GetParam(), {1});    // input data
  model.AddInput(kTfLiteInt32, {1});  // broadcast_dimensions
  model.AddOutput(GetParam(), {1, 4, 1, 1});
  std::vector<int> broadcast_dims_data = {1};

  // Build the interpreter and delegate it.
  std::unique_ptr<::tflite::Interpreter> interpreter = model.Build();
  ASSERT_TRUE(interpreter);

  // Set input 1 as constant tensor with data.
  // This requires hacking allocation type and data, because
  // SingleOpInterpreterBuilder doesn't support constant inputs.
  TfLiteTensor* const_tensor = interpreter->tensor(interpreter->inputs()[1]);
  const_tensor->allocation_type = kTfLiteMmapRo;
  const_tensor->data.i32 = broadcast_dims_data.data();

  ASSERT_EQ(interpreter->ModifyGraphWithDelegate(delegate_), kTfLiteOk);

  // Inspect the IrModel generated by the delegate.
  const ::ml_drift::ir::IrModel* ir_model = GetIrModel(delegate_);
  ASSERT_TRUE(ir_model);
  EXPECT_EQ(ir_model->inputs().size(), 1);
  EXPECT_EQ(ir_model->outputs().size(), 1);
  ASSERT_EQ(ir_model->ops().size(), 2);
  const ::ml_drift::ir::IrOp* transpose_op = ir_model->op(0);
  EXPECT_EQ(transpose_op->inputs.size(), 1);
  EXPECT_EQ(transpose_op->outputs.size(), 1);
  EXPECT_EQ(transpose_op->name, "transpose");
  const ::ml_drift::Transpose3DAttributes* attr =
      std::any_cast<::ml_drift::Transpose3DAttributes>(&transpose_op->attr);
  ASSERT_TRUE(attr);

  const ::ml_drift::ir::IrOp* tile_op = ir_model->op(1);
  const ::ml_drift::ir::IrTensor* tile_in =
      ir_model->tensor(tile_op->inputs[0]);
  const ::ml_drift::ir::IrTensor* tile_out =
      ir_model->tensor(tile_op->outputs[0]);
  EXPECT_TRUE(CanTile(*tile_in, *tile_out));

  // Sanity check inference.
  ASSERT_EQ(interpreter->AllocateTensors(), kTfLiteOk);
  ASSERT_EQ(interpreter->Invoke(), kTfLiteOk);
}

TEST_P(ConvertBroadcastInDimTest, IndicesWithMapBHWDC) {
  // Generate a model with a broadcast_in_dim op.
  SingleOpInterpreterBuilder model(kTfLiteBuiltinStablehloBroadcastInDim,
                                   /*version=*/1);
  model.AddInput(GetParam(), {1});    // input data
  model.AddInput(kTfLiteInt32, {1});  // broadcast_dimensions
  model.AddOutput(GetParam(), {1, 4, 1, 1, 1});
  std::vector<int> broadcast_dims_data = {1};

  // Build the interpreter and delegate it.
  std::unique_ptr<::tflite::Interpreter> interpreter = model.Build();
  ASSERT_TRUE(interpreter);

  // Set input 1 as constant tensor with data.
  // This requires hacking allocation type and data, because
  // SingleOpInterpreterBuilder doesn't support constant inputs.
  TfLiteTensor* const_tensor = interpreter->tensor(interpreter->inputs()[1]);
  const_tensor->allocation_type = kTfLiteMmapRo;
  const_tensor->data.i32 = broadcast_dims_data.data();

  ASSERT_EQ(interpreter->ModifyGraphWithDelegate(delegate_), kTfLiteOk);

  // Inspect the IrModel generated by the delegate.
  const ::ml_drift::ir::IrModel* ir_model = GetIrModel(delegate_);
  ASSERT_TRUE(ir_model);
  EXPECT_EQ(ir_model->inputs().size(), 1);
  EXPECT_EQ(ir_model->outputs().size(), 1);
  ASSERT_EQ(ir_model->ops().size(), 2);
  const ::ml_drift::ir::IrOp* transpose_op = ir_model->op(0);
  EXPECT_EQ(transpose_op->inputs.size(), 1);
  EXPECT_EQ(transpose_op->outputs.size(), 1);
  EXPECT_EQ(transpose_op->name, "transpose");
  const ::ml_drift::Transpose3DAttributes* attr =
      std::any_cast<::ml_drift::Transpose3DAttributes>(&transpose_op->attr);
  ASSERT_TRUE(attr);

  const ::ml_drift::ir::IrOp* tile_op = ir_model->op(1);
  const ::ml_drift::ir::IrTensor* tile_in =
      ir_model->tensor(tile_op->inputs[0]);
  const ::ml_drift::ir::IrTensor* tile_out =
      ir_model->tensor(tile_op->outputs[0]);
  EXPECT_TRUE(CanTile(*tile_in, *tile_out));

  // Sanity check inference.
  ASSERT_EQ(interpreter->AllocateTensors(), kTfLiteOk);
  ASSERT_EQ(interpreter->Invoke(), kTfLiteOk);
}

INSTANTIATE_TEST_SUITE_P(ConvertBroadcastInDimTest, ConvertBroadcastInDimTest,
                         ::testing::Values(  // clang-format off
      // go/keep-sorted start numeric=yes
      kTfLiteBool,
      kTfLiteFloat16,
      kTfLiteFloat32,
      kTfLiteInt8,
      kTfLiteInt16,
      kTfLiteInt32,
      kTfLiteUInt8,
      kTfLiteUInt16,
      kTfLiteUInt32
      // go/keep-sorted end
                                             // clang-format on
                             ));

}  // namespace
}  // namespace litert::ml_drift::ir
