// Copyright 2025 Google LLC.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#include <any>
#include <cstdlib>
#include <memory>
#include <string>
#include <tuple>
#include <vector>

#include "testing/base/public/gunit.h"
#include "absl/log/absl_log.h"  // from @com_google_absl
#include "ml_drift/common/data_type.h"  // from @ml_drift
#include "ml_drift/common/ir_model.h"  // from @ml_drift
#include "ml_drift/common/operations.h"  // from @ml_drift
#include "ml_drift/common/shape.h"  // from @ml_drift
#include "ml_drift/common/tensor.h"  // from @ml_drift
#include "third_party/odml/litert/ml_drift/tflite/convert/convert_testing_utils.h"
#include "third_party/odml/litert/ml_drift/tflite/convert/stub_delegate.h"
#include "third_party/odml/litert/ml_drift/tflite/ir_model_builder_helper.h"
#include "tflite/builtin_ops.h"
#include "tflite/c/builtin_op_data.h"
#include "tflite/c/c_api.h"
#include "tflite/c/common.h"
#include "tflite/interpreter.h"

namespace litert::ml_drift::ir {
namespace {

class ConvertConvTest
    : public ::testing::TestWithParam<std::tuple<
          TfLiteType, bool, bool, TfLitePadding, TfLiteFusedActivation, int>> {
 protected:
  void SetUp() override {
    delegate_ = CreateStubDelegate();
    ASSERT_TRUE(delegate_);
    std::tie(dtype_, const_weights_, use_bias_, padding_, activation_,
             groups_) = GetParam();
    weights_data_ = nullptr;
    bias_data_ = nullptr;
  }

  void TearDown() override {
    free(weights_data_);
    free(bias_data_);

    DeleteStubDelegate(delegate_);
  }

  TfLiteDelegate* delegate_;
  TfLiteType dtype_;
  bool const_weights_;
  bool use_bias_;
  TfLitePadding padding_;
  TfLiteFusedActivation activation_;
  int groups_;
  void* weights_data_ = nullptr;
  void* bias_data_ = nullptr;
};

TEST_P(ConvertConvTest, Parameterized) {
  // Generate a model with a conv op.
  SingleOpInterpreterBuilder model(kTfLiteBuiltinConv2d,
                                   /*version=*/1);
  const int input_channels = 2 * groups_;
  const int output_channels = 4 * groups_;
  model.AddInput(kTfLiteFloat32, {1, 2, 3, input_channels});  // input data
  model.AddInput(dtype_,
                 {output_channels, 1, 1, input_channels / groups_});  // weights
  if (use_bias_) {
    const TfLiteType bias_dtype =
        dtype_ == kTfLiteFloat16 ? kTfLiteFloat16 : kTfLiteFloat32;
    model.AddInput(bias_dtype, {output_channels});  // bias
  }
  model.AddOutput(kTfLiteFloat32, {1, 2, 3, output_channels});  // output
  TfLiteConvParams* params =
      reinterpret_cast<TfLiteConvParams*>(calloc(1, sizeof(TfLiteConvParams)));
  params->padding = padding_;
  params->stride_height = 1;
  params->stride_width = 1;
  params->activation = activation_;
  params->dilation_height_factor = 1;
  params->dilation_width_factor = 1;
  model.SetParameters(params);

  // Build the interpreter.
  std::unique_ptr<::tflite::Interpreter> interpreter = model.Build();
  ASSERT_TRUE(interpreter);

  if (const_weights_) {
    TfLiteTensor* weights = interpreter->tensor(interpreter->inputs()[1]);
    weights->allocation_type = kTfLiteMmapRo;
    weights_data_ = malloc(weights->bytes);
    weights->data.raw = static_cast<char*>(weights_data_);

    // Add mock quantization params for quantized types
    if (dtype_ == kTfLiteInt8 || dtype_ == kTfLiteInt4) {
      if (weights->quantization.type == kTfLiteAffineQuantization) {
        auto* quant_params = reinterpret_cast<TfLiteAffineQuantization*>(
            weights->quantization.params);
        if (quant_params && quant_params->scale &&
            quant_params->scale->size > 0 && quant_params->zero_point &&
            quant_params->zero_point->size > 0) {
          quant_params->scale->data[0] = 1.0f;
          quant_params->zero_point->data[0] = 0;
        }
      }
    }

    if (use_bias_) {
      TfLiteTensor* bias = interpreter->tensor(interpreter->inputs()[2]);
      bias->allocation_type = kTfLiteMmapRo;
      bias_data_ = malloc(bias->bytes);
      bias->data.raw = static_cast<char*>(bias_data_);
    }
  }

  // Delegate the graph.
  ASSERT_EQ(interpreter->ModifyGraphWithDelegate(delegate_), kTfLiteOk);

  // Inspect the IrModel generated by the delegate.
  const ::ml_drift::ir::IrModel* ir_model = GetIrModel(delegate_);
  if (!ir_model) {
    ABSL_LOG(INFO) << "IrModel is null";
  }
  ASSERT_TRUE(ir_model);
  const int expected_model_inputs = const_weights_ ? 1 : (use_bias_ ? 3 : 2);
  EXPECT_EQ(ir_model->inputs().size(), expected_model_inputs);
  EXPECT_EQ(ir_model->outputs().size(), 1);
  const bool is_fallback = const_weights_ && groups_ > 1;
  const int expected_ops_count =
      is_fallback ? (1 + groups_ + 1 + (activation_ == kTfLiteActNone ? 0 : 1))
                  : (activation_ == kTfLiteActNone ? 1 : 2);
  ASSERT_EQ(ir_model->ops().size(), expected_ops_count);

  const ::ml_drift::ir::IrOp* conv_op = nullptr;
  if (is_fallback) {
    // The first conv op in the fallback sequence is at index 1 (after SPLIT at
    // 0)
    conv_op = ir_model->op(1);
  } else {
    conv_op = ir_model->op(0);
  }

  int expected_conv_inputs = const_weights_ ? 1 : -1;
  if (!const_weights_) {
    expected_conv_inputs = 1;
    if (interpreter->inputs().size() >= 2) expected_conv_inputs++;
    if (use_bias_) expected_conv_inputs++;
  }
  EXPECT_EQ(conv_op->inputs.size(), expected_conv_inputs);
  EXPECT_EQ(conv_op->outputs.size(), 1);
  EXPECT_EQ(conv_op->name, "convolution_2d");
  const ::ml_drift::Convolution2DAttributes* attr =
      std::any_cast<::ml_drift::Convolution2DAttributes>(&conv_op->attr);
  ASSERT_TRUE(attr);
  EXPECT_EQ(attr->groups, 1);
  if (const_weights_) {
    const bool is_int4 = dtype_ == kTfLiteInt4;
    const bool is_int8 = dtype_ == kTfLiteInt8;
    if (is_int4 && !is_fallback) {
      EXPECT_FALSE((
          std::get<
              ::ml_drift::Tensor<::ml_drift::OHWI, ::ml_drift::DataType::INT4>>(
              attr->weights)
              .data.empty()));
    } else if (is_int8 && !is_fallback) {
      EXPECT_FALSE((
          std::get<
              ::ml_drift::Tensor<::ml_drift::OHWI, ::ml_drift::DataType::INT8>>(
              attr->weights)
              .data.empty()));
    } else {
      EXPECT_FALSE((std::get<::ml_drift::Tensor<::ml_drift::OHWI,
                                                ::ml_drift::DataType::FLOAT32>>(
                        attr->weights)
                        .data.empty()));
    }
    if (use_bias_) {
      EXPECT_FALSE(attr->bias.data.empty());
    } else {
      if (is_fallback) {
        // Fallback explicitly pad biases to 0
        EXPECT_FALSE(attr->bias.data.empty());
        for (float val : attr->bias.data) {
          EXPECT_EQ(val, 0.0f);
        }
      } else {
        EXPECT_TRUE(attr->bias.data.empty());
      }
    }
  } else {
    EXPECT_TRUE((std::get<::ml_drift::Tensor<::ml_drift::OHWI,
                                             ::ml_drift::DataType::FLOAT32>>(
                     attr->weights)
                     .data.empty()));
    EXPECT_TRUE(attr->bias.data.empty());
  }

  // Sanity check inference.
  ASSERT_EQ(interpreter->AllocateTensors(), kTfLiteOk);
  ASSERT_EQ(interpreter->Invoke(), kTfLiteOk);
}

INSTANTIATE_TEST_SUITE_P(
    ConvertConvTest, ConvertConvTest,
    ::testing::Combine(::testing::Values(kTfLiteFloat32, kTfLiteFloat16,
                                         kTfLiteInt8, kTfLiteInt4),  // dtype
                       ::testing::Bool(),  // const_weights
                       ::testing::Bool(),  // use_bias
                       ::testing::Values(kTfLitePaddingSame,
                                         kTfLitePaddingValid),  // padding
                       ::testing::Values(kTfLiteActNone,
                                         kTfLiteActRelu),  // activation
                       ::testing::Values(1, 2)             // groups
                       ),
    [](const ::testing::TestParamInfo<ConvertConvTest::ParamType>& info) {
      std::string name;
      auto dtype = std::get<0>(info.param);
      if (dtype == kTfLiteFloat32)
        name += "float32";
      else if (dtype == kTfLiteFloat16)
        name += "float16";
      else if (dtype == kTfLiteInt8)
        name += "int8";
      else if (dtype == kTfLiteInt4)
        name += "int4";
      name += std::string(std::get<1>(info.param) ? "_const" : "_runtime") +
              std::string(std::get<2>(info.param) ? "_bias" : "_nobias") +
              std::string(std::get<3>(info.param) == kTfLitePaddingSame
                              ? "_same"
                              : "_valid") +
              std::string(std::get<4>(info.param) == kTfLiteActNone
                              ? "_noactivation"
                              : "_relu") +
              "_groups" + std::to_string(std::get<5>(info.param));
      return name;
    });

TEST(ConvertConvFallbackTest, GroupedConvFallbackShapes) {
  auto delegate = CreateStubDelegate();
  ASSERT_TRUE(delegate);

  // Generate a model with a grouped conv op that triggers fallback
  // src_channels_per_group = 2, which is not divisible by 4.
  int groups = 2;
  int input_channels = 2 * groups;   // 4
  int output_channels = 4 * groups;  // 8

  SingleOpInterpreterBuilder model(kTfLiteBuiltinConv2d, /*version=*/1);
  model.AddInput(kTfLiteFloat32, {1, 2, 3, input_channels});  // input data
  model.AddInput(kTfLiteFloat32,
                 {output_channels, 1, 1, input_channels / groups});  // weights
  model.AddOutput(kTfLiteFloat32, {1, 2, 3, output_channels});       // output

  TfLiteConvParams* params =
      reinterpret_cast<TfLiteConvParams*>(calloc(1, sizeof(TfLiteConvParams)));
  params->padding = kTfLitePaddingValid;
  params->stride_height = 1;
  params->stride_width = 1;
  params->activation = kTfLiteActNone;
  params->dilation_height_factor = 1;
  params->dilation_width_factor = 1;
  model.SetParameters(params);

  std::unique_ptr<::tflite::Interpreter> interpreter = model.Build();
  ASSERT_TRUE(interpreter);

  // Force constant weights to trigger the grouped conv fallback logic
  TfLiteTensor* weights = interpreter->tensor(interpreter->inputs()[1]);
  weights->allocation_type = kTfLiteMmapRo;
  std::unique_ptr<void, decltype(&free)> weights_data(malloc(weights->bytes),
                                                      &free);
  weights->data.raw = static_cast<char*>(weights_data.get());

  ASSERT_EQ(interpreter->ModifyGraphWithDelegate(delegate), kTfLiteOk);

  const ::ml_drift::ir::IrModel* ir_model = GetIrModel(delegate);
  ASSERT_TRUE(ir_model);

  // Fallback results in Split -> 2x Convs -> Concat
  EXPECT_EQ(ir_model->ops().size(), 4);
  EXPECT_EQ(ir_model->op(0)->name, "split");
  EXPECT_EQ(ir_model->op(0)->outputs.size(), 2);
  EXPECT_EQ(ir_model->op(1)->name, "convolution_2d");
  EXPECT_EQ(ir_model->op(1)->outputs.size(), 1);
  EXPECT_EQ(ir_model->op(2)->name, "convolution_2d");
  EXPECT_EQ(ir_model->op(2)->outputs.size(), 1);
  EXPECT_EQ(ir_model->op(3)->name, "concat");

  DeleteStubDelegate(delegate);
}

TEST(ConvertConvFallbackTest, GroupedConvFallbackShapesDstNotDivisible) {
  auto delegate = CreateStubDelegate();
  ASSERT_TRUE(delegate);

  // src_channels_per_group = 8 / 2 = 4 (divisible by 4)
  // dst_channels_per_group = 12 / 2 = 6 (not divisible by 4)
  // Fallback should trigger.
  int groups = 2;
  int input_channels = 8;
  int output_channels = 12;

  SingleOpInterpreterBuilder model(kTfLiteBuiltinConv2d, /*version=*/1);
  model.AddInput(kTfLiteFloat32, {1, 2, 3, input_channels});
  model.AddInput(kTfLiteFloat32,
                 {output_channels, 1, 1, input_channels / groups});
  model.AddOutput(kTfLiteFloat32, {1, 2, 3, output_channels});

  TfLiteConvParams* params =
      reinterpret_cast<TfLiteConvParams*>(calloc(1, sizeof(TfLiteConvParams)));
  params->padding = kTfLitePaddingValid;
  params->stride_height = 1;
  params->stride_width = 1;
  params->activation = kTfLiteActNone;
  params->dilation_height_factor = 1;
  params->dilation_width_factor = 1;
  model.SetParameters(params);

  std::unique_ptr<::tflite::Interpreter> interpreter = model.Build();
  ASSERT_TRUE(interpreter);

  TfLiteTensor* weights = interpreter->tensor(interpreter->inputs()[1]);
  weights->allocation_type = kTfLiteMmapRo;
  std::unique_ptr<void, decltype(&free)> weights_data(malloc(weights->bytes),
                                                      &free);
  weights->data.raw = static_cast<char*>(weights_data.get());

  ASSERT_EQ(interpreter->ModifyGraphWithDelegate(delegate), kTfLiteOk);

  const ::ml_drift::ir::IrModel* ir_model = GetIrModel(delegate);
  ASSERT_TRUE(ir_model);

  // Fallback results in Split -> 2x Convs -> Concat
  EXPECT_EQ(ir_model->ops().size(), 4);
  EXPECT_EQ(ir_model->op(0)->name, "split");
  EXPECT_EQ(ir_model->op(0)->outputs.size(), 2);
  EXPECT_EQ(ir_model->op(1)->name, "convolution_2d");
  EXPECT_EQ(ir_model->op(1)->outputs.size(), 1);
  EXPECT_EQ(ir_model->op(2)->name, "convolution_2d");
  EXPECT_EQ(ir_model->op(2)->outputs.size(), 1);
  EXPECT_EQ(ir_model->op(3)->name, "concat");

  DeleteStubDelegate(delegate);
}

TEST(ConvertConvFallbackTest, GroupedConvNoFallback) {
  auto delegate = CreateStubDelegate();
  ASSERT_TRUE(delegate);

  // src_channels_per_group = 8 / 2 = 4 (divisible by 4)
  // dst_channels_per_group = 16 / 2 = 8 (divisible by 4)
  // Fallback should NOT trigger.
  int groups = 2;
  int input_channels = 8;
  int output_channels = 16;

  SingleOpInterpreterBuilder model(kTfLiteBuiltinConv2d, /*version=*/1);
  model.AddInput(kTfLiteFloat32, {1, 2, 3, input_channels});
  model.AddInput(kTfLiteFloat32,
                 {output_channels, 1, 1, input_channels / groups});
  model.AddOutput(kTfLiteFloat32, {1, 2, 3, output_channels});

  TfLiteConvParams* params =
      reinterpret_cast<TfLiteConvParams*>(calloc(1, sizeof(TfLiteConvParams)));
  params->padding = kTfLitePaddingValid;
  params->stride_height = 1;
  params->stride_width = 1;
  params->activation = kTfLiteActNone;
  params->dilation_height_factor = 1;
  params->dilation_width_factor = 1;
  model.SetParameters(params);

  std::unique_ptr<::tflite::Interpreter> interpreter = model.Build();
  ASSERT_TRUE(interpreter);

  TfLiteTensor* weights = interpreter->tensor(interpreter->inputs()[1]);
  weights->allocation_type = kTfLiteMmapRo;
  std::unique_ptr<void, decltype(&free)> weights_data(malloc(weights->bytes),
                                                      &free);
  weights->data.raw = static_cast<char*>(weights_data.get());

  ASSERT_EQ(interpreter->ModifyGraphWithDelegate(delegate), kTfLiteOk);

  const ::ml_drift::ir::IrModel* ir_model = GetIrModel(delegate);
  ASSERT_TRUE(ir_model);

  // No fallback results in a single Convolution_2d op
  ASSERT_EQ(ir_model->ops().size(), 1);
  EXPECT_EQ(ir_model->op(0)->name, "convolution_2d");

  DeleteStubDelegate(delegate);
}

TEST(ConvertConvTest, SpannedWeights) {
  IrModelBuilderOptions options;
  options.enable_spanned_weights = true;
  std::unique_ptr<TfLiteDelegate, void (*)(TfLiteDelegate*)> delegate(
      CreateStubDelegate(options), DeleteStubDelegate);

  SingleOpInterpreterBuilder model(kTfLiteBuiltinConv2d, /*version=*/1);
  model.AddInput(kTfLiteFloat32, {1, 2, 3, 4});   // input data
  model.AddInput(kTfLiteFloat32, {8, 1, 1, 4});   // weights
  model.AddOutput(kTfLiteFloat32, {1, 2, 3, 8});  // output
  TfLiteConvParams* params =
      reinterpret_cast<TfLiteConvParams*>(calloc(1, sizeof(TfLiteConvParams)));
  params->padding = kTfLitePaddingValid;
  params->stride_height = 1;
  params->stride_width = 1;
  params->activation = kTfLiteActNone;
  model.SetParameters(params);

  std::unique_ptr<::tflite::Interpreter> interpreter = model.Build();
  ASSERT_TRUE(interpreter);

  TfLiteTensor* weights_tensor = interpreter->tensor(interpreter->inputs()[1]);
  weights_tensor->allocation_type = kTfLiteMmapRo;
  std::vector<float> weights_data(8 * 1 * 1 * 4, 1.0f);
  weights_tensor->data.f = weights_data.data();
  weights_tensor->bytes = weights_data.size() * sizeof(float);

  ASSERT_EQ(interpreter->ModifyGraphWithDelegate(delegate.get()), kTfLiteOk);

  const ::ml_drift::ir::IrModel* ir_model = GetIrModel(delegate.get());
  ASSERT_TRUE(ir_model);
  ASSERT_EQ(ir_model->ops().size(), 1);

  const ::ml_drift::ir::IrOp* conv_op = ir_model->op(0);
  const auto* attr =
      std::any_cast<::ml_drift::Convolution2DAttributes>(&conv_op->attr);
  ASSERT_TRUE(attr);

  const auto& weights = std::get<
      ::ml_drift::Tensor<::ml_drift::OHWI, ::ml_drift::DataType::FLOAT32>>(
      attr->weights);
  EXPECT_TRUE(weights.data.empty());
  EXPECT_FALSE(weights.spanned_data.empty());
  EXPECT_EQ(weights.spanned_data.data(), weights_data.data());
}

TEST(ConvertConvTest, ConvToFullyConnected) {
  auto delegate = CreateStubDelegate();
  ASSERT_TRUE(delegate);

  SingleOpInterpreterBuilder model(kTfLiteBuiltinConv2d, /*version=*/1);
  model.AddInput(kTfLiteFloat32, {1, 1, 1, 4});   // input data
  model.AddInput(kTfLiteFloat32, {8, 1, 1, 4});   // weights
  model.AddOutput(kTfLiteFloat32, {1, 1, 1, 8});  // output

  TfLiteConvParams* params =
      reinterpret_cast<TfLiteConvParams*>(calloc(1, sizeof(TfLiteConvParams)));
  params->padding = kTfLitePaddingValid;
  params->stride_height = 1;
  params->stride_width = 1;
  params->activation = kTfLiteActNone;
  params->dilation_height_factor = 1;
  params->dilation_width_factor = 1;
  model.SetParameters(params);

  std::unique_ptr<::tflite::Interpreter> interpreter = model.Build();
  ASSERT_TRUE(interpreter);

  TfLiteTensor* weights = interpreter->tensor(interpreter->inputs()[1]);
  weights->allocation_type = kTfLiteMmapRo;
  std::unique_ptr<void, decltype(&free)> weights_data(malloc(weights->bytes),
                                                      &free);
  weights->data.raw = static_cast<char*>(weights_data.get());

  ASSERT_EQ(interpreter->ModifyGraphWithDelegate(delegate), kTfLiteOk);

  const ::ml_drift::ir::IrModel* ir_model = GetIrModel(delegate);
  ASSERT_TRUE(ir_model);

  // Fallback results in FullyConnected op
  ASSERT_EQ(ir_model->ops().size(), 1);
  EXPECT_EQ(ir_model->op(0)->name, "fully_connected");

  DeleteStubDelegate(delegate);
}

}  // namespace
}  // namespace litert::ml_drift::ir
