# Description:
#    BUILD file for creating the litert pip package.

package(
    default_visibility = ["//visibility:public"],
    licenses = ["notice"],
)

filegroup(
    name = "pip_package_files",
    srcs = [
        "README.md",
        "build_pip_package.sh",
    ],
)
