from typing import Any, Callable
from xdsl.irdl import SSAValue
from litert.python.google.tools import model_utils as mu
from litert.python.google.tools.model_utils.dialect import arith
from litert.python.google.tools.model_utils.dialect import tfl
from litert.python.google.tools.model_utils.matcher import match_pred

__all__ = ["registry"]

registry = {}

MatchPred = match_pred.MatchPred


def register(identifier: str):
  def reg(fn: Callable[[Any], None]):
    registry[identifier] = fn
    return fn

  return reg


def MatchOwnerOpName(name: str):
  def check_fn(value: SSAValue):
    op = value.owner
    MatchPred(isinstance(op, mu.core.MlirOpBase) and op.name == name)

  return check_fn


# fmt: off
# pyformat: disabledef
register("TFL_PseudoConstOp")(MatchOwnerOpName(tfl.PseudoConstOp.name))
register("TFL_ConstOp")(MatchOwnerOpName(tfl.ConstOp.name))
register("TFL_ConstantOp")(MatchOwnerOpName(tfl.ConstantOp.name))
register("Arith_ConstantOp")(MatchOwnerOpName(arith.ConstantOp.name))

register("TFL_AbsOp")(MatchOwnerOpName("tfl.abs"))
register("TFL_AddNOp")(MatchOwnerOpName("tfl.add_n"))
register("TFL_AddOp")(MatchOwnerOpName("tfl.add"))
register("TFL_ArgMaxOp")(MatchOwnerOpName("tfl.arg_max"))
register("TFL_ArgMinOp")(MatchOwnerOpName("tfl.arg_min"))
register("TFL_AssignVariableOp")(MatchOwnerOpName("tfl.assign_variable"))
register("TFL_Atan2Op")(MatchOwnerOpName("tfl.atan2"))
register("TFL_AveragePool2DOp")(MatchOwnerOpName("tfl.average_pool_2d"))
register("TFL_BasicLSTMOp")(MatchOwnerOpName("tfl.basic_lstm"))
register("TFL_BatchMatMulOp")(MatchOwnerOpName("tfl.batch_matmul"))
register("TFL_BatchToSpaceNdOp")(MatchOwnerOpName("tfl.batch_to_space_nd"))
register("TFL_BidirectionalSequenceLSTMOp")(MatchOwnerOpName("tfl.bidirectional_sequence_lstm"))
register("TFL_BitcastOp")(MatchOwnerOpName("tfl.bitcast"))
register("TFL_BitwiseXorOp")(MatchOwnerOpName("tfl.bitwise_xor"))
register("TFL_BroadcastArgsOp")(MatchOwnerOpName("tfl.broadcast_args"))
register("TFL_BroadcastToOp")(MatchOwnerOpName("tfl.broadcast_to"))
register("TFL_BucketizeOp")(MatchOwnerOpName("tfl.bucketize"))
register("TFL_CallOnceOp")(MatchOwnerOpName("tfl.call_once"))
register("TFL_CastOp")(MatchOwnerOpName("tfl.cast"))
register("TFL_CeilOp")(MatchOwnerOpName("tfl.ceil"))
register("TFL_ComplexAbsOp")(MatchOwnerOpName("tfl.complex_abs"))
register("TFL_ConcatenationOp")(MatchOwnerOpName("tfl.concatenation"))
register("TFL_ControlNodeOp")(MatchOwnerOpName("tfl.control_node"))
register("TFL_Conv2DOp")(MatchOwnerOpName("tfl.conv_2d"))
register("TFL_Conv3DOp")(MatchOwnerOpName("tfl.conv_3d"))
register("TFL_Conv3DTransposeOp")(MatchOwnerOpName("tfl.conv_3d_transpose"))
register("TFL_CosOp")(MatchOwnerOpName("tfl.cos"))
register("TFL_CumsumOp")(MatchOwnerOpName("tfl.cumsum"))
register("TFL_CustomOp")(MatchOwnerOpName("tfl.custom"))
register("TFL_CustomTfOp")(MatchOwnerOpName("tfl.custom_tf"))
register("TFL_DensifyOp")(MatchOwnerOpName("tfl.densify"))
register("TFL_DepthToSpaceOp")(MatchOwnerOpName("tfl.depth_to_space"))
register("TFL_DepthwiseConv2DOp")(MatchOwnerOpName("tfl.depthwise_conv_2d"))
register("TFL_DequantizeOp")(MatchOwnerOpName("tfl.dequantize"))
register("TFL_DilateOp")(MatchOwnerOpName("tfl.dilate"))
register("TFL_DivOp")(MatchOwnerOpName("tfl.div"))
register("TFL_DynamicUpdateSliceOp")(MatchOwnerOpName("tfl.dynamic_update_slice"))
register("TFL_EluOp")(MatchOwnerOpName("tfl.elu"))
register("TFL_EmbeddingLookupOp")(MatchOwnerOpName("tfl.embedding_lookup"))
register("TFL_EqualOp")(MatchOwnerOpName("tfl.equal"))
register("TFL_ExpOp")(MatchOwnerOpName("tfl.exp"))
register("TFL_ExpandDimsOp")(MatchOwnerOpName("tfl.expand_dims"))
register("TFL_ExternalConstOp")(MatchOwnerOpName("tfl.external_const"))
register("TFL_FakeQuantOp")(MatchOwnerOpName("tfl.fake_quant"))
register("TFL_FillOp")(MatchOwnerOpName("tfl.fill"))
register("TFL_FloorDivOp")(MatchOwnerOpName("tfl.floor_div"))
register("TFL_FloorModOp")(MatchOwnerOpName("tfl.floor_mod"))
register("TFL_FloorOp")(MatchOwnerOpName("tfl.floor"))
register("TFL_FullyConnectedOp")(MatchOwnerOpName("tfl.fully_connected"))
register("TFL_GatherNdOp")(MatchOwnerOpName("tfl.gather_nd"))
register("TFL_GatherOp")(MatchOwnerOpName("tfl.gather"))
register("TFL_GeluOp")(MatchOwnerOpName("tfl.gelu"))
register("TFL_GreaterEqualOp")(MatchOwnerOpName("tfl.greater_equal"))
register("TFL_GreaterOp")(MatchOwnerOpName("tfl.greater"))
register("TFL_HardSwishOp")(MatchOwnerOpName("tfl.hard_swish"))
register("TFL_HashtableFindOp")(MatchOwnerOpName("tfl.hashtable_find"))
register("TFL_HashtableImportOp")(MatchOwnerOpName("tfl.hashtable_import"))
register("TFL_HashtableOp")(MatchOwnerOpName("tfl.hashtable"))
register("TFL_HashtableSizeOp")(MatchOwnerOpName("tfl.hashtable_size"))
register("TFL_IfOp")(MatchOwnerOpName("tfl.if"))
register("TFL_ImagOp")(MatchOwnerOpName("tfl.imag"))
register("TFL_L2NormalizationOp")(MatchOwnerOpName("tfl.l2_normalization"))
register("TFL_LSTMOp")(MatchOwnerOpName("tfl.lstm"))
register("TFL_LeakyReluOp")(MatchOwnerOpName("tfl.leaky_relu"))
register("TFL_LessEqualOp")(MatchOwnerOpName("tfl.less_equal"))
register("TFL_LessOp")(MatchOwnerOpName("tfl.less"))
register("TFL_LocalResponseNormalizationOp")(MatchOwnerOpName("tfl.local_response_normalization"))
register("TFL_LogOp")(MatchOwnerOpName("tfl.log"))
register("TFL_LogSoftmaxOp")(MatchOwnerOpName("tfl.log_softmax"))
register("TFL_LogicalAndOp")(MatchOwnerOpName("tfl.logical_and"))
register("TFL_LogicalNotOp")(MatchOwnerOpName("tfl.logical_not"))
register("TFL_LogicalOrOp")(MatchOwnerOpName("tfl.logical_or"))
register("TFL_LogisticOp")(MatchOwnerOpName("tfl.logistic"))
register("TFL_MatrixDiagOp")(MatchOwnerOpName("tfl.matrix_diag"))
register("TFL_MatrixSetDiagOp")(MatchOwnerOpName("tfl.matrix_set_diag"))
register("TFL_MaxPool2DOp")(MatchOwnerOpName("tfl.max_pool_2d"))
register("TFL_MaximumOp")(MatchOwnerOpName("tfl.maximum"))
register("TFL_MeanOp")(MatchOwnerOpName("tfl.mean"))
register("TFL_MinimumOp")(MatchOwnerOpName("tfl.minimum"))
register("TFL_MirrorPadOp")(MatchOwnerOpName("tfl.mirror_pad"))
register("TFL_MulOp")(MatchOwnerOpName("tfl.mul"))
register("TFL_MultinomialOp")(MatchOwnerOpName("tfl.multinomial"))
register("TFL_NegOp")(MatchOwnerOpName("tfl.neg"))
register("TFL_NoValueOp")(MatchOwnerOpName("tfl.no_value"))
register("TFL_NonMaxSuppressionV4Op")(MatchOwnerOpName("tfl.non_max_suppression_v4"))
register("TFL_NonMaxSuppressionV5Op")(MatchOwnerOpName("tfl.non_max_suppression_v5"))
register("TFL_NotEqualOp")(MatchOwnerOpName("tfl.not_equal"))
register("TFL_NumericVerifyOp")(MatchOwnerOpName("tfl.NumericVerify"))
register("TFL_OneHotOp")(MatchOwnerOpName("tfl.one_hot"))
register("TFL_PReluOp")(MatchOwnerOpName("tfl.prelu"))
register("TFL_PackOp")(MatchOwnerOpName("tfl.pack"))
register("TFL_PadOp")(MatchOwnerOpName("tfl.pad"))
register("TFL_PadV2Op")(MatchOwnerOpName("tfl.padv2"))
register("TFL_PolyCallOp")(MatchOwnerOpName("tfl.poly_call"))
register("TFL_PowOp")(MatchOwnerOpName("tfl.pow"))
register("TFL_QConstOp")(MatchOwnerOpName("tfl.pseudo_qconst"))
register("TFL_QuantizeOp")(MatchOwnerOpName("tfl.quantize"))
register("TFL_RFFT2dOp")(MatchOwnerOpName("tfl.rfft2d"))
register("TFL_RandomStandardNormalOp")(MatchOwnerOpName("tfl.random_standard_normal"))
register("TFL_RandomUniformOp")(MatchOwnerOpName("tfl.random_uniform"))
register("TFL_RangeOp")(MatchOwnerOpName("tfl.range"))
register("TFL_RankOp")(MatchOwnerOpName("tfl.rank"))
register("TFL_ReadVariableOp")(MatchOwnerOpName("tfl.read_variable"))
register("TFL_RealOp")(MatchOwnerOpName("tfl.real"))
register("TFL_ReduceAllOp")(MatchOwnerOpName("tfl.reduce_all"))
register("TFL_ReduceAnyOp")(MatchOwnerOpName("tfl.reduce_any"))
register("TFL_ReduceMaxOp")(MatchOwnerOpName("tfl.reduce_max"))
register("TFL_ReduceMinOp")(MatchOwnerOpName("tfl.reduce_min"))
register("TFL_ReduceProdOp")(MatchOwnerOpName("tfl.reduce_prod"))
register("TFL_Relu0To1Op")(MatchOwnerOpName("tfl.relu_0_to_1"))
register("TFL_Relu1Op")(MatchOwnerOpName("tfl.relu_n1_to_1"))
register("TFL_Relu6Op")(MatchOwnerOpName("tfl.relu6"))
register("TFL_ReluOp")(MatchOwnerOpName("tfl.relu"))
register("TFL_ReshapeOp")(MatchOwnerOpName("tfl.reshape"))
register("TFL_ResizeBilinearOp")(MatchOwnerOpName("tfl.resize_bilinear"))
register("TFL_ResizeNearestNeighborOp")(MatchOwnerOpName("tfl.resize_nearest_neighbor"))
register("TFL_ReverseSequenceOp")(MatchOwnerOpName("tfl.reverse_sequence"))
register("TFL_ReverseV2Op")(MatchOwnerOpName("tfl.reverse_v2"))
register("TFL_RightShiftOp")(MatchOwnerOpName("tfl.right_shift"))
register("TFL_RoundOp")(MatchOwnerOpName("tfl.round"))
register("TFL_RsqrtOp")(MatchOwnerOpName("tfl.rsqrt"))
register("TFL_SVDFOp")(MatchOwnerOpName("tfl.svdf"))
register("TFL_ScatterNdOp")(MatchOwnerOpName("tfl.scatter_nd"))
register("TFL_SegmentSumOp")(MatchOwnerOpName("tfl.segment_sum"))
register("TFL_SelectOp")(MatchOwnerOpName("tfl.select"))
register("TFL_SelectV2Op")(MatchOwnerOpName("tfl.select_v2"))
register("TFL_ShapeOp")(MatchOwnerOpName("tfl.shape"))
register("TFL_SignOp")(MatchOwnerOpName("tfl.sign"))
register("TFL_SinOp")(MatchOwnerOpName("tfl.sin"))
register("TFL_SliceOp")(MatchOwnerOpName("tfl.slice"))
register("TFL_SoftmaxOp")(MatchOwnerOpName("tfl.softmax"))
register("TFL_SpaceToBatchNdOp")(MatchOwnerOpName("tfl.space_to_batch_nd"))
register("TFL_SpaceToDepthOp")(MatchOwnerOpName("tfl.space_to_depth"))
register("TFL_SparseConstOp")(MatchOwnerOpName("tfl.pseudo_sparse_const"))
register("TFL_SparseQConstOp")(MatchOwnerOpName("tfl.pseudo_sparse_qconst"))
register("TFL_SparseToDenseOp")(MatchOwnerOpName("tfl.sparse_to_dense"))
register("TFL_SplitOp")(MatchOwnerOpName("tfl.split"))
register("TFL_SplitVOp")(MatchOwnerOpName("tfl.split_v"))
register("TFL_SqrtOp")(MatchOwnerOpName("tfl.sqrt"))
register("TFL_SquareOp")(MatchOwnerOpName("tfl.square"))
register("TFL_SquaredDifferenceOp")(MatchOwnerOpName("tfl.squared_difference"))
register("TFL_SqueezeOp")(MatchOwnerOpName("tfl.squeeze"))
register("TFL_StridedSliceOp")(MatchOwnerOpName("tfl.strided_slice"))
register("TFL_SubOp")(MatchOwnerOpName("tfl.sub"))
register("TFL_SumOp")(MatchOwnerOpName("tfl.sum"))
register("TFL_TanhOp")(MatchOwnerOpName("tfl.tanh"))
register("TFL_TileOp")(MatchOwnerOpName("tfl.tile"))
register("TFL_TopKV2Op")(MatchOwnerOpName("tfl.topk_v2"))
register("TFL_TransposeConvOp")(MatchOwnerOpName("tfl.transpose_conv"))
register("TFL_TransposeOp")(MatchOwnerOpName("tfl.transpose"))
register("TFL_UnidirectionalSequenceLSTMOp")(MatchOwnerOpName("tfl.unidirectional_sequence_lstm"))
register("TFL_UnidirectionalSequenceRNNOp")(MatchOwnerOpName("tfl.unidirectional_sequence_rnn"))
register("TFL_UniqueOp")(MatchOwnerOpName("tfl.unique"))
register("TFL_UnpackOp")(MatchOwnerOpName("tfl.unpack"))
register("TFL_UnsortedSegmentMaxOp")(MatchOwnerOpName("tfl.unsorted_segment_max"))
register("TFL_UnsortedSegmentMinOp")(MatchOwnerOpName("tfl.unsorted_segment_min"))
register("TFL_UnsortedSegmentProdOp")(MatchOwnerOpName("tfl.unsorted_segment_prod"))
register("TFL_UnsortedSegmentSumOp")(MatchOwnerOpName("tfl.unsorted_segment_sum"))
register("TFL_VarHandleOp")(MatchOwnerOpName("tfl.var_handle"))
register("TFL_WhereOp")(MatchOwnerOpName("tfl.where"))
register("TFL_WhileOp")(MatchOwnerOpName("tfl.while"))
register("TFL_YieldOp")(MatchOwnerOpName("tfl.yield"))
register("TFL_ZerosLikeOp")(MatchOwnerOpName("tfl.zeros_like"))
# fmt: on
# pyformat: enable
