// Copyright 2026 Google LLC.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#ifndef LITERT_VENDORS_INTEL_OPENVINO_COMPILER_WEIGHT_BANK_ATTRIBUTES_H_
#define LITERT_VENDORS_INTEL_OPENVINO_COMPILER_WEIGHT_BANK_ATTRIBUTES_H_

#include <string>
#include <utility>

#include "openvino/core/rtti.hpp"
#include "openvino/core/runtime_attribute.hpp"

namespace litert {
namespace openvino {

// Marks an ov::op::v0::Constant as created/generated by LiteRT. This is the
// general-purpose tag for synthesized constants that are not plain converted
// weights. The attribute provides an optional stable source key for identity
// checks and diagnostics; callers should prefer it over relying on a friendly
// name prefix, which is easy to collide or rewrite during graph transforms.
class LiteRtGeneratedConstantAttribute : public ov::RuntimeAttribute {
 public:
  OPENVINO_RTTI("LiteRtGeneratedConstantAttribute", "0", ov::RuntimeAttribute);

  LiteRtGeneratedConstantAttribute() = default;
  explicit LiteRtGeneratedConstantAttribute(std::string source_key)
      : source_key(std::move(source_key)) {}

  bool is_copyable() const override { return true; }

  std::string source_key;  // Stable identity hint for dedup / registration.
};

}  // namespace openvino
}  // namespace litert

#endif  // LITERT_VENDORS_INTEL_OPENVINO_COMPILER_WEIGHT_BANK_ATTRIBUTES_H_
