/******************************************************************************
 * Copyright (C) 2025 Broadcom.
 * The term "Broadcom" refers to Broadcom Inc. and/or its subsidiaries.
 *
 * This program is the proprietary software of Broadcom and/or its licensors,
 * and may only be used, duplicated, modified or distributed pursuant to
 * the terms and conditions of a separate, written license agreement executed
 * between you and Broadcom (an "Authorized License").  Except as set forth in
 * an Authorized License, Broadcom grants no license (express or implied),
 * right to use, or waiver of any kind with respect to the Software, and
 * Broadcom expressly reserves all rights in and to the Software and all
 * intellectual property rights therein. IF YOU HAVE NO AUTHORIZED LICENSE,
 * THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 * IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.
 *
 * Except as expressly set forth in the Authorized License,
 *
 * 1.     This program, including its structure, sequence and organization,
 * constitutes the valuable trade secrets of Broadcom, and you shall use all
 * reasonable efforts to protect the confidentiality thereof, and to use this
 * information only in connection with your use of Broadcom integrated circuit
 * products.
 *
 * 2.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED
 * "AS IS" AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS
 * OR WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH
 * RESPECT TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL
 * IMPLIED WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR
 * A PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS, QUIET
 * ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION. YOU ASSUME
 * THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE SOFTWARE.
 *
 * 3.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM
 * OR ITS LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL,
 * INDIRECT, OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY
 * RELATING TO YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM
 * HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN
 * EXCESS OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1,
 * WHICHEVER IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY
 * FAILURE OF ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
 ******************************************************************************/
/* Portions generated by GENAI: Cursor 2.2.36 (IDE), Claude Sonnet 4.5 */
#include <cstdio>
#include "litert/cc/litert_compiled_model.h"
#include "litert/cc/litert_environment.h"
#include "litert/cc/litert_macros.h"
#include "litert/cc/litert_model.h"
#include "litert/cc/litert_options.h"
#include "bstorm_example_next.h"
#include "bstorm_common.h"
#include "bstorm_types.h"
#include "bstorm_core_internal.h"

static void usage(const char* prog)
{
    printf("Usage: %s [--input <input>] [--output <output>] [--expected <expected>] [--accuracy <normal/fp16/bf16/low/none>] [--dispatch_library_dir <dir>] <model.tflite>\n", prog);
}

int main(int argc, char** argv)
{
    const char *model_fname = NULL;
    const char *input = NULL;
    const char *output = NULL;
    const char *expected = NULL;
    const char *accuracy = NULL;
    const char *dispatch_library_dir = NULL;
    struct inference_parameters parameters;
    int cur_arg = 1;

    if (argc == 1) {
        usage(argv[0]);
        return 1;
    }
    for (; cur_arg < argc; cur_arg++) {
        const char* arg = argv[cur_arg];
        unsigned offset = 1;
        if (arg[0] != '-') {
            break;
        }
        if (strcmp(arg, "-h") == 0 || strcmp(arg, "--help") == 0) {
            usage(argv[0]);
            return 0;
        }
        if (arg[1] == '-') {
            offset = 2;
        }
        if (cur_arg + 1 < argc)  {
            const char* val = argv[cur_arg+1];
            if (strcmp(arg + offset, "input") == 0) {
                input = val;
            } else if (strcmp(arg + offset, "output") == 0) {
                output = val;
            } else if (strcmp(arg + offset, "expected") == 0) {
                expected = val;
            } else if (strcmp(arg + offset, "accuracy") == 0) {
                accuracy = val;
            } else if (strcmp(arg + offset, "dispatch_library_dir") == 0) {
                dispatch_library_dir = val;
            }
            cur_arg++;
        } else {
            fprintf(stderr, "%s: missing argument for option: '%s'\n", argv[0], arg);
            return 1;
        }
    }
    if (cur_arg < argc) {
        model_fname = argv[cur_arg];
        cur_arg++;
    } else {
        fprintf(stderr, "missing model\n");
        usage(argv[0]);
        return 1;
    }
    parameters.model_fname = model_fname;
    parameters.input = input;
    parameters.output = output;
    parameters.expected = expected;
    parameters.accuracy = accuracy;

    std::vector<litert::Environment::Option> env_options;
    if (dispatch_library_dir) {
        env_options.push_back(litert::Environment::Option{
            litert::Environment::OptionTag::DispatchLibraryDir,
            dispatch_library_dir,
        });
    }

    LITERT_ASSIGN_OR_RETURN(litert::Environment env, litert::Environment::Create(env_options));
    LITERT_ASSIGN_OR_RETURN(auto compilation_options, litert::Options::Create());
    LITERT_RETURN_IF_ERROR(compilation_options.SetHardwareAccelerators(litert::HwAccelerators::kNpu | litert::HwAccelerators::kCpu));
    LITERT_ASSIGN_OR_RETURN(litert::CompiledModel compiled_model, litert::CompiledModel::Create(env, parameters.model_fname, compilation_options));

    // Preallocate input/output buffers
    LITERT_ASSIGN_OR_RETURN(std::vector<litert::TensorBuffer> input_buffers, compiled_model.CreateInputBuffers());
    LITERT_ASSIGN_OR_RETURN(std::vector<litert::TensorBuffer> output_buffers, compiled_model.CreateOutputBuffers());

    // Fill input buffers: use input file if provided, otherwise fill with zeros
    if (parameters.input) {
        // Convert C++ TensorBuffer objects to C LiteRtTensorBuffer for read_input function
        std::vector<LiteRtTensorBuffer> c_tensor_buffers;
        for (size_t i = 0; i < input_buffers.size(); ++i) {
            c_tensor_buffers.push_back(input_buffers[i].Get());
        }
        read_input(parameters.input, c_tensor_buffers.data(), c_tensor_buffers.size());
    } else {
        // Fill all input buffers with zeros
        for (size_t i = 0; i < input_buffers.size(); ++i) {
            LITERT_ASSIGN_OR_RETURN(litert::RankedTensorType tensor_type, input_buffers[i].TensorType());
            const litert::Layout& layout = tensor_type.Layout();

            // Calculate total number of elements from dimensions
            size_t total_elements = 1;
            printf("Input tensor %zu dimensions: [", i);
            for (size_t d = 0; d < layout.Rank(); ++d) {
                printf("%d", layout.Dimensions()[d]);
                if (d < layout.Rank() - 1) printf(", ");
                total_elements *= layout.Dimensions()[d];
            }
            printf("]\n");
            printf("Total elements needed: %zu\n", total_elements);

            // Fill with zeros using raw bytes
            LITERT_ASSIGN_OR_RETURN(size_t packed_size, input_buffers[i].PackedSize());
            std::vector<uint8_t> zero_data(packed_size, 0);
            input_buffers[i].Write<uint8_t>(absl::MakeConstSpan(zero_data.data(), packed_size));
        }
    }

    // Invoke
    compiled_model.Run(input_buffers, output_buffers);

    // Write output to file if specified
    if (parameters.output || parameters.expected) {
        // Convert C++ TensorBuffer objects to C LiteRtTensorBuffer for write_output function
        std::vector<LiteRtTensorBuffer> c_tensor_buffers;
        for (size_t i = 0; i < output_buffers.size(); ++i) {
            c_tensor_buffers.push_back(output_buffers[i].Get());
        }
        if (parameters.output) {
            write_output(parameters.output, c_tensor_buffers.data(), c_tensor_buffers.size());
        }
        if (parameters.expected) {
            if (verify_outputs(parameters.expected, c_tensor_buffers.data(), c_tensor_buffers.size(), parameters.accuracy) != 0) {
                fprintf(stderr, "expected output does not match\n");
                return 1;
            }
        }
    }

    // Read the output
    LITERT_ASSIGN_OR_RETURN(litert::RankedTensorType output_tensor_type, output_buffers[0].TensorType());
    const litert::Layout& output_layout = output_tensor_type.Layout();

    // Calculate total number of output elements
    size_t output_total_elements = 1;
    printf("Output tensor dimensions: [");
    for (size_t d = 0; d < output_layout.Rank(); ++d) {
        printf("%d", output_layout.Dimensions()[d]);
        if (d < output_layout.Rank() - 1) printf(", ");
        output_total_elements *= output_layout.Dimensions()[d];
    }
    printf("]\n");
    printf("Total output elements: %zu\n", output_total_elements);

    // Read output based on element type
    if (output_tensor_type.ElementType() == litert::ElementType::Float32) {
        std::vector<float> data(output_total_elements);
        output_buffers[0].Read<float>(absl::MakeSpan(data));
        printf("Output data size = %zu\n", data.size());
        printf("First few output values: ");
        for (size_t i = 0; i < std::min(size_t(5), data.size()); ++i) {
            printf("%.6f ", data[i]);
        }
        printf("\n");
    } else if (output_tensor_type.ElementType() == litert::ElementType::UInt8) {
        std::vector<uint8_t> data(output_total_elements);
        output_buffers[0].Read<uint8_t>(absl::MakeSpan(data));
        printf("Output data size = %zu\n", data.size());
        printf("First few output values: ");
        for (size_t i = 0; i < std::min(size_t(5), data.size()); ++i) {
            printf("%d ", static_cast<int>(data[i]));
        }
        printf("\n");
    } else if (output_tensor_type.ElementType() == litert::ElementType::Int8) {
        std::vector<int8_t> data(output_total_elements);
        output_buffers[0].Read<int8_t>(absl::MakeSpan(data));
        printf("Output data size = %zu\n", data.size());
        printf("First few output values: ");
        for (size_t i = 0; i < std::min(size_t(5), data.size()); ++i) {
            printf("%d ", static_cast<int>(data[i]));
        }
        printf("\n");
    }
    return 0;
}
