/******************************************************************************
 * Copyright (C) 2025 Broadcom.
 * The term "Broadcom" refers to Broadcom Inc. and/or its subsidiaries.
 *
 * This program is the proprietary software of Broadcom and/or its licensors,
 * and may only be used, duplicated, modified or distributed pursuant to
 * the terms and conditions of a separate, written license agreement executed
 * between you and Broadcom (an "Authorized License").  Except as set forth in
 * an Authorized License, Broadcom grants no license (express or implied),
 * right to use, or waiver of any kind with respect to the Software, and
 * Broadcom expressly reserves all rights in and to the Software and all
 * intellectual property rights therein. IF YOU HAVE NO AUTHORIZED LICENSE,
 * THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 * IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.
 *
 * Except as expressly set forth in the Authorized License,
 *
 * 1.     This program, including its structure, sequence and organization,
 * constitutes the valuable trade secrets of Broadcom, and you shall use all
 * reasonable efforts to protect the confidentiality thereof, and to use this
 * information only in connection with your use of Broadcom integrated circuit
 * products.
 *
 * 2.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED
 * "AS IS" AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS
 * OR WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH
 * RESPECT TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL
 * IMPLIED WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR
 * A PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS, QUIET
 * ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION. YOU ASSUME
 * THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE SOFTWARE.
 *
 * 3.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM
 * OR ITS LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL,
 * INDIRECT, OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY
 * RELATING TO YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM
 * HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN
 * EXCESS OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1,
 * WHICHEVER IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY
 * FAILURE OF ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
 *
 * Portions generated by GenAI: Cursor 2.0, Claude Sonnet 4.5
 *
 ******************************************************************************/
#define BSTORM_DEBUG_LEVEL_VERBOSE 1
#include "bstorm_example_tensor.h"

#include <cstdio>
#include <complex>
#include "bstorm_types.h"
#include "bstorm_common.h"
#include "flatbuf/bstorm_flatbuf.h"
#include "bstorm_core_internal.h"
#include "common/bstorm_util_litert.h"

static bstorm_result bstorm_LiteRtExample_p_BlobsFromTensors(struct bstorm_Blobs* blobs, LiteRtTensorBuffer* tensors, unsigned count)
{
    bstorm_result rc = BSTORM_RESULT_INITIALIZER();
    bstorm_Blobs_Init(blobs);
    B_STORM_CHECKED_CALL(rc, bstorm_Blobs_AllocateBlobs, (blobs, count), err_blobs);
    for (unsigned i = 0; i < count; i++) {
        B_STORM_CHECKED_CALL(rc, bstorm_Blobs_UseInlineBlob, (blobs, i), err_blob);
        struct bstorm_Blob* blob = blobs->entry[i];
        B_STORM_ASSERT(blob);
        LiteRtTensorBuffer tensor = tensors[i];
        B_STORM_CONDITION(rc, tensor, err_tensor);
        B_STORM_CHECKED_CALL(rc, bstorm_LiteRt_BlobFromTensorBuffer, (blob, tensor), err_tensor);
    }
    return rc;

err_tensor:
err_blob:
    bstorm_Blobs_Clear(blobs);
    bstorm_Blobs_Uninit(blobs);
err_blobs:
    return rc;
}

int bstorm_LiteRtExample_WriteTensors(const char* fileName, LiteRtTensorBuffer* tensors, unsigned count)
{
    bstorm_result rc = BSTORM_RESULT_INITIALIZER();
    struct bstorm_Blobs blobs;
    B_STORM_ASSERT(fileName);
    B_STORM_ASSERT(tensors);
    B_STORM_CHECKED_CALL(rc, bstorm_LiteRtExample_p_BlobsFromTensors, (&blobs, tensors, count), err_convert);
    if (count == 1) {
        B_STORM_CHECKED_CALL(rc, bstorm_flatbuf_write_blob, (fileName, blobs.entry[0]), err_write);
    } else {
        B_STORM_CHECKED_CALL(rc, bstorm_flatbuf_write_blobs, (fileName, &blobs), err_write);
    }
    bstorm_Blobs_Clear(&blobs);
    bstorm_Blobs_Uninit(&blobs);
    return 0;

err_write:
    bstorm_Blobs_Clear(&blobs);
    bstorm_Blobs_Uninit(&blobs);
err_convert:
    return -1;
}

int bstorm_LiteRtExample_BlobsFromTensors(struct bstorm_Blobs* blobs, LiteRtTensorBuffer* tensors, unsigned count)
{
    bstorm_result rc = BSTORM_RESULT_INITIALIZER();
    B_STORM_CHECKED_CALL(rc, bstorm_LiteRtExample_p_BlobsFromTensors, (blobs, tensors, count), err_blobs);
    return 0;

err_blobs:
    return -1;
}
