/******************************************************************************
 * Copyright (C) 2025 Broadcom.
 * The term "Broadcom" refers to Broadcom Inc. and/or its subsidiaries.
 *
 * This program is the proprietary software of Broadcom and/or its licensors,
 * and may only be used, duplicated, modified or distributed pursuant to
 * the terms and conditions of a separate, written license agreement executed
 * between you and Broadcom (an "Authorized License").  Except as set forth in
 * an Authorized License, Broadcom grants no license (express or implied),
 * right to use, or waiver of any kind with respect to the Software, and
 * Broadcom expressly reserves all rights in and to the Software and all
 * intellectual property rights therein. IF YOU HAVE NO AUTHORIZED LICENSE,
 * THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 * IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.
 *
 * Except as expressly set forth in the Authorized License,
 *
 * 1.     This program, including its structure, sequence and organization,
 * constitutes the valuable trade secrets of Broadcom, and you shall use all
 * reasonable efforts to protect the confidentiality thereof, and to use this
 * information only in connection with your use of Broadcom integrated circuit
 * products.
 *
 * 2.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED
 * "AS IS" AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS
 * OR WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH
 * RESPECT TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL
 * IMPLIED WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR
 * A PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS, QUIET
 * ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION. YOU ASSUME
 * THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE SOFTWARE.
 *
 * 3.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM
 * OR ITS LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL,
 * INDIRECT, OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY
 * RELATING TO YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM
 * HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN
 * EXCESS OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1,
 * WHICHEVER IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY
 * FAILURE OF ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
 *
 * Portions generated by GenAI: Cursor 2.0, Claude Sonnet 4.5
 *
 ******************************************************************************/
#undef NDEBUG
#include <assert.h>
#include <stdbool.h>
#include <stdio.h>
#include <string.h>

#include "bstorm_example_next.h"
#include "bstorm_example_tensor.h"

#include "bstorm_types.h"
#include "bstorm_common.h"
/* #define BSTORM_DEBUG_LEVEL_VERBOSE 1 */
#include "bstorm_internal.h"
#include "bstorm_misc.h"
#include "bstorm_tolerance.h"
#include "flatbuf/bstorm_flatbuf.h"
#include "litert/c/litert_tensor_buffer.h"

static void copy_input(unsigned no, const struct bstorm_Blob& blob, LiteRtTensorBuffer tensor_buffer)
{
    unsigned bstorm_size = bstorm_BlobShape_Size(&blob.shape);

    // Get the packed size from LiteRT tensor buffer
    size_t litert_size;
    LiteRtStatus status = LiteRtGetTensorBufferPackedSize(tensor_buffer, &litert_size);
    assert(status == kLiteRtStatusOk);

    if (litert_size != bstorm_size) {
        fprintf(stderr, "input#%u not compatible: payload size %u, expected %zu (bytes)\n", no, bstorm_size, litert_size);
        assert(litert_size == bstorm_size);
    }

    assert(blob.data);

    // Lock the tensor buffer for writing
    void* tensor_data;
    status = LiteRtLockTensorBuffer(tensor_buffer, &tensor_data, kLiteRtTensorBufferLockModeReadWrite);
    assert(status == kLiteRtStatusOk);
    assert(tensor_data);

    // Copy data from blob to tensor buffer
    memcpy(tensor_data, blob.data, bstorm_size);

    // Unlock the tensor buffer
    status = LiteRtUnlockTensorBuffer(tensor_buffer);
    assert(status == kLiteRtStatusOk);

    return;
}

void read_input(const char* input, LiteRtTensorBuffer* tensors, unsigned count)
{
    bstorm_result rc = BSTORM_RESULT_INITIALIZER();
    if (input) {
        struct bstorm_flatbuf flatbuf_input;
        printf("Using input %s\n", input);
        rc = bstorm_flatbuf_read(input, &flatbuf_input, NULL);
        assert(BSTORM_SUCCESS(rc));
        if (flatbuf_input.blob) {
            LiteRtTensorBuffer tensor_buffer = tensors[0];
            assert(tensor_buffer);
            copy_input(0, *flatbuf_input.blob, tensor_buffer);
        } else if (flatbuf_input.blobs) {
            for (unsigned i = 0; i < flatbuf_input.blobs->count && i < count; i++) {
                LiteRtTensorBuffer tensor_buffer = tensors[i];
                const struct bstorm_Blob* blob = flatbuf_input.blobs->entry[i];
                assert(tensor_buffer);
                assert(blob);
                if (blob) {
                    copy_input(i, *blob, tensor_buffer);
                }
            }
        } else {
            assert(0);
        }
        bstorm_flatbuf_free(&flatbuf_input);
    }
    return;
}

void write_output(const char* output, LiteRtTensorBuffer* tensors, unsigned count)
{
    if (output) {
        bstorm_LiteRtExample_WriteTensors(output, tensors, count);
    }
    return;
}

static const struct bstorm_FloatCompareTolerance* parse_accuracy(const char* accuracy)
{
    if (strcmp(accuracy, "normal") == 0) {
        return &bstorm_ToleranceFloat32;
    } else if (strcmp(accuracy, "fp16") == 0) {
        return &bstorm_ToleranceFloat16;
    } else if (strcmp(accuracy, "bf16") == 0) {
        return &bstorm_ToleranceBfloat16;
    } else if (strcmp(accuracy, "low") == 0) {
        return &bstorm_ToleranceQuantizedInexact;
    } else if (strcmp(accuracy, "none") == 0) {
        return &bstorm_ToleranceNone;
    } else if (strcmp(accuracy, "exact") == 0) {
        return &bstorm_ToleranceExact;
    }
    return &bstorm_ToleranceNone;
}

int verify_outputs(const char* expected, LiteRtTensorBuffer* tensors, unsigned count, const char* accuracy)
{
    bstorm_result rc = BSTORM_RESULT_INITIALIZER();
    int irc;
    struct bstorm_Blobs output;
    struct bstorm_Blobs* blobs_expected;
    struct bstorm_Blobs _blobs_expected;
    struct bstorm_flatbuf flatbuf_expected;
    const struct bstorm_FloatCompareTolerance* tolerance = accuracy ? parse_accuracy(accuracy) : NULL;

    irc = bstorm_LiteRtExample_BlobsFromTensors(&output, tensors, count);
    B_STORM_CONDITION(rc, irc==0, err_output);
    bstorm_Blobs_Init(&_blobs_expected);
    B_STORM_CHECKED_CALL(rc, bstorm_Blobs_AllocateBlobs, (&_blobs_expected, 1), err_blobs);
    B_STORM_CHECKED_CALL(rc, bstorm_flatbuf_read, (expected, &flatbuf_expected, NULL), err_read);
    if (flatbuf_expected.blob) {
        _blobs_expected.entry[0] = flatbuf_expected.blob;
        blobs_expected = &_blobs_expected;
    } else if (flatbuf_expected.blobs) {
        blobs_expected = flatbuf_expected.blobs;
    } else {
        B_STORM_ERROR(rc, NotSupported, err_expected);
    }
    for (unsigned i = 0; i < output.count; i++) {
        const struct bstorm_Blob* blob_expected;
        const struct bstorm_Blob* blob_output;
        bool compare_results = true;
        unsigned elements_expected;
        if (i >= blobs_expected->count) {
            break;
        }
        printf("Verifying %u output with %s\n", count, expected);
        B_STORM_CHECKED_NULL_CALL(rc, blob_expected, bstorm_Blobs_GetBlob, (blobs_expected, i), err_blob);
        B_STORM_CONDITION(rc, blob_expected->data, err_blob);
        B_STORM_CHECKED_NULL_CALL(rc, blob_output, bstorm_Blobs_GetBlob, (&output, i), err_blob);
        elements_expected = bstorm_BlobShape_Scalar(&blob_expected->shape);
        if (tolerance == &bstorm_ToleranceNone) {
            unsigned elements = bstorm_BlobShape_Scalar(&blob_output->shape);
            if (elements > elements_expected) {
                B_STORM_DEBUG("Don't verify output:%u %u>%u", i, elements, elements_expected);
                compare_results = false;
            } else if (elements < elements_expected) {
                B_STORM_DEBUG("Verify partial output:%u %u(%u)", i, elements, elements_expected);
                elements_expected = elements;
            }
        }
        if (compare_results) {
            B_STORM_CHECKED_CALL(rc, bstorm_CompareResults, (NULL, blob_output, blob_expected->data, elements_expected, tolerance), err_compare);
        }
    }
    bstorm_Blobs_Clear(&_blobs_expected);
    bstorm_Blobs_Uninit(&_blobs_expected);
    bstorm_Blobs_Clear(&output);
    bstorm_Blobs_Uninit(&output);
    bstorm_flatbuf_free(&flatbuf_expected);
    return 0;

err_compare:
err_blob:
err_expected:
    bstorm_flatbuf_free(&flatbuf_expected);
err_read:
    bstorm_Blobs_Clear(&_blobs_expected);
    bstorm_Blobs_Uninit(&_blobs_expected);
err_blobs:
    bstorm_Blobs_Clear(&output);
    bstorm_Blobs_Uninit(&output);
err_output:
    return -1;
}
