load("@org_tensorflow//tensorflow:strict.default.bzl", "py_strict_binary")

package(
    # copybara:uncomment default_applicable_licenses = ["@org_tensorflow//tensorflow:license"],
    licenses = ["notice"],
)

# Commented out under the (b/279852433) because caused an error in the OSS
# TODO(zhurakovskyi): Uncomment when fixed.
# copybara:uncomment_begin
# py_strict_binary(
#     name = "label_image",
#     srcs = ["label_image.py"],
#     main = "label_image.py",
#     deps = [
#         "@org_tensorflow//third_party/py/PIL:pil",
#         "@org_tensorflow//third_party/py/numpy",
#         "//tflite/python:lite",
#     ],
# )
# copybara:uncomment_end
