def CreateTensorBufferFromHostMemory(py_data: object, dtype: str, num_elements: int) -> object: ...
def DestroyTensorBuffer(arg0: object) -> None: ...
def ReadTensor(arg0: object, arg1: int, arg2: str) -> object: ...
def WriteTensor(arg0: object, arg1: object, arg2: str) -> None: ...
