/******************************************************************************
 * Copyright (C) 2025 Broadcom.
 * The term "Broadcom" refers to Broadcom Inc. and/or its subsidiaries.
 *
 * This program is the proprietary software of Broadcom and/or its licensors,
 * and may only be used, duplicated, modified or distributed pursuant to
 * the terms and conditions of a separate, written license agreement executed
 * between you and Broadcom (an "Authorized License").  Except as set forth in
 * an Authorized License, Broadcom grants no license (express or implied),
 * right to use, or waiver of any kind with respect to the Software, and
 * Broadcom expressly reserves all rights in and to the Software and all
 * intellectual property rights therein. IF YOU HAVE NO AUTHORIZED LICENSE,
 * THEN YOU HAVE NO RIGHT TO USE THIS SOFTWARE IN ANY WAY, AND SHOULD
 * IMMEDIATELY NOTIFY BROADCOM AND DISCONTINUE ALL USE OF THE SOFTWARE.
 *
 * Except as expressly set forth in the Authorized License,
 *
 * 1.     This program, including its structure, sequence and organization,
 * constitutes the valuable trade secrets of Broadcom, and you shall use all
 * reasonable efforts to protect the confidentiality thereof, and to use this
 * information only in connection with your use of Broadcom integrated circuit
 * products.
 *
 * 2.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, THE SOFTWARE IS PROVIDED
 * "AS IS" AND WITH ALL FAULTS AND BROADCOM MAKES NO PROMISES, REPRESENTATIONS
 * OR WARRANTIES, EITHER EXPRESS, IMPLIED, STATUTORY, OR OTHERWISE, WITH
 * RESPECT TO THE SOFTWARE.  BROADCOM SPECIFICALLY DISCLAIMS ANY AND ALL
 * IMPLIED WARRANTIES OF TITLE, MERCHANTABILITY, NONINFRINGEMENT, FITNESS FOR
 * A PARTICULAR PURPOSE, LACK OF VIRUSES, ACCURACY OR COMPLETENESS, QUIET
 * ENJOYMENT, QUIET POSSESSION OR CORRESPONDENCE TO DESCRIPTION. YOU ASSUME
 * THE ENTIRE RISK ARISING OUT OF USE OR PERFORMANCE OF THE SOFTWARE.
 *
 * 3.     TO THE MAXIMUM EXTENT PERMITTED BY LAW, IN NO EVENT SHALL BROADCOM
 * OR ITS LICENSORS BE LIABLE FOR (i) CONSEQUENTIAL, INCIDENTAL, SPECIAL,
 * INDIRECT, OR EXEMPLARY DAMAGES WHATSOEVER ARISING OUT OF OR IN ANY WAY
 * RELATING TO YOUR USE OF OR INABILITY TO USE THE SOFTWARE EVEN IF BROADCOM
 * HAS BEEN ADVISED OF THE POSSIBILITY OF SUCH DAMAGES; OR (ii) ANY AMOUNT IN
 * EXCESS OF THE AMOUNT ACTUALLY PAID FOR THE SOFTWARE ITSELF OR U.S. $1,
 * WHICHEVER IS GREATER. THESE LIMITATIONS SHALL APPLY NOTWITHSTANDING ANY
 * FAILURE OF ESSENTIAL PURPOSE OF ANY LIMITED REMEDY.
 *
 * Portions generated by GenAI: Cursor 2.0, Claude Sonnet 4.5
 *
 ******************************************************************************/
#ifndef BSTORM_UTIL_LITERT_H_
#define BSTORM_UTIL_LITERT_H_

#include "bstorm_common.h"
#include "bstorm_types.h"

#include "litert/c/litert_common.h"
#include "litert/c/litert_model.h"
#include "litert/c/litert_tensor_buffer.h"

#define BSTORM_VENDOR_ID "Broadcom"

#ifdef __cplusplus
extern "C" {
#endif

enum bstorm_engine_control {
    bstorm_engine_disable,
    bstorm_engine_default,
    bstorm_engine_enable
};

enum bstorm_engine_control bstorm_engine_control_from_arg(const char* arg);
bool bstorm_boolean_from_arg(const char* arg);

bstorm_result bstorm_LiteRt_BlobShapeFromTensor(struct bstorm_BlobShape *shape, LiteRtTensor tensor);

bstorm_result bstorm_LiteRt_BlobFromTensorBuffer(struct bstorm_Blob *blob, LiteRtTensorBuffer tensor);

bstorm_result bstorm_LiteRt_LinkPayload(LiteRtRankedTensorType &tensor_type, void *tensor_data, size_t packed_size, struct bstorm_Blob &blob);

bstorm_result bstorm_LiteRt_convert_datatype(LiteRtElementType litert_datatype,enum bstorm_DataType &datatype);

bstorm_result bstorm_LiteRt_to_bstorm_error(LiteRtStatus status);

#define B_STORM_CHECKED_LITERT_CALL(rc, f, args, label)\
    do {\
        if (LiteRtStatus s = f args; s != kLiteRtStatusOk) { \
            rc=bstorm_LiteRt_to_bstorm_error(s);\
            rc=B_STORM_TRACE_ERROR(rc,"Call to function '%s' has failed", #f);goto label;\
        }\
    } while(0)

#ifdef __cplusplus
} /* extern "C" */
#endif

#endif /* #ifndef BSTORM_UTIL_LITERT_H_ */

