load("@rules_license//rules:license.bzl", "license")

package(default_visibility = ["//visibility:public"])

license(
    name = "license",
    package_name = "tensorflow",
)

exports_files(["LICENSE"])
