// Copyright 2026 Google LLC.
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//      http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

#ifndef THIRD_PARTY_ODML_LITERT_LITERT_CC_OPTIONS_LITERT_DISPATCH_DELEGATE_VENDOR_OPTIONS_H_
#define THIRD_PARTY_ODML_LITERT_LITERT_CC_OPTIONS_LITERT_DISPATCH_DELEGATE_VENDOR_OPTIONS_H_

#include <string>
#include <utility>
#include <vector>

#include "absl/strings/string_view.h"  // from @com_google_absl
#include "absl/types/span.h"  // from @com_google_absl
#include "litert/cc/litert_expected.h"
#include "litert/cc/litert_opaque_options.h"

#include "litert/cc/options/litert_concrete_options_base.h"

namespace litert {

// Mapping between a model tensor on a delegated function and its port index.
struct TensorPortMapping {
  // Required: Canonical tensor name from the model's signature. Must be
  // non-empty.
  std::string tensor_name;
  // Required: Zero-based index of the input or output port on the dispatch
  // operation (>= 0).
  int port_index = -1;
};

// All port mappings and signature information for a single delegated function.
//
// NOTE on backward/forward compatibility:
// If any supplementary fields are added to this struct in the future (e.g.,
// supplementary execution flags or scheduling hints), they MUST be wrapped in
// std::optional<T> (or have safe default values). When older and newer .so
// versions communicate via TOML, fields added in newer versions will not be
// present in serialized TOML strings generated by older runtimes.
struct FunctionMapping {
  // Required: Name of the delegated function/subgraph matching the dispatch
  // op's "function_name" attribute. Must be non-empty.
  std::string function_name;
  // Required: Name of the model signature corresponding to this delegated
  // function. Must be non-empty.
  std::string signature_name;
  // Port mappings for all input tensors to this function.
  // The vector may be empty if the delegated function has no inputs (e.g. entry
  // or generator nodes).
  std::vector<TensorPortMapping> input_tensor_ports;
  // Port mappings for all output tensors from this function.
  // The vector may be empty if the delegated function has no outputs (e.g. exit
  // or sink nodes).
  std::vector<TensorPortMapping> output_tensor_ports;
};

// Holds common model metadata constructed at the LiteRT runtime level and
// passed across the boundary down to the Southbound vendor dispatch layer.
//
// Because it is internal between the Dispatch Delegate and vendor plugins
// it is serialized to a TOML string wrapped within an OpaqueOptions instance.
class DispatchDelegateVendorOptions : public ConcreteOptionsBase {
 public:
  // Identifier string used to tag these options in the OpaqueOptions chain.
  static constexpr const char* kIdentifier = "dispatch_delegate_vendor_options";

  // Returns the unique discriminator identifying this option type.
  static const char* Discriminator() { return kIdentifier; }

  // Implements ConcreteOptionsBase: serializes options to TOML payload for
  // attachment to LiteRtOptions.
  LiteRtStatus GetOpaqueOptionsData(
      const char** identifier, void** payload,
      void (**payload_deleter)(void*)) const override;

  // Appends a new function mapping to the options.
  // Note: `DispatchDelegateVendorOptions` takes and retains ownership of the
  // appended `FunctionMapping` object.
  void AddFunctionMapping(FunctionMapping mapping) {
    function_mappings_.push_back(std::move(mapping));
  }

  // Returns an immutable view of all registered function mappings.
  // The returned span is valid for the lifetime of this options container.
  // The container retains ownership of all mappings.
  absl::Span<const FunctionMapping> FunctionMappings() const {
    return function_mappings_;
  }

  // Serializes all function mappings to a TOML-formatted string.
  std::string ToToml() const;

  // Deserializes a TOML-formatted string into a DispatchDelegateVendorOptions
  // object.
  static Expected<DispatchDelegateVendorOptions> CreateFromToml(
      absl::string_view toml_string);

  // Searches the given OpaqueOptions chain for the options tagged with
  // `kIdentifier` and deserializes them from the TOML payload.
  static Expected<DispatchDelegateVendorOptions> FromOpaqueOptions(
      OpaqueOptions& options);

 private:
  std::vector<FunctionMapping> function_mappings_;
};

}  // namespace litert

#endif  // THIRD_PARTY_ODML_LITERT_LITERT_CC_OPTIONS_LITERT_DISPATCH_DELEGATE_VENDOR_OPTIONS_H_
