class CompiledModelWrapper:
    def __init__(self, *args, **kwargs) -> None: ...
    def CreateInputBufferByName(self, arg0: str, arg1: str) -> object: ...
    def CreateInputBuffers(self, arg0: int) -> object: ...
    def CreateOutputBufferByName(self, arg0: str, arg1: str) -> object: ...
    def CreateOutputBuffers(self, arg0: int) -> object: ...
    def GetInputBufferRequirements(self, arg0: int, arg1: int) -> object: ...
    def GetNumSignatures(self) -> object: ...
    def GetOutputBufferRequirements(self, arg0: int, arg1: int) -> object: ...
    def GetSignatureByIndex(self, arg0: int) -> object: ...
    def GetSignatureIndex(self, arg0: str) -> object: ...
    def GetSignatureList(self) -> object: ...
    def Run(self, arg0: object, arg1: object) -> None: ...
    def RunByIndex(self, arg0: int, arg1: object, arg2: object) -> None: ...
    def RunByName(self, arg0: str, arg1: object, arg2: object) -> None: ...

def CreateCompiledModelFromBuffer(*args, **kwargs): ...
def CreateCompiledModelFromFile(*args, **kwargs): ...
