name: Build LiteRT Android Artifacts

on:
  push:
    tags:
    - v*.*.*
  pull_request:
    branches:
    - main
  schedule:
    - cron: "0 10 * * *"  # Run at 2am PST (10am UTC) every day to refresh the cache.
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build_android_on_linux:
    name: Build Android Artifacts on Linux
    runs-on: linux-x86-n2-16
    container:
      image: us-docker.pkg.dev/ml-oss-artifacts-published/ml-public-container/ml-build@sha256:12822904942562e7deb0c91fb0eb3dd9ec87b4292881108b166e44149422b87d
    steps:
      - name: Checkout code
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
        with:
          persist-credentials: false

      - name: Set up JDK
        uses: actions/setup-java@cf277c60eb25467037889841efdb72551f06f6c3 # v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Android SDK
        uses: android-actions/setup-android@9fc6c4e9069bf8d3d10b2204b1fb8f6ef7065407 # v3
        with:
          packages: >
            ndk;26.3.11579264
            build-tools;35.0.1
            platforms;android-35
            platform-tools
            cmdline-tools;latest

      - name: Export Android NDK env
        run: |
          echo "ANDROID_NDK_HOME=$ANDROID_HOME/ndk/26.3.11579264" >> $GITHUB_ENV
          echo "ANDROID_SDK_ROOT=$ANDROID_HOME" >> $GITHUB_ENV

      - name: Configure Bazel for Android
        run: |
          echo "build --action_env ANDROID_NDK_HOME=$ANDROID_HOME/ndk/26.3.11579264" >> .bazelrc

      - name: Accept Android Licenses
        run: yes | $ANDROID_HOME/cmdline-tools/latest/bin/sdkmanager --licenses

      - name: Build Android Artifacts with Bazel
        run: |
          bazel build --extra_toolchains=@bazel_tools//tools/jdk:all --config=android_arm64 //litert/kotlin:litert

      - name: Upload Android Artifacts
        if: github.event_name != 'pull_request'
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: android-artifacts
          path: |
            bazel-bin/litert/kotlin/litert.aar
            bazel-bin/tflite/java/tensorflow-lite-api.aar
            bazel-bin/tflite/java/tensorflow-lite.aar
            bazel-bin/tflite/java/tensorflow-lite-gpu-api.aar
            bazel-bin/tflite/java/tensorflow-lite-gpu.aar
