name: "linux_x86_64"
on:
  push:
    tags:
    - v*.*.*
  pull_request:
    branches:
    - main
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - 'g3doc/**'
      - 'site/**'
      - 'LICENSE'

  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  presubmit:
    name: "Presubmit-Linux"
    runs-on: linux-x86-n2-16
    container:
      image: us-docker.pkg.dev/ml-oss-artifacts-published/ml-public-container/ml-build:latest
    steps:
      - name: Install Git LFS
        run: |
          sudo apt-get update
          sudo apt-get install -y git-lfs
          git lfs install

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install System Dependencies
        run: |
          sudo apt-get update && sudo apt-get install -y --no-install-recommends libc++-18-dev libc++abi-18-dev llvm-18 clang-18

      - name: Configure tensorflow & python path
        run: |
          chmod +x configure.py
          export PYTHON_BIN_PATH=$(which python3)
          export PYTHON_LIB_PATH=$(python3 -c 'import site; print(site.getsitepackages()[0])')
          export TF_NEED_ROCM=0
          export TF_NEED_CUDA=0
          export TF_SET_ANDROID_WORKSPACE=0
          export CC_OPT_FLAGS='-Wno-sign-compare'
          yes "" | python3 configure.py

      - name: Run bazel build on Linux
        env:
          TEST_LANG_FILTERS: cc,py
        shell: bash
        run: |
          BUILD_FLAGS=(
            "--config=public_cache"
            "--config=bulk_test_cpu"
            "--test_lang_filters=${TEST_LANG_FILTERS}"
            "--test_output=errors"
            "--keep_going"
            "--repo_env=USE_PYWRAP_RULES=True"
          )

          LITERT_EXCLUDED_TARGETS=(
            "-//litert/c:litert_compiled_model_shared_lib_test"
            "-//litert/c:litert_compiled_model_test"
            "-//litert/cc:litert_compiled_model_test"
            "-//litert/cc:litert_environment_test"
            "-//litert/python/tools/model_utils/test/..."
            "-//litert/runtime:compiled_model_test"
            "-//litert/runtime/accelerators/gpu/..."
            "-//litert/tools:tool_display_test"
            "-//litert/tools:dump_test"
            "-//litert/tools:apply_plugin_test"
            "-//litert/vendors/intel_openvino/compiler:decoder_test"
            "-//litert/vendors/intel_openvino/dispatch:dispatch_api_openvino_test"
            "-//litert/vendors/intel_openvino/compiler:openvino_compiler_plugin_test"
          )

          bazel test "${BUILD_FLAGS[@]}" -- //tensor/... //litert/... //weight_loader/... "${LITERT_EXCLUDED_TARGETS[@]}"

      - name: Build Intel OpenVINO plugin for Linux
        run: |
          bazel build --config=public_cache \
            //litert/vendors/intel_openvino/compiler:libLiteRtCompilerPlugin_IntelOpenvino.so \
            //litert/vendors/intel_openvino/dispatch:libLiteRtDispatch_IntelOpenvino.so
