name: "macos-arm64"
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

  workflow_dispatch:  # Manual trigger

permissions:
  contents: read # Required

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  check:
    name: Check Changes
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    outputs:
      run_build: ${{ steps.check.outputs.run_build }}
    steps:
      - if: github.event_name == 'pull_request'
        uses: dorny/paths-filter@ceb8a2b8f2d89434be7ff52d3de7ec3738c5cc9d # v4.0.0
        id: filter
        with:
          predicate-quantifier: 'some-with-excludes'
          filters: |
            src:
              - '**'
              - '!*.md'
              - '!**/*.md'
              - '!docs/**'
              - '!g3doc/**'
              - '!site/**'
              - '!LICENSE'
      - name: Determine if build should run
        id: check
        shell: bash
        env:
          EVENT_NAME: ${{ github.event_name }}
          SRC_CHANGED: ${{ steps.filter.outputs.src }}
        run: |
          if [[ "${EVENT_NAME}" != "pull_request" || "${SRC_CHANGED}" == "true" ]]; then
            echo "run_build=true" >> "$GITHUB_OUTPUT"
          else
            echo "run_build=false" >> "$GITHUB_OUTPUT"
          fi

  presubmit:
    name: "Presubmit-Mac"
    needs: check
    if: needs.check.outputs.run_build == 'true'
    runs-on: macos-15

    steps:

      - name: Checkout code
        uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4
        with:
          persist-credentials: false

      - name: Setup Python
        uses: actions/setup-python@a26af69be951a213d495a4c3e4e4022e16d87065 # v5
        with:
          python-version: "3.11"

      - name: Configure tensorflow & python path
        run: |
          chmod +x configure.py
          export PYTHON_BIN_PATH=$(which python3)
          export PYTHON_LIB_PATH=$(python3 -c 'import site; print(site.getsitepackages()[0])')
          export TF_NEED_ROCM=0
          export TF_NEED_CUDA=0
          export TF_SET_ANDROID_WORKSPACE=0
          export CC_OPT_FLAGS='-Wno-sign-compare'
          python3 configure.py

      - name : Set up cache keys
        id: cache-keys
        run: |
          CACHE_RESTORE_KEY_2="${GITHUB_WORKFLOW}"
          CACHE_RESTORE_KEY_1="$CACHE_RESTORE_KEY_2-${{ hashFiles('**/WORKSPACE', '**/.bazelrc') }}"
          CACHE_RESTORE_KEY_0="$CACHE_RESTORE_KEY_1-${{ hashFiles('**/BUILD*') }}"
          # If it's not a pull request, then it will be the same as $CACHE_RESTORE_KEY_1-.
          CACHE_RESTORE_KEY_HEAD="$CACHE_RESTORE_KEY_0-${{ github.event.pull_request.base.sha }}"
          CACHE_KEY="$CACHE_RESTORE_KEY_0-${{ github.sha }}"
          echo "CACHE_RESTORE_KEY_2=$CACHE_RESTORE_KEY_2" >> "$GITHUB_OUTPUT"
          echo "CACHE_RESTORE_KEY_1=$CACHE_RESTORE_KEY_1" >> "$GITHUB_OUTPUT"
          echo "CACHE_RESTORE_KEY_0=$CACHE_RESTORE_KEY_0" >> "$GITHUB_OUTPUT"
          echo "CACHE_RESTORE_KEY_HEAD=$CACHE_RESTORE_KEY_HEAD" >> "$GITHUB_OUTPUT"
          echo "CACHE_KEY=$CACHE_KEY" >> "$GITHUB_OUTPUT"

      - name: Clean build outputs if cache is being refreshed.
        if: env.REFRESH_CACHE == 'true'
        run: bazel clean --expunge

      - name: Restore bazel cache if cache is not being refreshed.
        id: bazel-cache
        if: env.REFRESH_CACHE != 'true'
        uses: actions/cache/restore@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        with:
          path: |
            ~/.cache/bazel-macos
            ~/.cache/bazel-ios
          key: ${{ steps.cache-keys.outputs.CACHE_KEY }}
          restore-keys: |
            ${{ steps.cache-keys.outputs.CACHE_RESTORE_KEY_HEAD }}
            ${{ steps.cache-keys.outputs.CACHE_RESTORE_KEY_0 }}-
            ${{ steps.cache-keys.outputs.CACHE_RESTORE_KEY_1 }}-
            ${{ steps.cache-keys.outputs.CACHE_RESTORE_KEY_2 }}-

      - name: Check cache hit
        run: |
          echo "Cache Hit: ${STEPS_BAZEL_CACHE_OUTPUTS_CACHE_HIT}"
          echo "Cache Primary Key: ${STEPS_BAZEL_CACHE_OUTPUTS_CACHE_PRIMARY_KEY}"
          echo "Cache Matched Key: ${STEPS_BAZEL_CACHE_OUTPUTS_CACHE_MATCHED_KEY}"
        env:
          STEPS_BAZEL_CACHE_OUTPUTS_CACHE_HIT: ${{ steps.bazel-cache.outputs.cache-hit }}
          STEPS_BAZEL_CACHE_OUTPUTS_CACHE_PRIMARY_KEY: ${{ steps.bazel-cache.outputs.cache-primary-key }}
          STEPS_BAZEL_CACHE_OUTPUTS_CACHE_MATCHED_KEY: ${{ steps.bazel-cache.outputs.cache-matched-key }}

      - name: Run LiteRT tests
        env:
          TEST_LANG_FILTERS: cc,py
        run: |
          BUILD_FLAGS=(
            "--config=public_cache"
            "--config=bulk_test_cpu"
            "--config=macos_arm64"
            "--test_lang_filters=${TEST_LANG_FILTERS}"
            "--test_output=errors"
            "--keep_going"
            "--repo_env=USE_PYWRAP_RULES=True"
          )

          LITERT_EXCLUDED_TARGETS=(
            "-//litert/c:litert_compiled_model_shared_lib_test"
            "-//litert/c:litert_compiled_model_test"
            "-//litert/cc:litert_compiled_model_test"
            "-//litert/cc:litert_environment_test"
            "-//litert/python/..."
            "-//litert/runtime:compiled_model_test"
            "-//litert/runtime/accelerators/gpu/..."
            "-//litert/tools/..."
            "-//litert/vendors/..."
          )

          bazel test \
            "${BUILD_FLAGS[@]}" \
            -- \
            //litert/c/... \
            //litert/cc/... \
            //litert/runtime/... \
            "${LITERT_EXCLUDED_TARGETS[@]}"

      - name: Remove cache if cache is being refreshed.
        if: env.REFRESH_CACHE == 'true'
        continue-on-error: true  # Ignore errors when cache is not found.
        run: gh cache delete ${STEPS_CACHE_KEYS_OUTPUTS_CACHE_KEY}
        env:
          STEPS_CACHE_KEYS_OUTPUTS_CACHE_KEY: ${{ steps.cache-keys.outputs.CACHE_KEY }}

      - name: Save bazel cache if it's new or being refreshed.
        uses: actions/cache/save@0057852bfaa89a56745cba8c7296529d2fc39830 # v4
        if: env.REFRESH_CACHE == 'true' || steps.bazel-cache.outputs.cache-hit != 'true'
        with:
          path: |
            ~/.cache/bazel-macos
            ~/.cache/bazel-ios
          key: ${{ steps.cache-keys.outputs.CACHE_KEY }}
