name: "macos-arm64"
on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main
    paths-ignore:
      - '**.md'
      - 'docs/**'
      - 'g3doc/**'
      - 'site/**'
      - 'LICENSE'

  workflow_dispatch:  # Manual trigger

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
  cancel-in-progress: true

jobs:
  presubmit:
    name: "Presubmit-Mac"
    runs-on: macos-15

    steps:

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Configure tensorflow & python path
        run: |
          chmod +x configure.py
          export PYTHON_BIN_PATH=$(which python3)
          export PYTHON_LIB_PATH=$(python3 -c 'import site; print(site.getsitepackages()[0])')
          export TF_NEED_ROCM=0
          export TF_NEED_CUDA=0
          export TF_SET_ANDROID_WORKSPACE=0
          export CC_OPT_FLAGS='-Wno-sign-compare'
          python3 configure.py

      - name: Run LiteRT tests
        env:
          TEST_LANG_FILTERS: cc,py
        run: |
          BUILD_FLAGS=(
            "--config=public_cache"
            "--config=bulk_test_cpu"
            "--config=macos_arm64"
            "--test_lang_filters=${TEST_LANG_FILTERS}"
            "--test_output=errors"
            "--keep_going"
            "--repo_env=USE_PYWRAP_RULES=True"
          )

          LITERT_EXCLUDED_TARGETS=(
            "-//litert/c:litert_compiled_model_shared_lib_test"
            "-//litert/c:litert_compiled_model_test"
            "-//litert/cc:litert_compiled_model_test"
            "-//litert/cc:litert_environment_test"
            "-//litert/python/tools/model_utils/test/..."
            "-//litert/runtime:compiled_model_test"
            "-//litert/runtime/accelerators/gpu/..."
            "-//litert/tools:tool_display_test"
            "-//litert/tools:dump_test"
            "-//litert/tools:apply_plugin_test"
            "-//litert/vendors/intel_openvino/compiler:decoder_test"
            "-//litert/vendors/intel_openvino/dispatch:dispatch_api_openvino_test"
            "-//litert/vendors/intel_openvino/compiler:openvino_compiler_plugin_test"
          )

          bazel test \
            --cache_test_results=no \
            "${BUILD_FLAGS[@]}" \
            -- \
            //litert/... \
            //tensor/... \
            //weight_loader/... \
            "${LITERT_EXCLUDED_TARGETS[@]}"
